var cnItems = {
    _OTHER_: [],

    'Incremancer': '僵尸增量',
    'Blood': '血液',
    'blood': '血液',
    'Energy': '能量',
    'energy': '能量',
    'Brains': '大脑',
    'brains': '大脑',
    'Humans': '人类',
    'Zombies': '僵尸',
    'zombies': '僵尸',
    'Level': '等级',
    'Take control of a horde of zombies to ravage small towns': '控制一群僵尸破坏小镇',
    'Energy refills over time. You need 10 energy to spawn a zombie by clicking on the ground.': '随着时间的流逝，能量会补充。 需要10能量才能单击地面来生成僵尸。',
    'Hold shift or control to spawn multiple zombies with a single click.': '按住Shift或Ctrl单击即可生成多个僵尸。',
    'Whenever one of your zombies attacks a human you will collect some blood.': '每当您的僵尸攻击一个人时，您都会收集一些血液。',
    'Killing a human or turning them into a zombie will earn you 1 brain.': '杀死人类或将他们变成僵尸将为您赢得1个大脑。',
    'You can spend these currencies in the shop to purchase upgrades for your zombie horde.': '您可以在商店中花费这些货币购买僵尸部落的升级。',
    'Hold shift to buy the maximum affordable number of upgrades.': '按住Shift键可购买最大数量的升级。',
    'The world can be dragged with the mouse to explore it. Or by using the WASD or arrow keys.': '可以用鼠标拖动世界进行探索。 或者使用WASD或箭头键。',
    'You can zoom in and out using your mouse wheel. Pinch to zoom on mobile.': '您可以使用鼠标滚轮放大和缩小。手机上可以使用双指缩放。',
    'Start Level': '开始等级',
    'Shop': '商店',
    'Options': '选项',
    'Stats': '统计',
    'Health': '生命',
    'Damage': '伤害',
    'Civilians': '平民',
    'Police': '警察',
    'Army': '军队',
    'How to play': '游戏指引',
    'Close': '关闭',
    'Complete': '已完成',
    'Completed': '已完成',
    'Your zombies thirst for blood and do +1 damage for each rank of Bloodthirst.': '你的僵尸渴求鲜血，每等级的嗜血+1伤害。',
    'Bloodthirst': '嗜血',
    'Your zombies gain tougher skin and +10 health with each rank.': '每等级僵尸都会获得更坚硬的皮肤，+10生命值。',
    'Like Leather': '皮革般的',
    'Cold Storage': '冷冻保存',
    'Turns out you can use all of your spare blood to store brains and keep them fresh. Each rank increases your maximum brain capacity by 50.': '事实证明，您可以使用所有剩余的血液来储存大脑并保持新鲜。 每个等级都会使您的大脑上限增加50。',
    'Recycling is Cool': '回收棒棒哒',
    'Why are we wasting so many good brains on this project? Each rank increases your chance to get a brain back from a dead zombie by': '为什么我们在这个项目上浪费了这么多大脑呢？ 每个等级都会使您从死去的僵尸中回收大脑的机会增加',
    'Your Soul is Mine!': '你的灵魂属于我！',
    'Using your most powerful blood magic you command the bodies of the dead to rise as your servants! Each rank grants 10% chance that dead humans will turn into zombies.': '使用最强大的鲜血魔法，您可以命令死者的身体作为仆人重生！ 每个等级都会给死人变成僵尸的机会提高10％。',
    'Blood capacity too low\n        ': '血液上限不够',
    'Unholy Construction': '邪恶建筑',
    'Learn the art of Unholy Construction in order to build structures that will solidify your foothold on the town.': '学习邪恶建筑的技巧，以便建造可以巩固您在城镇上立足的建筑。',
    'Energy Rush': '能量补充',
    'Master Summoner': '召唤大师',
    'Primal Reflexes': '原始反射',
    'Blood Harvest': '血液采集',
    'Available': '可用',
    'Pause': '暂停',
    'Cancel': '取消',
    'Bones': '骨头',
    'Construction': '建筑',
    'Cursed Graveyard': '诅咒墓地',
    'Graveyard': '墓地',
    'All': '全部',
    'Add to Home Screen': '添加到主屏幕',
    'A trophy is available on this level.': '通过这关可以获得一个战利品',
    'All the brains you harvested have proved fruitful in your experiments. Each rank raises your maximum energy by 5.': '你获得的大脑大幅推进了你的实验，每级提高你能量上限5点',
    'All the humans are either dead or undead!': '死，或者变成僵尸',
    'All this brain power has enabled you to devise some superior blood storage methods. Each rank increases your maximum blood by 10%.': '你用大脑设计出了一些新的血液储存方法，每级提高你血液上限10%',
    'Amount': '数量',
    'as some of their effects will only activate when a new level is started.': '有些效果只能在开始新关卡后生效',
    'Auto Release': '自动召唤',
    'Auto Start Next Level': '自动进入下一关',
    'Automatically start the next level after 3 seconds. If you want to play without actually playing.': '完成关卡三秒后自动进入下一关，如果你想自动进行游戏就启动它',
    'Begin Construction': '开始建造建筑',
    'Bone Collectors ': '骨头收集者',
    'Caged Zombies ': '僵尸笼',
    'Causes any zombie spawned using energy to be a Gigazombie. This will increase their health and damage by 10x, and energy cost by 5x.': '使召唤的所有僵尸都变成巨人僵尸，巨人僵尸攻击和血量十倍，但能量消耗五倍',
    'Choose your preferred resolution to render the game.': '选择你的游戏分辨率',
    'Collected': '已收集',
    'Consuming \n      ': '重要的',
    'Control how many zombies the graveyard spawns each time your energy is full. This is limited by your maximum energy.': '控制每当你满能量时召唤的僵尸数量，上限取决于你的能量上限',
    'Cost': '消耗',
    'Creatures': '召唤物',
    'Creatures can be automatically built until they reach your set limit.': '召唤物可以自动制造直到你设置的数量上限',
    'Download Save File': '下载存档',
    'Each time you level up a creature its health and damage will increase by 75%, but the cost will increase by 100%. Make sure you can afford it because there\'s no going back.': '每次你升级傀儡，傀儡会获得75%的攻击血量加成，但消耗会提高100%，由于不能降级请酌情升级',
    'Earn bonuses by collecting the severed heads of VIPs from certain towns. These trophies persist through prestige resets, while escaped VIPs will return to town.': '在某些城镇可以收集VIP的头颅获得加成，转生会保留VIP加成，并重新刷新逃跑的VIP',
    'Factory': '工厂',
    'Gigazombies ': '巨型僵尸',
    'Harpies ': '鹰身女妖',
    'Hire bone collectors to gather bones from the town\'s dead and your own fallen zombies. Each bone collector consumes 1 energy per second. They\'re hungry little creatures. Must be all that running around.': '雇用骨头收集者从城镇死者和您自己的丧尸中收集骨头。 每个骨骼收集器每秒消耗1能量。 他们是饥饿的小动物。 必须是所有运行。',
    'i': 'i',
    'If you\'re unable to zoom with other methods this will add some buttons to the screen for zooming the map.': '如果您无法使用其他方法进行缩放，则会在屏幕上添加一些按钮来缩放地图。',
    'Import or export a saved game': '导入或导出游戏存档',
    'Import Save': '导入存档',
    'Info': '信息',
    'It is recommended to spend your points before clicking start game': '最好在开始游戏前使用你的点数',
    'It\'s time to start from the beginning again, but this time stronger and faster.': '是时候重新开始游戏了，不过这一次你变得更强',
    'Level Select': '等级选择',
    'Load from Cloud': '加载云存档',
    'Manage Save': '管理存档',
    'Max': '最大',
    'Melting brains down in your cauldron to make smoothies can be beneficial for your health. It also increases your energy rate by 0.5 per second for each rank.': '把大脑放进锅里熬成羹对你有益，每级可以提高你0.5能量恢复每秒',
    'Minions': '奴隶',
    'Off': '关闭',
    'parts': '零件',
    'Parts': '零件',
    'Prestige': '声望',
    'Prestige Menu': '声望菜单',
    'Prestige Now': '现在声望',
    'Production stopped, need more\n      ': '生产停止，需要更多',
    'Release': '释放',
    'Release harpies that drop barrels of plague infected zombie flesh on unsuspecting humans. Each harpy consumes 1 energy per second.': '召唤哈比并向毫无防备的人类投掷毒桶，每个哈比每秒消耗1能量',
    'Render Resolution': '渲染分辨率',
    'Reset': '重置',
    'Reset Game': '重置游戏',
    'Rune of Death': '死亡符文',
    'Rune of Life': '生命符文',
    'Runesmith': '符文工匠',
    'Sacrifice': '牺牲',
    'Save to Cloud': '保存到云',
    'Show Framerate Counter': '显示帧率计数器',
    'Show Zoom Buttons': '显示缩放按钮',
    'Speed': '速度',
    'Stat Totals': '统计汇总',
    'The rune of death increases your zombies offensive capabilities': '死亡符文提高僵尸的进攻能力',
    'The rune of life increases your zombies defensive capabilities': '生命符文提高僵尸的生存能力',
    'The runesmith enchants your zombies with magical symbols of life and death. These runes can be infused with resources to increase their power.': '符文工厂可以给你的僵尸进行生命和死亡附魔，你可以给符文投入资源来加强符文效果',
    'The zombies retain more of their human agility increasing run speed by 1 for each rank.': '僵尸保持更多的作为人类时的行动力，因此每级提高1移动速度',
    'This will reset all save data if you want to start from the very beginning again.': '这会使你失去所有存档，请确保你想重新开始游戏',
    'This will reset your game progress but grant you powerful prestige points to spend.': '这会使你重新开始游戏但获得可使用的转生点数',
    'Toggle Full Screen': '全屏显示',
    'Toggle full screen mode. Can be helpful on smaller screen devices.': '全屏显示模式，在某些小屏幕的设备上也许很有用',
    'Total Cost': '总消耗',
    'Trophies': '战利品',
    'Uncollected': '未收集',
    'Upgrade': '升级',
    'Used for performance testing': '性能测试用',
    'VIP Escaped': 'VIP已逃跑',
    'Warning: Importing a save game will overwrite your current progress': '警告: 导入存档会覆盖你当前的存档',
    'You can add this game to your smartphones home screen without having to install anything.': '你可以把本游戏添加到手机桌面，不需要下载任何东西',
    'You can go directly to any level previously completed, but only after the preceding boss level has been beaten.': '你可以在打倒最终BOSS之后自由跳转至本区域的任何一关',
    'You currently have ': '你已经获得',
    'You have been defeated': '你已经击败',
    'You have prestiged!': '你已经转生',
    'Zombies to Spawn ': '召唤僵尸',
    '50% will run better on slower hardware but may look blurry.': '50%在较低配置的硬件上运行更流畅，但可能看起来模糊。',
    '100% will pixel match the resolution reported by your browser.': '100%将匹配你浏览器的分辨率。',
    '200% will double the reported values which may look better on retina devices or smartphones.': '200%是你浏览器分辨率的两倍，这可能在视网膜屏幕或智能手机上看起来更好。',
    'Construct a Cursed Graveyard in the town that will automatically spawn zombies when your energy is at its maximum!': '在城镇中建造一个被诅咒的墓地，当你的能量达到最大值时，它将自动产生僵尸!',
    'Explode your zombies into clouds of plague, cost 69 energy... nice': '使你所有僵尸自爆，消耗69能量...很好',
    '\n each second\n': '每秒',
    'prestige points to spend': '消耗转生点',
    'Gigazombies': '巨人僵尸',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'add': '添加',
    '% parts income': '%的零件收入',
    '% brains income': '%的大脑收入',
    '% bones income': '%的骨头收入',
    '% damage reduction': '%的伤害减免',
    '% runic syphon': '%符文弯管',
    '% chance to recover brain': '%几率回收大脑',
    '% zombie health': '%僵尸血量',
    '% zombie damage': '%僵尸攻击',
    '% max brains': '%大脑上限',
    '% max blood': '%血液上限',
    '%count%': '%数%',
    '% plague damage': '%瘟疫的伤害',
    '% plague healing': '%瘟疫治疗',
    '% blood income': '%血液收入',
    '5x Energy rate for 20 seconds, cost 50 energy': '20秒内能量恢复5x，消耗50能源',
    'Acursed Aviary': '尖顶鸟舍',
    'addChildAt: The index ': 'addChildAt:索引',
    'Additional 10% graveyard health during boss levels with each rank.': 'boss等级每级增加10%墓地生命值。',
    'Complete called again for an already completed resource.': 'Complete再次调用已完成的资源。',
    'The VIP has been killed!': 'VIP被杀了!',
    'The VIP has escaped!': 'VIP逃走了!',
    'The VIP is escaping!': 'VIP在逃跑!',
    'alpha': 'α',
    'button': '按钮',
    'Hold shift or control to spawn multiple zombies with a single click.': '按住shift键或control键，一键生成多个僵尸。',
    'octet/stream': '八隅体/流',
    'put': '把',
    'Turn your fort into a fortress. The additional space will also allow you to store 70% more blood and brains.': '把你的堡垒变成堡垒。额外的空间也能让你多储存70%的血液和大脑。',
    'Turn your fortress into a towering citadel that looms over the town. The additional space will also allow you to store 80% more blood and brains.': '把你的堡垒变成一座高耸入云的城堡。额外的空间也能让你多储存80%的血液和大脑。',
    'Turn your crypt into a fort. The additional space will also allow you to store 60% more blood and brains.': '把你的地穴变成堡垒。额外的空间也能让你多储存60%的血液和大脑。',
    'Freeze all humans in place preventing them from moving for 15 seconds, cost 75 energy': '把所有人都冻结在原地，让他们无法移动15秒，消耗75点能量',
    'white': '白色',
    'saturate': '饱和',
    'save': '保存',
    'saved to playfab': '保存到playfab',
    'fort': '堡',
    'fortress': '堡垒',
    'Cursed Graveyard': '被诅咒的墓地',
    'race': '比赛',
    'pen': '笔',
    'darken': '变黑',
    'Identifier': '标识符',
    'concurrency': '并发性',
    'Concurrency must not be zero': '并发性不能为零',
    'patch': '补丁',
    'unsafe:': '不安全:',
    'unsafe': '不安全的',
    'Not just dapper, these spikes help channel your energy. Each rank increases energy rate by 0.2 per second.': '不仅仅是威风，这些长钉还能引导你的能量。每级增加0.2能量恢复每秒。',
    'parts': '零件',
    'Parts: ': '零件:',
    'Part Factory': '零件工厂',
    'Parts Rate': '零件产量',
    'Property': '财产',
    'cursive': '草书',
    'test': '测试',
    'query': '查询',
    'common': '常见的',
    'constant': '常数',
    'timeout': '超时',
    'html': '超文本标记语言',
    'serif': '衬线',
    'A promises callback cannot return that same promise.': '承诺回调不能返回相同的承诺。',
    'citadel': '城堡',
    'multiply': '乘',
    'Hold shift to buy the maximum affordable number of upgrades.': '持有移位购买最多可负担的升级次数。',
    ' is out of bounds': '出界',
    'init': '初始化',
    'dispose': '处理',
    'handlers': '处理程序',
    'touch': '触摸',
    'You must pass a buffer when creating an attribute': '创建属性时必须传递缓冲区',
    'off': '从',
    'Game Loaded from Cloud': '从云端下载游戏',
    'destroy': '摧毁',
    'error': '错误',
    'Error: ': '错误:',
    'Big Boned': '大骨架',
    'brains': '大脑',
    'Brains: ': '大脑:',
    'Brain Storage': '大脑存储',
    'Brains Storage: ': '大脑存储:',
    'Brain Cage': '大脑笼',
    'Brain Rate': '大脑率',
    ' brains per second': '大脑每秒',
    'Brains capacity too low': '大脑容量太低',
    'size': '大小',
    'uppercase': '大写字母',
    ' parts while you were away': '当你不在的时候',
    'Each rank gives you an additional 500 blood, 50 brains, and 200 bones when starting a new level.': '当你开始一个新的等级时，每个等级会给你额外的500个血液，50个大脑和200个骨头。',
    'Prop': '道具',
    'get': '得到',
    'name': '的名字',
    'pending': '等待',
    'waiting': '等待',
    'monospace': '等宽字体',
    'floor': '地板上',
    'Earth Golem': '地傀儡',
    'Earth Freeze': '大地冻结',
    '% chance for earth golems to reflect bullets': '地傀儡反射子弹的几率',
    '% earth golem bullet reflect': '地傀儡子弹反射',
    'crypt': '地下室',
    'second': '第二个',
    'Second Zombie Cage': '第二个僵尸笼',
    'Third Zombie Cage': '第三个僵尸笼',
    'Fourth Zombie Cage': '第四个僵尸笼',
    'Fifth Zombie Cage': '第五个僵尸笼',
    'The first rank gives your zombies the ability to spit plague at enemies beyond normal attack range. Spit attacks do 50% zombie damage and infect the victim with plague. Subsequent ranks will increase the range of spit attacks.': '第一等级使你的僵尸有能力向超过正常攻击范围的敌人喷吐瘟疫。喷吐攻击造成50%的僵尸伤害，并用瘟疫感染目标。后续的等级将增加喷吐攻击的范围。',
    'first': '第一个',
    'points': '点',
    'click': '点击',
    'click dblclick mousedown mouseup mouseover mouseout mousemove mouseenter mouseleave keydown keyup keypress submit focus blur copy cut paste': '点击鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标右键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键，鼠标左键',
    'Energy Charge': '能量狂热',
    'vertices': '顶点',
    'animate': '动画',
    'animation': '动画',
    'STANDALONE': '独立的',
    'short': '短',
    'object': '对象',
    'object ': '对象',
    'multiple': '多个',
    'multiple selected checked disabled readOnly required open': '多个选中的已禁用只读需要打开',
    'multilink': '多链路',
    'Extra Limbs': '额外的肢体',
    'binary': '二进制',
    'binary&&': '二进制',
    'binary!=': '二进制! =',
    'binary!==': '二进制! = =',
    'binary%': '二进制%',
    'binary*': '二进制*',
    'binary/': '二进制/',
    'binary<': '二进制<',
    'binary<=': '二进制< =',
    'binary==': '二进制= =',
    'binary>': '二进制>',
    'binary>=': '二进制> =',
    'binary+': '二元+',
    'binary===': '二元= = =',
    'canvas': '帆布',
    'Anti tank harpies': '反坦克哈比',
    'return ': '返回',
    'returning': '返回',
    'return fn;': '返回fn;',
    'range': '范围',
    'scope': '范围',
    'bulletproof': '防弹',
    'debounce': '防反跳',
    'detach': '分离',
    'assign': '分配',
    'Splitter Combiner': '分配器合路器',
    'Minutes': '分钟',
    'style': '风格',
    'service': '服务',
    'float': '浮动',
    'load': '负载',
    'copy': '复制',
    'isComplete': '赋予isComplete',
    'overlay': '覆盖',
    'The index ': '该指数',
    'change': '改变',
    'Infected Bite': '感染咬',
    'stencil': '钢网',
    'port': '港口',
    'height': '高度',
    'isolate scope definition': '隔离范围定义',
    'chrome': '铬',
    'track': '跟踪',
    'Bigger Fence': '更大的栅栏',
    'More Gigazombies': '更多巨人僵尸',
    'Faster Harpies': '更快的哈比',
    'lighter': '更轻的',
    'A more advanced device that produces 4 parts every 3 seconds': '更先进的设备，每3秒生产4个零件',
    'update': '更新',
    'factory': '工厂',
    'Factory menu now available!': '工厂菜单现在可用!',
    'Anno Domini': '公元',
    'CCW': '公约',
    'attacking': '攻击',
    ' supplied is out of bounds ': '供应是禁区',
    'HOOK DIV': '钩DIV',
    'dog': '狗',
    'Build (': '建造(',
    'Both name and url are required for constructing a resource.': '构造资源需要名称和url。',
    'orphan': '孤儿',
    'Runic Syphon': '符文弯管',
    'ticker': '股票行情自动收录器',
    'Bone Fort': '骨堡',
    'Bone Citadel': '骨城堡',
    'Bone Throne': '骨的宝座',
    'Bone Fortress': '骨的堡垒',
    'Bone Reinforced Tanks': '骨钢筋坦克',
    'Bones: ': '骨骼:',
    'Bone Rate': '骨率',
    'Bone collector capacity: ': '骨头收集者上限:',
    'bones': '骨头',
    ' bones': '骨头',
    ' bones per second': '骨头每秒',
    'fixed': '固定',
    'luminosity': '光度',
    'scale': '规模',
    'Booby trap the area around your graveyard with cruel spikes that infect trespassing humans with the plague.': '你墓地周围的区域布置尖锐的陷阱，可以用瘟疫感染入侵的人类。',
    'VIP': '贵宾',
    'transition': '过渡',
    'Filter': '过滤器',
    'Harpy upgrades now available in the shop!': '哈比升级现在可在商店购买!',
    'function': '函数',
    'function(': '函数(',
    'Defend the Graveyard!': '捍卫墓地!',
    'action': '行动',
    'Milliseconds': '毫秒',
    'and': '和',
    ' and expected ': '和预期',
    'black': '黑色的',
    'bombing': '轰炸',
    'Syphon amount: ': '虹吸数额:',
    'following': '后',
    'Thick Skull': '厚的头骨',
    'BufferResource width or height invalid': '缓冲区资源宽度或高度无效',
    'fantasy': '幻想',
    'Crown of Bones': '皇冠的骨头',
    'A calming golem that restores health to nearby units': '恢复附近单位生命值的镇静傀儡',
    'Recycling is Cool': '回收很酷',
    'callback': '回调',
    'Callback was already called.': '回调已经被调用。',
    'Fire Golem': '火傀儡',
    'currency': '货币',
    'base': '基地',
    'geometry': '几何',
    'geometry error, GPU Instancing is not supported on this device': '几何错误，该设备不支持GPU实例化',
    'inherit': '继承',
    'Speed up the flow of time for 30 seconds': '加速时间流30秒',
    'loaded': '加载',
    'Load timed out.': '加载超时。',
    'Cannot add resources while the loader is running.': '加载程序运行时不能添加资源。',
    'Failed to load element using: ': '加载元素失败，使用:',
    'FALSE': '假',
    'value': '价值',
    'Sharpened Teeth': '尖锐的牙齿',
    'Tough as Nails': '坚决严厉的',
    'The listener must be a function': '监听器必须是一个函数',
    'checked': '检查',
    'lighten': '减轻',
    'Simple Machine': '简单的机器',
    'Build a laboratory to study the effects of plague. This will unlock new upgrades in the shop.': '建立一个实验室来研究鼠疫的影响。这将解锁商店的新升级。',
    'construction': '建设',
    'Construction of ': '建设',
    'Build an additional cage to contain surplus zombies once a town is defeated.': '建造一个额外的笼子在占领城镇后用来携带多余的僵尸',
    'Build a factory to turn creature parts into living entities of destruction': '建造一个工厂，把傀儡零件变成带来毁灭的傀儡',
    'Build a factory to create parts that can be used to construct more powerful beings for your army.': '建造一个工厂来制造零件，可以用来为你的军队建造更强大的傀儡',
    'Build a cage to contain surplus zombies once a town is defeated.': '建造一个笼子来容纳多余的僵尸一旦一个城镇被击败。',
    'Build an outfitter to upgrade the abilities of your harpies.': '建造一个装备商来升级你的哈比的能力。',
    'building': '建筑',
    'Building...': '建筑……',
    'Construction menu now available!': '建筑菜单现在可用!',
    'health': '健康',
    'The zombies retain more of their human agility increasing run speed by 1 for each rank.': '僵尸保留了更多的人类敏捷性，每个等级增加1点的奔跑速度。',
    'Zombie Cost: ': '僵尸成本:',
    'Zombie damage: ': '僵尸伤害:',
    ' zombie speed': '僵尸速度',
    '% chance for zombies to infect their targets': '僵尸感染目标的几率',
    'Zombie Health': '僵尸血量',
    ' zombie health': '僵尸血量',
    'Zombie Health: ': '僵尸血量:',
    'Zombie Cage': '僵尸笼',
    ' zombie energy cost': '僵尸能量成本',
    'Zombie Damage': '僵尸伤害',
    ' zombie damage': '僵尸伤害',
    'Zombie speed: ': '僵尸速度:',
    'Zombie spit distance: ': '僵尸吐距离:',
    '% chance for zombies to explode on death': '僵尸在死亡时爆炸的几率',
    'Zombie maximum health: ': '僵尸最大的血量:',
    'trophies': '奖杯',
    'interaction': '交互',
    'focus': '焦点',
    'angular': '角',
    'script': '脚本',
    'Teach your harpies some new tricks. Once bought this upgrade will make your harpies drop fire bombs on tanks during boss stages.': '教你的哈比一些新把戏。一旦购买了这个升级，你的哈比将在boss阶段向坦克投掷火焰炸弹',
    'end': '结束',
    'end ngIf': '结束ngIf',
    'end ngRepeat': '结束ngRepeat',
    'end ngSwitchWhen': '结束ngSwitchWhen',
    'resolve': '解决',
    'Unlock the ability to automatically purchase items from the shop.': '解锁从商店自动购买物品的能力',
    'Unlock more gigazombies': '解锁更多巨人僵尸',
    'Unlock the ability to automatically start construction of the cheapest available building option.': '解锁能力，自动开始建设最便宜的可用建筑选项',
    'Unlock the Time Warp spell in order to speed up the flow of time.': '解锁时间扭曲法术以加速时间',
    'gopher:': '金花鼠:',
    'progress': '进步',
    'The assault has begun!': '进攻开始了!',
    'The best defense is a good offense? True in the case of Plague Armor which reduces the damage done by infected humans by 2% per rank.': '进攻是最好的防御？是的，瘟疫护甲可以使被瘟疫感染的人类造成的伤害降低2%每等级',
    'disable': '禁用',
    'disabled': '禁用',
    'AngularJS: disabling automatic bootstrap. <script> protocol indicates an extension, document.location.href does not match.': '禁用自动引导。脚本>协议表示一个扩展，document.location。href不匹配。',
    'precision': '精度',
    'precision ': '精度',
    'precision mediump float;': '精密mediump浮动;',
    'pre': '精准医疗',
    'warn': '警告',
    'WARNING: Tried to load AngularJS more than once.': '警告:尝试加载AngularJS不止一次。',
    'Warning: High Military Activity!': '警告:高度军事活动!',
    'Warning: High Police Activity!': '警告:警察活动频繁!',
    'AS IS': '就像',
    'reject': '拒绝',
    'rejected': '拒绝了',
    'absolute': '绝对',
    'start': '开始',
    'accessibility': '可访问性',
    'Possibly unhandled rejection: ': '可能未处理的拒绝:',
    'cancelable': '可取消的',
    'The world can be dragged with the mouse to explore it. Or by using the WASD or arrow keys.': '可以用鼠标拖动世界来探索它。或者使用WASD或箭头键。',
    'available': '可用',
    'pit': '坑',
    'Air Golem': '气傀儡',
    'Controller': '控制器',
    'controller bindings definition': '控制器绑定定义',
    'width': '宽度',
    'loose': '宽松的',
    'Enlarge the fence so a greater area is protected.': '扩大篱笆，使更多的地方受到保护。',
    'Expand the plague workshop into a well equipped laboratory in order to unlock additional plague upgrades.': '扩大瘟疫车间到一个装备良好的实验室，以解锁额外的瘟疫升级。',
    'class': '类',
    'type': '类型',
    'Cold Storage': '冷藏',
    'leave': '离开',
    'tap': '利用',
    'particle': '粒子',
    'face': '脸',
    'link': '链接',
    'amount': '量',
    'null': '零',
    'path': '路径',
    'max': '上限',
    ' max brains': '大脑上限',
    ' max blood': '血液上限',
    'Sold Out': '卖完了',
    'anchor': '锚',
    'none': '没有一个',
    'An industrial press that produces 16 parts every 5 seconds': '一个工业印刷机每5秒生产16个零件',
    'Whenever one of your zombies attacks a human you will collect some blood.': '每当你的僵尸攻击人类，你将收集一些血液。',
    'Additional 20% bones income rate for each rank.': '每级额外增加20%的骨骼收入。',
    'Additional 20% creature parts income rate for each rank.': '每级额外增加20%的生物物品收入。',
    'Additional 20% blood income rate for each rank.': '每级额外增加20%的血液收入。',
    'Each rank reduces the energy cost of summoning a zombie by 1': '每级降低召唤一个僵尸的能量消耗1',
    'Additional 20% zombie health for each rank': '每级增加20%的僵尸生命值',
    'Additional 20% brain storage for each rank.': '每级额外增加20%的大脑存储空间。',
    'Additional 20% brain income rate for each rank.': '每级额外增加20%的大脑收入。',
    'Additional 20% blood storage for each rank.': '每级额外增加20%的血液储备。',
    'Additional 20% zombie damage for each rank': '每级增加20%的僵尸伤害',
    ' per second': '每秒',
    'sealed': '密封',
    'password': '密码',
    'Infuse your runes for free! Each rank gives your Runesmith the ability to infuse 1% of your resource income, without consuming it': '免费注入你的符文!每个等级都能让你的符文获得1%的总资源收益，而不消耗资源',
    'mask': '面具',
    'Seconds': '秒',
    'template': '模板',
    'templates': '模板',
    'blur': '模糊',
    'module': '模块',
    'pattern': '模式',
    'model': '模型',
    'Spell Tower': '魔法塔',
    'Spells now available in the shop!': '魔法现在可以在商店里买到!',
    'default': '默认的',
    'target': '目标',
    'directory': '目录',
    'graveyard': '墓地',
    'Graveyard menu now available!': '墓地菜单现在可用!',
    'Graveyard Health': '墓地的血量',
    'Graveyard health: ': '墓地的血量:',
    'energy': '能源',
    ' energy': '能源',
    ' energy per second': '能源/秒',
    'Energy rate: ': '能源率:',
    'Energy Rush': '能源热潮',
    'Your zombies attacks do +5 damage with each rank of Razor Claws.': '剃刀爪使你的僵尸攻击造成+5伤害每级。',
    'Your zombies attacks do +8 damage with each rank of Killer Instinct.': '杀手本能使你的僵尸攻击造成+8伤害每级。',
    'Your zombies gain +100 health with each rank of Tough as Nails.': '像钉子般坚硬，你的僵尸获得+100的血量每等级',
    'Your zombies gain +2% health with each rank of Big Boned.': '大骨架使你的僵尸获得+2%的血量每等级',
    'Your zombies gain tougher skin and +10 health with each rank.': '更坚韧的皮肤使你的僵尸获得+10的血量每等级。',
    'Your zombies gain +25 health with each rank.': '你的僵尸获得+25点血量每等级',
    'Your zombies gain +2% damage with each rank of Extra Limbs.': '额外的肢体使你的僵尸获得2%的伤害每等级',
    'Your zombies thirst for blood and do +1 damage for each rank of Bloodthirst.': '你的僵尸嗜血，每一级嗜血造成+1伤害',
    'Your zombies are now infected with plague and could infect their victims too. Each rank adds 10% chance to inflict damage over time when a zombie attacks a target.': '你的僵尸现在携带瘟疫，并可能感染他们的受害者。当僵尸攻击目标时，每一等级增加10%的伤害几率',
    'Your zombies bites do +3 damage with each rank of Sharpened Teeth.': '锋利的尖牙使你的僵尸攻击造成+3伤害每等级',
    'Your zombies gain +40 health with each rank of Battle Hardened.': '久经沙场使你的僵尸在获得+40的生命值每等级',
    'Your Soul is Mine!': '你的灵魂属于我!',
    'You have yet to learn this spell': '你还得学这个咒语',
    'You have yet to unlock tank buster': '你还没有解锁坦克克星',
    'You have yet to unlock Unholy Construction': '你还没有解锁邪恶建筑',
    'You have yet to unlock automatic construction': '你还没有解锁自动建造',
    'You have yet to unlock more gigazombies': '你还没有解锁更多的巨人僵尸',
    'You can zoom in and out using your mouse wheel. Pinch to zoom on mobile.': '你可以使用鼠标滚轮放大或缩小。缩放手机。',
    'You can spend these currencies in the shop to purchase upgrades for your zombie horde.': '你可以在商店里使用这些货币为你的僵尸部落购买升级。',
    'Your factory has generated ': '你们工厂已经生产了',
    'Are you sure?': '你确定吗?',
    'Are you sure you want to cancel construction?': '你确定要取消施工吗?',
    'Are you sure you want to reset everything? If you have a cloud save it will also be deleted. Make sure you export your save game first.': '你确定要重置一切吗?如果你有云，保存它也会被删除。确保你首先导出你的保存游戏。',
    'All the brains you harvested have proved fruitful in your experiments. Each rank raises your maximum energy by 5.': '你收获的所有大脑在你的实验中都证明是富有成效的。每级提升你的最大能量5点。',
    'You have unlocked more gigazombies': '你已经解锁了更多的巨人僵尸',
    'You have unlocked tank buster': '你已经解锁了坦克克星',
    'You have unlocked automatic construction': '你已经解锁了自动建造',
    'You have unlocked Unholy Construction': '你已经开启了邪恶建筑',
    'You have learned this spell': '你已经学会了这个咒语',
    'anonymous': '匿名',
    'aviary': '鸟类饲养场',
    'harpy': '哈比',
    'Harpies available for hire in the graveyard menu': '哈比可在墓地菜单中租用',
    ' harpy speed': '哈比速度',
    'Harpy speed: ': '哈比速度:',
    'Harpy Outfitter': '哈比装备',
    ' harpy bombs': '哈比炸弹',
    'Harpy bombs: ': '哈比炸弹:',
    'You have yet to unlock automatic shop purchases': '您还没有解锁自动商店',
    'You have unlocked automatic shop purchases': '您已解锁自动商店',
    'minions': '单位',
    'shooting': '拍摄',
    'exclusion': '排除',
    'batch': '批处理',
    'Batch Converter': '批处理转换',
    'unshift': '平移',
    'screen': '屏幕',
    'other': '其他',
    'else{': '其他{',
    'enable': '启用',
    'auto': '自动',
    'Auto Construction': '自动建筑',
    'Auto Shop': '自动商店',
    'top': '前',
    ' Request was aborted by the user.': '请求被用户中止。',
    ' Request timed out.': '请求超时。',
    'difference': '区别',
    'canceled': '取消了',
    'authority': '权威',
    'Burning zombie speed: ': '被点燃僵尸的速度:',
    'Blazing Speed': '燃烧的速度',
    'Fill your zombies with so much plague they are ready to explode! Each rank adds 10% chance for a zombie to explode into a cloud of plague upon death.': '让你的僵尸充满瘟疫，他们准备爆炸!每一等级增加10%的僵尸死亡后爆炸成瘟疫云的几率。',
    '% chance for human corpses to turn into zombies': '人类尸体变成僵尸的几率',
    'The humans are using torches to set your zombies on fire. Perhaps we can turn the tables on them? Each rank increases the movement and attack speed of burning zombies by 5%': '人类正在用火把点燃你的僵尸。也许我们能扭转局势?每个等级增加燃烧僵尸的移动和攻击速度5%',
    'task callback must be a function': '任务回调必须是一个函数',
    'date': '日期',
    'log': '日志',
    'Provided WebGL context does not have a stencil buffer, masks may not render correctly': '如果WebGL上下文没有模板缓冲区，掩码可能无法正确呈现',
    'sss': '瑞士',
    'ternary?:': '三元吗?',
    'tint': '色彩',
    'hue': '色调',
    'Killer Instinct': '杀手本能',
    'Killing a human or turning them into a zombie will earn you 1 brain.': '杀死一个人类或把他们变成僵尸将获得1个大脑。',
    'delete': '删除',
    'removed': '删除',
    'shop': '商店',
    'context': '上下文',
    'Upgrade your harpies so they can carry more than just one bomb at a time.': '升级你的哈比，这样它们可以一次携带多个炸弹。',
    'Upgrade Level ': '升级水平',
    'life': '生活',
    'Creature Factory': '傀儡工厂',
    'Creatures now available in factory menu!': '傀儡现在可在工厂制造!',
    ' creature limit': '傀儡上限',
    'Creature limit: ': '傀儡上限:',
    'prestige': '声望',
    'prestiged': '声望',
    '% chance for corpse to become zombie': '尸体变成僵尸的几率',
    'failed': '失败的',
    'time': '时间',
    'Time Warp': '时间隧道',
    'timezone': '时区',
    'fulfilled': '实现了',
    ' bone collector capacity': '骨头收集者上限',
    'use': '使用',
    'Using your most powerful blood magic you command the bodies of the dead to rise as your servants! Each rank grants 10% chance that dead humans will turn into zombies.': '使用你最强大的血魔法，你命令死者作为你的仆人复活!每个等级都有10%的几率让死去的人类变成僵尸。',
    'use strict': '使用严格的',
    'Turns out you can use all of your spare blood to store brains and keep them fresh. Each rank increases your maximum brain capacity by 50.': '事实证明，你可以用所有多余的血液来储存大脑并保持它们的新鲜。每升一级，你的大脑最大容量增加50。',
    'Error trying to parse loaded json: ': '试图解析加载的json时出错:',
    'Error trying to parse loaded xml: ': '试图解析加载的xml时出错:',
    'video': '视频',
    'video/': '视频/',
    'View': '视图',
    'is an unexpected token': '是一个意外的标记',
    'Bloodthirst': '嗜血',
    'collected': '收集',
    'collecting': '收集',
    'Infected damage reduction: ': '受感染的伤害减免:',
    'Infected Corpse': '受感染的尸体',
    'dupes': '受骗的人',
    'hunting': '狩猎',
    'Out buffer length is incorrect, got ': '输出缓冲区长度不正确，得到',
    'enter': '输入',
    'input': '输入',
    'inputs': '输入',
    'input select option textarea button form details': '输入选择选项textarea按钮表单细节',
    'Conveyor': '输送机',
    'mouse': '鼠标',
    'mouseover': '鼠标移至',
    'cpws': '数据',
    'data:': '数据:',
    'data:image/svg+xml;base64': '数据:图像/ svg + xml; base64',
    'number': '数量',
    'math': '数学',
    'Water Golem': '水傀儡',
    'level': '等级',
    'death': '死亡',
    'speed': '速度',
    'Energy refills over time. You need 10 energy to spawn a zombie by clicking on the ground.': '随着时间的推移，能量会不断补充。你需要10点能量通过点击地面来产生一个僵尸。',
    'damage': '伤害',
    'The supplied DisplayObject must be a child of the caller': '所提供的DisplayObject必须是调用者的一个子对象',
    'all': '所有',
    'All this brain power has enabled you to devise some superior blood storage methods. Each rank increases your maximum blood by 10%.': '所有这些脑力使你能够设计出一些更好的血液储存方法。每个等级增加你的最大血量10%。',
    'Tank Buster': '坦克破坏',
    'fleeing': '逃离',
    'escaping': '逃离',
    'provider': '提供者',
    'submit': '提交',
    'extract': '提取',
    'Razor Claws': '剃须刀的爪子',
    'Arial': '天线',
    'added': '添加',
    'additions': '添加',
    'dispatch': '调度',
    'debug': '调试',
    'invoke': '调用',
    'resize': '调整',
    'post': '帖子',
    'paused': '停顿了一下',
    'head': '头',
    'Bombs Away': '投弹完毕',
    'projection': '投影',
    'transparent': '透明的',
    'image': '图像',
    'graphics': '图形',
    'Spit it Out': '吐出来',
    ' spit distance': '喷吐的距离',
    'blob:': '团:',
    'push': '推',
    'Twitter': '推特',
    'outside': '外',
    'completed': '完成',
    ' complete!': '完成了!',
    'complete': '完整的',
    'play': '玩',
    'mesh': '网',
    'Perimeter Fence': '围栏',
    'undefined': '未定义的',
    'uncollected': '未收款的',
    'unknown': '未知的',
    'location': '位置',
    'position': '位置',
    'Plague explosions from zombies and harpies will also heal nearby zombies for 10% of the explosion damage with each rank.': '僵尸和哈比的瘟疫爆炸也会给附近僵尸治疗爆炸伤害的10%，每级。',
    'Plague Workshop': '瘟疫车间',
    'Plague Armor': '瘟疫的盔甲',
    'Plague Spikes': '瘟疫峰值',
    'Plague upgrades now available!': '瘟疫升级现在可用!',
    'Plague Laboratory': '瘟疫实验室',
    'Plague heal: ': '瘟疫治疗:',
    'text': '文本',
    'text/css': '文本/ css',
    'document': '文档',
    'file': '文件',
    'file:': '文件:',
    'Literal': '文字',
    'texture': '纹理',
    'Texture Error: frame does not fit inside the base Texture dimensions: ': '纹理错误:框架不适合在基本纹理尺寸:',
    'Why are we wasting so many good brains on this project? Each rank increases your chance to get a brain back from a dead zombie by 10%': '我们为什么要在这个项目上浪费这么多优秀的人才呢?每个等级增加你从一个死僵尸那里得到一个大脑的几率10%',
    'We need more gigazombies! This will unlock the ability for all zombies to be gigazombies. They gain health and damage but the energy cost also increases. This can be toggled in the graveyard.': '我们需要更多的巨人僵尸!这将解锁所有僵尸成为巨人僵尸的能力。他们获得生命和伤害，但是能量消耗也增加了。这可以在墓地中切换。',
    'Bottomless Pit': '无底坑',
    'Invalid input': '无效的输入',
    'Invalid exponent': '无效的指数',
    'relative': '相对',
    'Like Leather': '像皮革的',
    'Hours': '小时',
    'lowercase': '小写字母',
    'protocol': '协议',
    'Unholy Construction': '邪恶的建设',
    'miter': '斜方',
    'new/isolated scope': '新/范围隔离',
    'New spell learned, Earth Freeze!': '新的法术，大地冻结!',
    'New spell learned, Energy Charge!': '新的法术，能量狂热!',
    'New spell learned, Gigazombies!': '新的法术，巨人僵尸!',
    'New upgrades are available in the shop!': '新的升级在商店解锁了!',
    'info': '信息',
    'Sun Mon Tue Wed Thu Fri Sat': '星期日、一、二及四、六',
    'Sunday Monday Tuesday Wednesday Thursday Friday Saturday': '星期日星期一星期二星期三星期四星期五星期六',
    'form': '形式',
    'rotation': '旋转',
    'option': '选项',
    'options': '选项',
    'option value': '选项值',
    'select': '选择',
    'selected': '选择',
    'Learn the Gigazombies spell which will turn some of your zombies into hulking monstrosities with increased health and damage.': '学习Gigazombies的法术，它会把你的一些僵尸变成巨大的怪物，增加生命值和伤害。',
    'Learn the Earth Freeze spell which can freeze all humans in place for a short time.': '学习地球冻结咒，它能在短时间内冻结所有人类。',
    'Learn the Energy Charge spell which can drastically increase your energy rate for a short time.': '学习能量充电法，它可以在短时间内大幅度提高你的能量率。',
    'Learn the art of Unholy Construction in order to build structures that will solidify your foothold on the town.': '学习邪恶建筑的艺术，以建立结构，将巩固你在城镇的立足点。',
    'Learn the Detonate spell which can explode all of your zombies into a cloud of plague. Not exactly sure how useful that will be.': '学习引爆咒，可以爆炸成一个云的瘟疫你所有的僵尸。不确定这有多有用。',
    'sprite': '雪碧',
    'blood': '血',
    'Blood: ': '血:',
    'Blood capacity too low': '血量过低',
    'Blood Rate': '血率',
    'Blood Harvest': '血收获',
    'Blood Storage: ': '血液储存:',
    'Blood Storage': '血液存储',
    'strict': '严格的',
    'color': '颜色',
    'required': '要求',
    'page': '页面',
    'step': '一步',
    'Part Duplicator': '一部分复印机',
    'once': '一次',
    'one': '一个',
    'A golem born from rocks and mud, able to take a lot of punishment and taunt enemies to attack it': '一个从岩石和泥土中诞生的傀儡，能够承受大量的惩罚并嘲讽敌人来攻击它',
    'A simple device that produces 1 part every 2 seconds': '一个简单的装置，每2秒产生一个零件',
    'An astounding contraption that produces 512 parts every 12 seconds': '一个惊人的装置，每12秒产生512个零件',
    'A fireball spewing golem that ignites everything it touches': '一个喷出火球的傀儡点燃它接触到的一切',
    'A fantastic new invention that produces 64 parts every 8 seconds': '一个神奇的新发明，每8秒产生64个零件',
    'A bottomless pit with walls made from creature parts. Drastically increases your capacity to store blood and brains.': '一个无底洞，墙壁由生物的部分组成。大大增加你储存血液和大脑的能力。',
    'A Small Investment': '一个小的投资',
    'One is Never Enough': '一个永远不够',
    'A wondrous machine that produces 192 parts every 10 seconds': '一台每10秒生产192个零件的神奇机器',
    'Day': '一天',
    'unary': '一元',
    'unary!': '一元!',
    'unary+': '一元+',
    'January February March April May June July August September October November December': '一月二月三月四月五月六月七月八月十月十一月十二月',
    'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec': '一月二月三月五月六月七月八月十月十一月十二月',
    'A fast moving golem able to cover large distances and chase targets down': '一种快速移动的傀儡，能够覆盖很远的距离并追捕目标',
    'move': '移动',
    ' already used': '已经使用',
    'Unexpected next character ': '意想不到的下一个字符',
    'overflow': '溢出',
    'Overflow: input needs wider integers to process': '溢出:输入需要处理更大的整数',
    'audio': '音频',
    'Detonate': '引爆',
    'hidden': '隐藏的',
    'app': '应用程序',
    'Craft your earth golems from much harder stone. Each rank gives them 5% chance to reflect bullets back to their source.': '用更坚硬的石头制造你的地傀儡。每个等级给他们5%的机会将子弹反射回他们的源头。',
    'user': '用户',
    'userInfo': '用户信息',
    'Stamp Press': '邮票的新闻',
    'Game Saved to Cloud': '游戏保存到云端',
    'has': '有',
    'polite': '有礼貌的',
    'validity': '有效性',
    'syntax': '语法',
    'preload': '预加载',
    'element': '元素',
    'Primal Reflexes': '原始反射',
    'prototype': '原型',
    'source': '源',
    'Month': '月',
    'running': '运行',
    'Error loading save game': '载入错误保存游戏',
    'For 5 seconds any zombies spawned will be giants with 10x health and attack damage, cost 100 energy': '5秒内所有僵尸的生命值和攻击伤害都将变为10倍，消耗100点能量',
    'Construct a Cursed Graveyard in the town that will automatically spawn zombies when your energy is at its maximum!': '在城镇中建造一个被诅咒的墓地，当你的能量达到最大值时，它将自动产生僵尸!',
    'Before Christ': '在基督之前',
    'Build a protective fence around the graveyard that will reduce damage taken by zombies inside by 50%.': '在墓地周围筑一道防护栏，可以减少里面的僵尸50%的伤害。',
    'Dedicate one tower of your fort to the study of spellcraft. Perhaps you can learn some new spells?': '在你的堡垒中奉献一座塔来学习法术技能。也许你可以学习一些新的咒语?',
    'Construct an aviary on top of your citadel so you can release wicked harpies to bomb the townspeople.': '在你的城堡顶部建造一个鸟舍，这样你就可以释放邪恶的鹰身女妖来轰炸镇民。',
    'Melting brains down in your cauldron to make smoothies can be beneficial for your health. It also increases your energy rate by 0.5 per second for each rank.': '在你的坩埚里融化大脑来制作冰沙对你的健康有益。它也增加你的能量率0.5每秒每等级。',
    'Construct a Crypt in your graveyard. This will give you a nice dark and quiet place to think. The additional space will also allow you to store 50% more blood and brains!': '在你的墓地建造一个墓穴。这会给你一个黑暗而安静的地方来思考。额外的空间也将允许你储存50%以上的血液和大脑!',
    'pause': '暂停',
    'fence': '栅栏',
    'paste': '粘贴',
    'paste cut drop': '粘贴将下降',
    'Battle Hardened': '战斗的',
    'standing': '站',
    'length': '长度',
    'this': '这',
    'These harpies are way too slow! We have to make them faster. Each rank increases harpy speed by 2': '这些鹰身女妖太慢了!我们必须让他们更快。每级增加2点鹰身女妖的速度',
    'shader': '着色器',
    'TRUE': '真正的',
    'normal': '正常的',
    'right': '正确的',
    'directive': '指令',
    'Index ': '指数',
    'pointer': '指针',
    'center': '中心',
    'abort': '中止',
    'Finally! Now that we have a solid construction material we can get to work building better storage for our other resources. Each rank increases blood storage by 2000.': '终于!现在，我们有了一个坚实的建筑材料，我们可以开始建设更好的存储我们的其他资源。每个军衔增加2000点血液储备。',
    'repeat': '重复',
    'reset': '重置',
    'week': '周',
    'host': '主机',
    'Master of Death': '主人的死亡',
    'Master Summoner': '主人的召唤者',
    'main': '主要',
    'register': '注册',
    'catch': '抓',
    'decorator': '装饰',
    'ceil': '装天花板',
    'state': '状态',
    'prepare': '准备',
    'Resource can be set only once': '资源只能设置一次',
    'autocomplete': '自动完成',
    'self': '自我',
    'assertive': '自信的',
    'premultiply': '自左乘',
    'char': '字符',
    'string': '字符串',
    'kerning': '字距调整',
    'alphabetic': '字母',
    'totals': '总数',
    'walking': '走',
    'component': '组件',
    'Maximum brains: ': '最大的大脑:',
    'Maximum energy: ': '最大的能源:',
    ' max energy': '最大能量',
    'Maximum blood: ': '最大血:',
    'maxlength': '最大长度',
    'finally': '最后',
    'minlength': '最小长度',
    'min': '最小值',
    'left': '左',
    'Sitting atop your throne of bones you can finally think clearly. Each rank increases maximum energy by 10.': '坐在你的骨头宝座上，你终于可以清晰地思考了。每级增加10点最大能量。',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
}


//需处理的前缀
var cnPrefix = {
    "Current Rank:": "当前等级:",
    "Purchase": "购买",
    "Infuse": "注入",
    ":": ":",
}

//需处理的后缀
var cnPostfix = {
    ":": ":",
    ": ": ": ",

    "Max blood": "血液上限",
    "Max brains": "大脑上限",
    "Max bones": "骨头上限",
    "Critical Damage": "暴击伤害",
    "Critical Chance": "暴击率",
    "Damage Reflection": "伤害反射",
    "Attack Speed": "攻击速度",
    "Damage Reduction": "伤害抵抗",
    "Health Regen / 5 secs": "生命恢复 / 5秒",
    "max blood": "血液上限",
    "max brains": "大脑上限",
    "max bones": "骨头上限",
    "blood": "血液",
    "brains": "大脑",
    "bones": "骨头",
    "Zombie damage": "僵尸伤害",
    "Zombie health": "僵尸生命",
    "Zombie speed": "僵尸速度",
    "zombie damage": "僵尸伤害",
    "zombie health": "僵尸生命",
    "zombie speed": "僵尸速度",
    "energy per second": "每秒能量恢复",
    "Max energy": "能量上限",
    "max energy": "能量上限",
    "chance to recover brain": "回收大脑几率",
    "chance for corpse to become zombie": "尸体复生为僵尸几率",
    "blood required\n        ": "血液需求",
    "brains required\n        ": "大脑需求",
    "bones required\n        ": "骨头需求",
    " blood)\n        ": " 血液)",
    " brains)\n        ": " 大脑)",
    " bones)\n        ": " 骨头)",


    //排除收录
    "血液上限": "血液上限",
    "大脑上限": "大脑上限",
    "血液": "血液",
    "大脑": "大脑",
    "僵尸伤害": "僵尸伤害",
    "僵尸生命": "僵尸生命",
    "每秒能量恢复": "每秒能量恢复",
    "能量上限": "能量上限",
    "僵尸速度": "僵尸速度",
    "回收大脑几率": "回收大脑几率",
    "尸体复生为僵尸几率": "尸体复生为僵尸几率",
    "血液需求": "血液需求",
    "大脑需求": "大脑需求",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s+$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
	/\{\{.*\}\}/, //{{xxx}}
];
var cnExcludePostfix = [
	/:?\s*\-?\d+(\.\d+)?\s*~\s*\d+(\.\d+)?$/, // : 1.5 ~ 2.5
	/:?\s*\d+\s*\/\s*\d+\s*$/, // : 13 / 14
	/:?\s*\d+(\.\d+)?,\s\+?\d+(\.\d+)?$/, // : 0.1, +1
    /(🎃)?(🌳)?(📖)?:?\s*\(?[+\-]?x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
	/:?\s*\d+%\s*$/, //12%
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new gityxGlobal.Map([

]);
