var res = {
    //arial_ttf: "res/arial.ttf",

    huo_png: "res/huo.png",

    map_00_02_jpg :"res/map_00_02.jpg",
    start1_png : "res/start1.png",
    start2_png : "res/start2.png",
    bg1_jpg : "res/bg1.jpg",
    logo_png: "res/logo.png",

    shadow_png: "res/shadow.png",

    hero1_png:"res/hero1.png",
    hero2_png:"res/hero2.png",
    hero3_png:"res/hero3.png",
    hero4_png:"res/hero4.png",
    hero5_png:"res/hero5.png",
    hero6_png:"res/hero6.png",
    hero7_png:"res/hero7.png",
    hero8_png:"res/hero8.png",
    hero9_png:"res/hero9.png",
    hero10_png:"res/hero10.png",

    sword1_png:"res/sword1.png",
    sword2_png:"res/sword2.png",
    sword3_png:"res/sword3.png",
    sword4_png:"res/sword4.png",
    sword5_png:"res/sword5.png",
    sword6_png:"res/sword6.png",
    sword7_png:"res/sword7.png",
    sword8_png:"res/sword8.png",
    sword9_png:"res/sword9.png",
    sword10_png:"res/sword10.png",

    monster1_1_png: "res/monster1_1.png",
    monster1_2_png: "res/monster1_2.png",
    monster1_3_png: "res/monster1_3.png",
    monster1_4_png: "res/monster1_4.png",
    monster1_5_png: "res/monster1_5.png",
    monster1_6_png: "res/monster1_6.png",
    monster1_7_png: "res/monster1_7.png",
    monster1_8_png: "res/monster1_8.png",
    monster1_9_png: "res/monster1_9.png",
    monster1_10_png: "res/monster1_10.png",

    monster2_1_png: "res/monster2_1.png",
    monster2_2_png: "res/monster2_2.png",
    monster2_3_png: "res/monster2_3.png",
    monster2_4_png: "res/monster2_4.png",
    monster2_5_png: "res/monster2_5.png",
    monster2_6_png: "res/monster2_6.png",
    monster2_7_png: "res/monster2_7.png",
    monster2_8_png: "res/monster2_8.png",
    monster2_9_png: "res/monster2_9.png",
    monster2_10_png: "res/monster2_10.png",

    monster3_1_png: "res/monster3_1.png",
    monster3_2_png: "res/monster3_2.png",
    monster3_3_png: "res/monster3_3.png",
    monster3_4_png: "res/monster3_4.png",
    monster3_5_png: "res/monster3_5.png",
    monster3_6_png: "res/monster3_6.png",
    monster3_7_png: "res/monster3_7.png",
    monster3_8_png: "res/monster3_8.png",
    monster3_9_png: "res/monster3_9.png",
    monster3_10_png: "res/monster3_10.png",

    monster4_1_png: "res/monster4_1.png",
    monster4_2_png: "res/monster4_2.png",
    monster4_3_png: "res/monster4_3.png",
    monster4_4_png: "res/monster4_4.png",
    monster4_5_png: "res/monster4_5.png",
    monster4_6_png: "res/monster4_6.png",
    monster4_7_png: "res/monster4_7.png",
    monster4_8_png: "res/monster4_8.png",
    monster4_9_png: "res/monster4_9.png",
    monster4_10_png: "res/monster4_10.png",
    arrow_png: "res/arrow.png",

    monster5_1_png: "res/monster5_1.png",
    monster5_2_png: "res/monster5_2.png",
    monster5_3_png: "res/monster5_3.png",
    monster5_4_png: "res/monster5_4.png",
    monster5_5_png: "res/monster5_5.png",
    monster5_6_png: "res/monster5_6.png",
    monster5_7_png: "res/monster5_7.png",
    monster5_8_png: "res/monster5_8.png",
    monster5_9_png: "res/monster5_9.png",
    monster5_10_png: "res/monster5_10.png",

    monster6_1_png: "res/monster6_1.png",
    monster6_2_png: "res/monster6_2.png",
    monster6_3_png: "res/monster6_3.png",
    monster6_4_png: "res/monster6_4.png",
    monster6_5_png: "res/monster6_5.png",
    monster6_6_png: "res/monster6_6.png",
    monster6_7_png: "res/monster6_7.png",
    monster6_8_png: "res/monster6_8.png",
    monster6_9_png: "res/monster6_9.png",
    monster6_10_png: "res/monster6_10.png",

    explosion0_png: "res/explosion0.png",
    explosion1_png: "res/explosion1.png",
    explosion2_png: "res/explosion2.png",
    explosion3_png: "res/explosion3.png",
    explosion4_png: "res/explosion4.png",
    explosion5_png: "res/explosion5.png",

    miss_png: "res/miss.png",
    skill_png: "res/skill1.png",
    skill_progress_png: "res/skill_progress1.png",
    popup_r_png: "res/popup_r.png",
    btn_r_png: "res/btn_r.png",
    be_shot_png: "res/be_shot.png",
    warning_wolf_png: "res/warning_wolf.png",
    notice_board_png: "res/notice_board.png",
    eff_dark_png: "res/eff_dark.png",
    guide_png: "res/guide.png",
    xin_1_png: "res/xin_1.png",
    xin_2_png: "res/xin_2.png",
    share_png: "res/share.png",
    btn_1:"res/btn_1.png",
    btn_2:"res/btn_2.png",
    icon58_png:"res/icon.png"
};

var g_resources = [
    //image
    res.huo_png,
    res.map_00_02_jpg,
    res.logo_png,

    res.start1_png,
    res.start2_png,
    res.hero1_png,
    res.hero2_png,
    res.hero3_png,
    res.hero4_png,
    res.hero5_png,
    res.hero6_png,
    res.hero7_png,
    res.hero8_png,
    res.hero9_png,
    res.hero10_png,

    res.sword1_png,
    res.sword2_png,
    res.sword3_png,
    res.sword4_png,
    res.sword5_png,
    res.sword6_png,
    res.sword7_png,
    res.sword8_png,
    res.sword9_png,
    res.sword10_png,


    res.monster1_1_png,
    res.monster1_2_png,
    res.monster1_3_png,
    res.monster1_4_png,
    res.monster1_5_png,
    res.monster1_6_png,
    res.monster1_7_png,
    res.monster1_8_png,
    res.monster1_9_png,
    res.monster1_10_png,

    res.monster2_1_png,
    res.monster2_2_png,
    res.monster2_3_png,
    res.monster2_4_png,
    res.monster2_5_png,
    res.monster2_6_png,
    res.monster2_7_png,
    res.monster2_8_png,
    res.monster2_9_png,
    res.monster2_10_png,

    res.monster3_1_png,
    res.monster3_2_png,
    res.monster3_3_png,
    res.monster3_4_png,
    res.monster3_5_png,
    res.monster3_6_png,
    res.monster3_7_png,
    res.monster3_8_png,
    res.monster3_9_png,
    res.monster3_10_png,

    res.monster4_1_png,
    res.monster4_2_png,
    res.monster4_3_png,
    res.monster4_4_png,
    res.monster4_5_png,
    res.monster4_6_png,
    res.monster4_7_png,
    res.monster4_8_png,
    res.monster4_9_png,
    res.monster4_10_png,

    res.monster5_1_png,
    res.monster5_2_png,
    res.monster5_3_png,
    res.monster5_4_png,
    res.monster5_5_png,
    res.monster5_6_png,
    res.monster5_7_png,
    res.monster5_8_png,
    res.monster5_9_png,
    res.monster5_10_png,

    res.monster6_1_png,
    res.monster6_2_png,
    res.monster6_3_png,
    res.monster6_4_png,
    res.monster6_5_png,
    res.monster6_6_png,
    res.monster6_7_png,
    res.monster6_8_png,
    res.monster6_9_png,
    res.monster6_10_png,

    res.miss_png,
    //res.skill_png,
    //res.skill_progress_png,
    res.popup_r_png,
    res.btn_r_png,
    res.be_shot_png,
    res.warning_wolf_png,
    res.notice_board_png,
    res.eff_dark_png,
    res.share_png,
    res.btn_1,
    res.btn_2,
    res.icon58_png
    //plist

    //fnt

    //tmx

    //bgm

    //effect
];