/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Add to queue': '加入队列',
    'Agriculture': '农业',
    'Ancient Era': '上古时代',
    'Archer': '弓兵',
    'Archery': '箭术',
    'Armies': '军队',
    'Art': '艺术',
    'Artists': '艺人',
    'Attacks & Transfers': '进攻与运输',
    'AI attacks disabled': 'AI不进攻',
    'AI attacks enabled': 'AI会进攻',
    'AI attacks enabled but rare': 'AI会偶尔进攻',
    'AI attacks more frequent': 'AI会频繁进攻',
    'and provided': '并提供',
    'Auto-assign': '自动分配',
    'Available': '解锁',
    'Available for purchase': '允许购买',
    'Barabarian attacks disabled': '土著不进攻',
    'Barabarian attacks enabled': '土著会进攻',
    'Barabarian attacks more frequent': '土著会频繁进攻',
    'Barracks': '兵营',
    'Base': '基地',
    'Battle reports': '战斗报告',
    'Bronze Working': '青铜铸造',
    'Builders': '建造工人',
    'Building nothing': '没有在建造',
    'Buildings': '建筑',
    'Buy those useless items': '购买这些无用的东西',
    'Calendar': '日历',
    'Chest': '箱子',
    'Children': '子项目',
    'Cities & Citizens': '城市和市民',
    'City': '城市',
    'City-state': '城邦',
    'City-State': '城邦',
    'Classical Era': '古典时代',
    'Code of Honor': '荣耀守则',
    'Code of Laws': '法典',
    'Collective Rules': '集团规则',
    'Colonialism': '殖民主义',
    'completly free': '完全免费',
    'Continue': '继续',
    'Credits': '鸣谢',
    'Crop Rotation': '轮作',
    'Cultural Diplomacy': '文化外交',
    'Culture': '文化',
    'Culture & Social Policies': '文化和社会政策',
    'Current': '当前',
    'Date': '日志',
    'Defense': '防御',
    'Daily Bonus': '每日奖励',
    'Despotism': '独裁',
    'Destination': '目的地',
    'Difficulty': '难度',
    'Diplomacy': '外交',
    'Diplomacy & Trade': '外交与贸易',
    'Discipline': '纪律',
    'Dog domestication': '驯化狗',
    'Done': '完成',
    'Exclude': '不包括',
    'Exploration': '探索',
    'Export': '导出',
    'Farmers': '农夫',
    'Food': '食物',
    'Food, Health & Happiness': '食物，健康和幸福度',
    'Freepik': 'Freepik',
    'from': '从',
    'From': '从',
    'Gold': '黄金',
    'Granary': '粮仓',
    'Hardcore': '核心内容',
    'Help': '帮助',
    'Herding': '放牧',
    'Here you will find answers to all of your questions about this Game.': '你可以在这里找到一些对你有帮助的提示',
    'Holy Wars': '圣战',
    'Horseriding': '骑术',
    'However, if you wish to support it, you can still offer a gift !': '当然，如果你赞助本游戏，就可以获得一份礼物！',
    'Icons made by': '图片来源',
    'Idle': '放置',
    'Imperialism': '帝国主义',
    'in every city': '在所有城市',
    'in the Capital': '仅在首都',
    'In the footer of this page, you will see links to different pages related to your current page.': '在这个页面的底部，你可以看到前往不同页面的链接',
    'in this section': '在这个部分',
    'Justice': '正义',
    'Landed Elite': '地主阶级',
    'Landed Elites': '地主阶级',
    'Language': '语言',
    'Literature': '文学',
    'Load an exported save': '导入游戏',
    'Load game': '加载存档',
    'Locked': '未解锁',
    'Longhouse': '长屋',
    'Mark all as read': '全部设为已读',
    'Masonry': '砖石结构',
    'Medieval Era': '中世纪',
    'Merchant Confederacy': '商人联盟',
    'Merchants': '商人',
    'Meritocracy': '精英统治',
    'Militarism': '军国主义',
    'Military buildings cost': '军事建筑消耗',
    'Military Tradition': '军事制度',
    'Mining': '采矿',
    'Miscelanous': '杂项',
    'Monarchy': '君主制',
    'Monument': '纪念碑',
    'Navigation': '导航',
    'New game': '新游戏',
    'No malus for Barbarians': '土著不会沉迷苹果酒而忘记发展',
    'Normal': '普通',
    'Notifications': '通知',
    'Oligarchy': '寡头政治',
    'Options': '功能',
    'Organized Religion': '宗教组织',
    'Origin': '起源',
    'Pacifism': '和平主义',
    'Patriotism': '爱国主义',
    'Patronage': '赞助',
    'Peaceful': '和平',
    'Philantropy': '慈善活动',
    'Philosophy': '哲学',
    'Piety': '虔诚',
    'Population': '人口',
    'Pottery': '制陶',
    'Prehistoric Era': '史前时代',
    'Prevent growth': '抑制增长',
    'Priority': '优先',
    'Production': '生产',
    'Production & Buildings': '生产和建筑',
    'Professional Army': '专业军队',
    'Purchased': '购买',
    'Rationalism': '理性主义',
    'Recruiting nothing': '没有在招募',
    'Reduce troop maintenance in the Capital by half': '首都的部队维护费用减半',
    'Reformation': '改革',
    'Related': '相关的',
    'Monument': '纪念碑',
    'Navigation': '导航',
    '': '',
    'Administration': '行政部门',
    'Allow recruitment of melee & ranged units': '允许招募近战和远程单位',
    'Aristocracy': '贵族政治',
    'Background by': '背景来源',
    'Background vector created by freepik - www.freepik.com': '背景由freepik提供 - www.freepik.com',
    'Citizens': '市民',
    'Cividlization II': '文明放置2',
    'Happiness': '幸福度',
    'Increase': '增加',
    'kept after growth': '人口增长后保留',
    'limi': '限制',
    'Number of Cities': '城市数量',
    'Ranged units attack before all other troops': '远程单位会在其他单位攻击前先攻击',
    'Relax': '放松',
    'Religion': '宗教',
    'Religious Laws': '宗教律法',
    'Remaining Time': '剩余时间',
    'Required': '需要',
    'Save': '保存',
    'Scholasticism': '经院哲学',
    'Science': '科学',
    'Scientific State': '科教兴国',
    'Scout': '侦察兵',
    'Scouts are used to explore the world': '侦察兵可以用于探索地图',
    'Secularism': '世俗主义',
    'Select building': '选择建筑',
    'Show on map': '在地图上显示',
    'Shrine': '圣地',
    'Social Policies': '社会政策',
    'Sovereignty': '主权',
    'Speed': '速度',
    'Spirituality': '精神',
    'Spoiler alert !': '剧透警告！',
    'State': '国家',
    'Status': '国家',
    'Strong priority': '强优先级',
    'Support': '赞助',
    'Support & Credits': '赞助与鸣谢',
    'Tanning': '制革',
    'Theocracy': '神权政治',
    'There is nothing we can build in this city': '这座城市没有可以建造的建筑',
    'This game is': '这个游戏是',
    'To': '想要',
    'Tools': '工具',
    'Total': '总计',
    'Total gains': '获得总计',
    'Total production': '生产总计',
    'Trade': '交易',
    'Traditionalism': '传统主义',
    'Troop maintenance': '部队维护费',
    'Troop unitary maintenance cost': '单个部队维护费',
    'Unavailable': '未解锁',
    'Unlock': '解锁',
    'Version: 1.': 'Version: 1.',
    'War & Troops': '战争与工具',
    'Warrior': '勇士',
    'Welcome to the Cividlization II Help pages !': '欢迎来到文明放置2的帮助页面！',
    'Wheel': '车轮',
    '': '',
    'Ancients\' Wisdom': '上古智慧',
    'Cancel': '取消',
    'Collective Rule': '集体规则',
    'Daily Bonus !': '每日奖励！',
    'Delete': '删除',
    'Education': '教育',
    'Empire': '帝国',
    'Era: Prehistoric Era': '时代：史前时代',
    'Governor': '统治者',
    'Load': '载入',
    'Paste your exported save here and click on the load button': '在这里粘贴你导出的存档并点击导入',
    'Recruiting': '正在招募',
    'Republic': '共和国',
    'Scholars': '学者',
    'Scouting': '正在探索',
    'Send scout (auto': '派遣侦察兵（自动',
    'Town Hall': '市政厅',
    'Treasury': '财政部门',
    'Use a bonus': '使用奖励',
    'While the help sections are a great way to learn more about the mechanics of this game, it might reveal some features that are locked in the early stage of the game.': '虽然帮助可以让你了解这个游戏，但也会剧透一些你未解锁的功能',
    'Wisdom of the Ancients': '古人的智慧',
    'without ads': '没有广告',
    'World': '世界',
    'World Map': '世界地图',
    'Writing': '写作',
    'You can find the meaning of all the icons used in this game': '你可以在这里找到所有图标的含义',
    'and': '和',
    'provides': '上一页',
    'A detailed list of buildings is available in': '可获得的建筑列表',
    'A detailed list of policies is available in': '可获得的政策列表',
    'A list of icons used in this game': '所有图标表示的含义',
    'A new citizen will be available every time you reach the required amount of food for growth. This amount depends on the city current population': '你的食物达到上限后可以获得一个人口，食物上限取决于你这座城市的人口数量',
    'A trade route will automatically be erased if the civilizations are at war or if one of the 2 cities changes ownership.': '如果贸易双方其中一座城市易主，或者双方的所属国家宣战，贸易将立即中断',
    'affects almost everything from food to culture.': '几乎影响从食物到文化的一切',
    'All citizens provide a small contribution to the': '所有市民都会少量加成',
    'Allow recruitment of mounted units': '允许招募骑兵',
    'Allow recruitment of siege units': '允许招募攻城单位',
    'allow you to reveal the details of a city: troops, buildings, treasury etc...': '允许你观察一个城市的情报：部队，建筑，资源等等',
    'Also, do not forget that barbarians are weaker than other civilizations.': '另外，不要忘记土著比其他文明弱得多',
    'Also, keep in mind that troops require': '另外，别忘了你解锁了什么军队',
    'An effective way to gain gold is by raiding other cities. If you clear an enemy city without bringing a governor, your troops will pillage it and bring the gold back in their city of origin.': '一个有效的赚钱手段是去劫掠其它城市，如果你不带总督出征，军队就不会占领城市而是劫掠一番就走',
    'and can be increased in several ways, including': '也能通过多种方式增加，包括',
    'Aqueduct': '水渠',
    'are specialized in': '专门用于',
    'are used to explore the world. Discovering the world is very important since it allows you to discover other civilizations, or to discover cities to pillage or to conquer.': '用来探索世界，这是非常重要的，你可以找到其它城市和文明来探索和征服',
    'Armory': '军械库',
    'artists': '艺术家',
    'Assur': '亚述城',
    'Assyrians': '亚述',
    'Assyrians\n': '亚述\n',
    'Athens': '雅典',
    'Attack': '攻击',
    'Attacking': '正在攻击',
    'auto-allocation option to prevent the algorithm to allocate other type of population (except from Farmers & Merchants that will keep your city running.': '自动分配选项会影响你其它资源的产出（农民和商人除外，他们要维持你的城市正常运转',
    'Auto-assign will always make sure that': '自动分配将尽可能的保证这一点',
    'auto-assignment of your citizens': '你的市民自动分配工作',
    'Aztecs': '阿兹特克',
    'Bank': '银行',
    'Barb. vil.': '土著村庄',
    'Barbarians': '土著',
    'Barbarians will behave differently from other civilizations. The only way to interact with them is on the battlefield.': '土著和其它文明不同，你只能在战场上和他们交流',
    'Beijing': '北京',
    'builders': '建筑工人',
    'Building': '建筑',
    'Buildings List': '建筑列表',
    'Buildings provide great bonuses for your cities and might even be required to recruit troops.': '建筑将对你的城市有巨大加成，并且可以解锁一些新的部队',
    'but you will gain some divine': '但你将得到一些神圣的',
    'Capacity': '容量',
    'Capital': '首都',
    'caravan': '大篷车',
    'Caravan': '大篷车',
    'Caravan cost': '大篷车消耗',
    'Caravans': '大篷车',
    'Castle': '城堡',
    'Catapult': '投石机',
    'catapult': '投石机',
    'Chinese': '中国',
    'Chinese\n': '中国\n',
    'Choose wisely, you will not be able to change your deity before you reincarnate !': '请谨慎地选择，在转生之前你将无法改变你的神',
    'Circus': '马戏团',
    'Cities': '城市',
    'civilizations': '文明',
    'Civilizations': '文明',
    'Coatlicue': '大地之母',
    'Common': '常见',
    'Consulate': '领事馆',
    'Copper Mine': '铜矿',
    'cost of governors will increase with the number of cities you own and the number of governor you currently have.': '总督的价格将随着你拥有的总督数和城市数总和上升而上升',
    'culture': '文化',
    'Culture production': '文化产出',
    'Cusco': '库斯科',
    'Declare war !': '宣战！',
    'Default priority will still allocate other types of citizens. You can check the': '默认优先级仍将自动分配其它职业的市民，你可以检查',
    'Deities': '神',
    'deity': '神',
    'Deity': '神',
    'Delhi': '德里',
    'depending of your devotion in this life.': '取决于你这一轮的信仰',
    'diplomacy': '外交',
    'Each civilization is different and they will behave differently. They will attack you if they consider you weak enough.': '每个文明发展方向都不相同，如果他们认为你很弱就会攻击你',
    'Each deity will grant you favors once you decide to': '当你信仰一个神，它就会给你一些恩惠',
    'Effect': '效果',
    'Egyptians': '埃及',
    'Egyptians\n': '埃及\n',
    'Embassy': '大使馆',
    'Empire': '帝国',
    'Epic': '史诗',
    'everything': '所有',
    'Except in a special situation, you do not want to reach that limit, all the gold gained after that will be lost.': '除非在特殊情况下，否则达到上限不是个好主意，超出上限的黄金将无法获得',
    'faith': '信仰',
    'Faith': '信仰',
    'favor': '神恩',
    'Favor': '神恩',
    'Favor allows you to gain special': '神恩允许你获得一些特别的东西',
    'first, then send it to another city.': '，然后把它们发送到其它城市',
    'food': '食物',
    'Food production': '食物产量',
    'For a succesful war, or for a succesful defense, you will need to recruit': '在一场成功的战争之后，你可能会需要招募',
    'Friendly': '友善',
    'Furnace': '熔炉',
    'Gardens': '花园',
    'Gifts include': '礼物包括',
    'gold': '黄金',
    'Gold Capacity': '黄金上限',
    'Gold cost': '黄金消耗',
    'Gold Mine': '金矿',
    'Gold production': '黄金产量',
    'governor': '总督',
    'Governor': '总督',
    'Governor cost': '总督消耗',
    'Governors': '总督',
    'Governors are used to capture a city': '总督用于占领城市',
    'Greeks': '希腊',
    'Greeks\n': '希腊\n',
    'Guarded': '警惕',
    'happiness': '幸福度',
    'have a carry capacity which means you will not be able to pilllage a lot if you don\'t bring enough troops': '部队有运载上限，你如果不携带足够的运载单位将无法带回足够的战利品',
    'Health': '健康',
    'Here is a list of all buildings available in this game': '这个列表显示了所有可建造的建筑物',
    'Here is a list of all military troops available in this game': '这个列表显示了所有可招募的军队',
    'Here is a list of all policies available in this game': '这个列表显示了所有可用的政策',
    'Here is the complete list of existing civilizations at the beginning of a game': '这个列表显示了你这次游戏出现的所有文明',
    'Here you will find the help sections that wouldn\'t fit anywhere else': '这里你能找到不适合放在其他标签页的帮助',
    'Horseman': '骑兵',
    'horseman': '骑兵',
    'Horus': '荷鲁斯',
    'Hospital': '医院',
    'Hunter-gatherers': '采猎者',
    'hunter-gatherers or farmers': '采猎者或者农夫',
    'Icons': '图标',
    'Idle citizens don\'t produce only what is needed to keep them alive. It is the default role of new citizens': '无业的市民只提供自身生存所需的资源，这是所有新市民的默认工作',
    'If you choose': '如果你选择',
    'If you want to conquer a city, you will need to bring a': '如果你想占领一个城市，你需要带一个',
    'Incans': '印加',
    'Incans\n': '印加\n',
    'Increase recruitment speed by': '加速招募时间',
    'Indians\n': '印度\n',
    'Indians': '印度',
    'industrial': '工业',
    'Industrial': '工业',
    'industrial production': '工业产量',
    'Industrial production': '工业产量',
    'is essential to an healthy empire. Without it, you will not be able to produce anything and your cities might even revolt.': '对健康的帝国来说必不可少，没有它你将无法生产任何东西，甚至可能会发生叛乱',
    'is essential to the growth of your cities.': '对你的城市发展来说必不可少',
    'is essential to your empire.': '对你的帝国来说必不可少',
    'is required to acquire new social policies.': '允许你点亮一个新的社会政策',
    'is required to acquire new technologies.': '允许你点亮一个新的技术',
    'is required to create a': '允许你创建',
    'is the most important resource in this game. Without it, your cities will not grow and you will not be able to produce anything else.': '是这个游戏最重要的资源，没有它你的城市将停止发展且不能产出任何资源',
    'is the way to construct buildings in your cities.': '是你建造建筑物的途径',
    'is vital to sustain the growth of your cities.': '对你的城市发展非常重要',
    'It is also very important to be able to defend your cities. While you will never be attacked during the Prehistoric Era, barbarians and other civilizations will not hesitate to attack you if you appear weak.': '配置足够的驻守部队也非常重要，虽然在史前时代不会被攻击，但除此之外如果你显得软弱，其它文明和土著就会来攻击你',
    'Knight': '骑士',
    'knight': '骑士',
    'Knights cost': '骑士消耗',
    'Lancier': '枪兵',
    'lancier': '枪兵',
    'Library': '图书馆',
    'Longbowman': '长弓手',
    'Longswordsman': '长剑士',
    'longbowman': '长弓手',
    'longswordsman': '长剑士',
    'Make sure to use it at the right time! For ex. do not use a gold gift if you treasury is full !': '确保你正确地使用他们！比如不要在满黄金的时候使用黄金礼物！',
    'Market': '市场',
    'merchants': '商人',
    'Military': '军事',
    'Military Academy': '军事学院',
    'Academy': '学院',
    'Military units cost': '军队消耗',
    'Mill': '磨坊',
    'Mint': '铸币厂',
    'Monastery': '寺院',
    'Name': '名字',
    'Neutral': '中立',
    'Nidaros': '特隆赫姆',
    'Nothing': '没有',
    'Odin': '奥丁',
    'Once you discover': '一旦你发现',
    'Once you discovered Religion, you will be able to choose a': '一旦你发现宗教，你就可以选择',
    'Once your city grow, all food will be consumed in the process but you there is a few buildings that allow to keep a portion of it.': '一旦你的城市人口增加，食物就会被消耗，有部分建筑可以保留一些食物',
    'Only available in Capital City': '只能在首都',
    'Opera': '歌剧院',
    'option. your city will still grow but just so that your people don\'t die of starvation.': '选项，你的城市将继续发展但食物只保证不会饿死',
    'or': '或',
    'or offer gifts.': '或获得一个礼物',
    'or powers but they do have access to': '或力量，但他们必须可以这么做',
    'or troops': '或部队',
    'Palace': '宫殿',
    'Parent': '上一页',
    'Peace': '和平',
    'Persepolis': '波斯波利斯',
    'Persians': '波斯',
    'Persians\n': '波斯\n',
    'Pikeman': '长矛兵',
    'pikeman': '长矛兵',
    'Player / City': '玩家 / 城市',
    'Policies': '政策',
    'Policy': '政策',
    'powers': '力量',
    'Powers': '力量',
    'priests': '牧师',
    'Priests': '牧师',
    'produced, the more': '生产，越多',
    'production': '产量',
    'Production / Industry': '产量 / 工业',
    'production is impacted by': '产量受到',
    'production is provided by': '产量由',
    'production is provided by all of your citizens in a small amount, but much more efficiently by': '产量由市民提供一小部分，另一部分由',
    'progress of your civilization.': '你的文明进度',
    'Ranged attack': '范围攻击',
    'Ranged?': '范围？',
    'Rare': '少见',
    'Recruitment': '招募',
    'recruitment speed': '招募速度',
    'Reduce discontent due to distance from capital by half': '减半基于首都距离的负面效果',
    'Reduce troop maintenance by half': '减半部队维护费用',
    'Reduce troop maintenance in this city by half': '减半这座城市的部队维护费用',
    'reincarnate': '转生',
    'Reincarnate': '转生',
    'Reincarnation': '转生',
    'Reincarnation is the way to get a better start by learning from your mistakes and get some new powers.': '转生可以使你获得一些新的力量，并吸取上次的经验发展的更好',
    'Require to recruit': '允许招募',
    'Romans': '罗马',
    'Romans\n': '罗马\n',
    'Rome': '罗马',
    'Scholars': '学者',
    'science': '科学',
    'Science production': '科学产量',
    'scientific': '科学的',
    'scientists': '科学家',
    'Scientists': '科学家',
    'Scouting': '正在探索',
    'Scouts': '侦察兵',
    'Shiva': '湿婆',
    'Siege attack': '攻城',
    'Siege Factory': '攻城武器工厂',
    'Siege?': '攻城？',
    'Social Policies provide great bonuses for your Empire.': '社会政策对你的帝国提供大量加成',
    'Some cities have bonuses which make them more productive in a certain domain': '有些城市在某些领域有额外加成',
    'Some groups are exclusing. Be careful before choosing one !': '有些选项是互斥的，选择之前要注意！',
    'Spies': '间谍',
    'Spying': '间谍活动',
    'Stables': '马厩',
    'Starting relation': '初始关系',
    'Stats': '国家',
    'strong': '强大',
    'Success of the operation will depend on the amount of spies you bring and the amount of spies present in the spied city. It does not depend on the amount of military troops.': '行动的成功率取决于你的间谍数量，与军队数量无关',
    'Swordsman': '剑士',
    'swordsman': '剑士',
    'Technologies are grouped in Eras that can only be visible right before you can access it.': '科技被分割成数个时代，你只能在抵达对应的时代之后才能看到那些科技',
    'Technologies are required to unlock buildings, troops, social policies and many more.': '科技可以解锁建筑、部队、社会政策等等',
    'Temple': '寺庙',
    'The': '这个',
    'The more': '更多',
    'Theatre': '剧场',
    'Thebes': '底比斯',
    'There are 4 deities in this game': '这个游戏有四个神',
    'There are 4 eras available in this game so far: Prehistoric, Ancient, Classical and Medieval Eras': '这个游戏有四个时代，史前，上古，古典和中世纪',
    'There is 3 level of gift': '礼物有三个等级',
    'There is a few ways to increase your troops attacking power, including': '有少数手段可以提高你部队的攻击力，包括',
    'There is a limited amount of trade routes allowed.': '贸易路线有上限',
    'There is a maximum number of trade routes allowed by civilization. This maximum can be increased with science or policies.': '每个文明有贸易上限，这个上限可以靠科技和政策提高',
    'There is also a few special units who are not made to fight': '有部分特殊单位不是用来战斗的',
    'Theres is different type of citizens which all contribute to your empire in a specific way': '不同职业的市民以不同的方式对你的帝国做贡献',
    'They also have a penality of 20% while attacking ot defending': '进攻和防御时也有20%的惩罚',
    'They are constantly at war with everyone, they do not have access to': '他们经常和所有人打仗，他们不能',
    'They are divided in 6 groups: Traditionalism, Imperialism, Piety, Rationalism, Pacifism and Militarism.': '他们分为六类，传统主义，帝国主义，虔诚，理性主义，和平主义和军国主义',
    'They will recruit troops, attack, take cities, create trade routes, select special powers, etc...': '他们会招募军队，进攻，占领城市，创造贸易路线，选择政策等等',
    'this help section': '这个帮助标签',
    'This is a list of all icons used in this game.': '这是这个游戏使用的所有图标',
    'To be able to recruit those, you usually have to construct the necessary building.': '想要招募这些单位，你通常需要对应的建筑',
    'To create a': '创建一个',
    'To ensure a great afterlife of course !': '当然是为了保证来世更强大！',
    'To improve relations with one civilization, you can create': '要改善一个文明的关系，你可以创建',
    'to maintain so be careful that your economy is strong enough to sustain your army!': '创建强大的军队时注意经济是否负担得起！',
    'to the city of origin and a smaller gain for the city of destination. It also improve the diplomatic relations with between the 2 civilizations.': '对目标城市也有少量产量加成，同时也会改善两个文明之间的关系',
    'To use a caravan, you need to click on the city where the caravan is located in the world panel.': '你需要在地图上点击你拥有大篷车的城市来使用它',
    'To use a gift, you need to select it in the top menu of the City Screen.': '礼物要在城市面板上方使用',
    'To use it, you need to click on the city where the scout is located in the world panel.': '你需要在地图上点击你拥有侦察兵的城市使用它',
    'To use it, you need to click on the city you want to spy in the world panel.': '你需要在地图上点击你想要进行间谍活动的城市使用它',
    'Town Hall': '市政厅',
    'trade route': '贸易路线',
    'Trade Route': '贸易路线',
    'trade routes': '贸易路线',
    'Trade routes': '贸易路线',
    'Trade Routes': '贸易路线',
    'Treasury': '财政部门',
    'Trebuchet': '投石机',
    'trebuchet': '投石机',
    'Tribunal': '裁判所',
    'Ulundi': '乌伦迪',
    'University': '大学',
    'Vikings': '维京',
    'Vikings\n': '维京\n',
    'Walls': '城墙',
    'War can be an essential part of your game or not. It depends on how you like to play.': '战争可以是你游戏的重要组成部分也可以不是，取决于你怎么玩这个游戏',
    'Well': '水井',
    'archer': '弓手',
    'Armie': '陆军',
    'Artist': '艺术家',
    'Back to list': '返回列表',
    'Barbarians\n': '土著\n',
    'Barrack': '兵营',
    'Battle of': '战斗在',
    'Battle report': '战斗报告',
    'Builder': '建筑工人',
    ' Tradition': '传统',
    'Aztecs\n': '阿兹特克\n',
    'Construction': '建造',
    'Defeat': '击败',
    'Details': '详情',
    'Drama': '戏剧',
    'Iron Working': '铁器',
    'buildings cost': '建筑花费',
    'Persepolis': '波斯波利斯',
    'Tradition': '传统',
    'Zulus': '祖鲁',
    'Zulus\n': '祖鲁\n',
    '': '',
    'Attack increased for each social policy owned.': '每个社会政策都使你攻击上升',
    'Bliss': '极乐',
    'Clairvoyance': '洞察',
    'created a trade route between': '创建了一条商路在',
    'Eye of Horus': '荷鲁斯之眼',
    'Feathered Serpent': '羽蛇神',
    'Gateway to Eternity': '永恒之门',
    'increased.': '增加',
    'Mathematics': '数学',
    'Max number of trade routes increased.': '最大贸易路线增加',
    'Milling': '研磨',
    'Next level': '下一等级',
    'Optics': '光学',
    'Ouroboros': '衔尾蛇',
    'production increased for each building owned.': '基于已有建筑数的额外产量加成',
    'production increased for each city owned.': '基于已有城市数的额外产量加成',
    'production increased for each tech discovered.': '基于已研究科技数的额外产量加成',
    'production increased for each trade route.': '基于已有贸易路线数的额外产量加成',
    'production increased.': '产量加成',
    'Stone Skin': '石肤',
    'Third Eye': '第三只眼',
    'Valhalla': '瓦尔哈拉',
    'Workshop': '工坊',
    'Coatlicue is a powerful goddess of the Aztec mythology. The creator and destroyer of world, the mother of gods and mortals, she is said to have given birth to the Moon and the stars.': '大地之母是阿兹特克神话里的一位强大的神明，是世界的创造者与毁灭者，是所有神明和人类的母亲，据说星星和月亮也是它创造的',
    'Copper mine': '铜矿',
    'Cultural ': '文化',
    'Deity Selection': '选择神',
    'Every': '每个',
    'for every citizen born (based on Feathered Serpent level': '每个市民出生（基于羽蛇神等级',
    'for every city taken (based on Valhalla level': '每个城市占领（基于瓦尔哈拉等级',
    'for every troop killed': '每次杀死一个部队',
    'gained after treasury is full is converted to': '当金币被填满时',
    'Horus...': '荷鲁斯...',
    'Odin is a supreme God of Death, healing, knowledge and poetry.': '奥丁是一个代表死亡、治疗、知识和诗歌的至高神明',
    'production by': '产量基于',
    'Shiva is the form of Brahma, the creator of world and the infinite. The God of Yogis, destroyer of world, he holds the word ‘destruction’ in a positive sense, as destruction of ego, attachments and old habits.': '湿婆是梵天的形体，是无限的化身，是世界的创造者，瑜伽之神，世界的毁灭者。它代表的毁灭具有积极意义，通常指向旧习俗、过去的自己和依恋',
    'Victory': '胜利',
    'Horus is "The One Far Above", protector of the Pharaoh. Originally the Sky God, he is also known as War God, Hunters God, God of Kingship and others.': '荷鲁斯是“至高神”，法老的守护者，原初的天神，同时也是战争之神，狩猎之神，王权之神等等',
    '(based on Eye of Horus level': '（基于荷鲁斯之眼的等级',
    '(based on science production and Third eye level': '（基于科学产量和第三只眼的等级',
    '': '',
    '': '',
    "Barbarians attacks disabled" : '土著不会攻击',
    "Barbarians attacks enabled" : '土著会攻击',
    "Barbarians attacks more frequent" : '土著会频繁攻击',
    "Big bonuses for AI" : 'AI有巨大加成',
    "Big maluses for barbarians" : '土著会沉迷苹果酒',
    "Moderate bonuses for AI" : 'AI获得一定加成',
    "Moderate maluses for barbarians" : '土著会饮用苹果酒',
    "No bonuses for AI" : 'AI无加成',
    "No malus for Barbarians (except science" : '土著全力发展（科学除外）',
    "Small bonuses for AI" : 'AI获得小幅度加成',
    "Start" : '开始',
    "Hunters-Gatherers" : '采猎者',
    "It will not cover every feature of this game, you will need to refer to the help section to get more information." : '教程并未包含这游戏的所有内容,你可以参考帮助页面来获取更多的帮助',
    "Next" : '下一步',
    "No bonuses for AI" : 'AI没有额外加成',
    "Nothing selected" : '没有选择任何东西',
    "Skip" : '跳过',
    "This is a short tutorial to help you get started with this game." : '进行一个简短的教程来帮助你开始游戏',
    "Welcome to Cividlization II !" : '欢迎来到文明放置2',
    "allows you to pause the game." : '你可以暂停游戏',
    "allows you to save your game locally. The game will save every 10s so you don't really have to actively save. You can also export your save to use it on another computer or if you play in private mode." : '你可以保存游戏到本地,并且此游戏每10秒钟自动保存,你也可以导出你的游戏存档到别的电脑或使用离线模式进行游戏',
    "allows you to switch between full screen and windowed." : '你可以选择全屏或者窗口化',
    "Next to your population is the average health in your empire. Be careful not to let it go too low or disease will strike." : '人口旁边的是帝国人民的平均健康水平,请不要让其过低,否则会导致市民生病',
    "Previous" : '上一个',
    "represents the average happiness of your people. Happy citizens are more efficient so keep it up!" : '代表人民的平均幸福,幸福的公民会更有效率',
    "represents the total population of your empire. The more population you have, the more you will be able to produce." : '代表了你帝国的总人口,人口越多,劳力越多',
    "represents your science production. you can see that you are not researching anything at the moment. Try to keep it active as much as possible or you will be left behind!" : '代表了你的科学产出,你可以看到你目前不在研究任何东西,请尝试尽可能的研究,否则你将被AI远远抛下',
    "There will be more stuff in it when you will progress in the game." : '随着游戏的进行你会解锁更多内容',
    "There's already a few interesting information to look at" :'这里已经有了一些有趣的信息',
    "This is the topbar where you can see how your empire is going." : '这是顶部栏,你可以查看你帝国的发展状况',
    "allows you to check all your previous notifications that appeared on screen. You will be notified every time an interesting event happens" : '允许你阅读屏幕上所有曾经显示过的通知。 每当发生有趣的事件时，你都会收到通知',
    "is a very important section since" : '因为这是一个非常重要的部分',
    "is the current screen. It allows you to manage your cities which is the core of your empire" : '是这个界面,它可以让你管理自己帝国的核心城市',
    "is where you will be able to select a science to work on. You can see a small icon" : '在这里你可以选择要研究的科学,你可以看到一个小图标',
    "there will not be any other tutorial" : '没有其他教程',
    "There's not much at the moment but there will be more options in it when you will progress in the game" : '目前没有多少东西,但是随着你的游戏进行,会有更多的选项',
    "This game is completly free but if you like it, you can support the dev there !" : '这款游戏是完全免费的,但是如果你喜欢本游戏,你可以支持开发人员',
    "This is the main menu that will help you access the different screens you need to manage your empire." : '这是主要菜单,你可以通过左侧的各种标签页来帮助你管理你的帝国',
    "which means that your attention is required. In this case it means that there is no science selected and that you should choose one." : '这意味着你需要注意。 在这种情况下，这意味着没有选择科学，你应该尽快选择其中一门。',
    ". It allows you to find all the information you need to play this game." : '.你可以在这里找到玩此游戏所需的所有信息',
    "And now the central part of this screen shows your citizens and what they are doing. There are not a lot of roles at the moment but you will unlock others when you will progress." : '现在，该屏幕的中心部分显示了你的公民及其工作。 目前工作种类不多，但是随着游戏进行将解锁其他工作。',
    "And this is the City Screen where you will be able to manage your cities" : '这是城市页面，你可以在其中管理城市',
    "Let's see what we have in the menu on the left part of this screen" : '让我们看看该屏幕左侧菜单中的内容',
    "represents the food. If you want you city to grow, you will need to meet the requirements for food." : '代表食物。 如果你希望城市发展，则需要填满食物上限，这样就可以获得新的人口',
    "represents the gold in this city's treasury. You will need it for a lot of things that you will discover later in this game. There is a maximum amount that you can hold." : "代表这座城市里的黄金数量，在随后的游戏中很多东西都需要用到它们，它是有储存上限的",
    "The autoassign option allows you to let the game allocate citizens automatically. You will find more information about it in the Help section" : "自动分配选项使你可以让游戏自动分配公民。 你可以在帮助中找到有关此选项的更多信息。",
    "They have the same meaning but at the city level." : '它们具有相同的含义，除了在城市等级',
    "You already know those icons" : "你已经知道那些图标",
    "You can find more information about the roles in the help menu." : '你可以在帮助菜单中找到有关职业的更多信息',
    "Alright, now you are ready to start. Just click on Start and watch your food accumulate, your city grow and your empire prosper... or fall appart" : '好了，现在你可以开始了。只需单击开始，然后观察你的食物积聚，你的城市成长，你的帝国繁荣……或沦陷',
    "Don't forget to look at the help pages if you need any help !": '如果你需要任何帮助，请不要忘记查看帮助页面！',
    "Start !" : '开始 !',
    'You can also ask the algorithm to prevent growth by checking the': '你还可以抑制人口增长，通过',
    'You can either allocate your population to specific roles or let the game do it for you by checking the auto-assign option.': '你可以手动将人口分配给特定职业，也可以通过选中自动分配选项让游戏为你完成。',
    'You can set priorities for each type of production.': '你可以为每种生产类型设置优先级。',
    'you don	 run out of': '你用完了',
    "you don	 waste workforce in production/culture/science that can't be used": '你浪费了无法使用的生产/文化/科学领域的劳动力',
    'your people have enough': '你的人民有足够的',
    "Dark theme (experimental": '黑色模式 (实验性',
    "don't drop under 20% (as much as possible" : "不要让它低于 20% (尽可能的",
    "(as much as possible" : '(尽可能的',
    "your" : '你的',
    " don't drop under 20% (as much as possible)" : '不要降到20％以下（尽可能）',
    ", you will be able to queue tech research." : '，你将可以排队进行技术研究。',
    " production" : '生产',
    "will go down depending on the population of a city,the distance from your capital and can be increased with artists,buildings or policies." : '会随着人口和与首都的距离增加而下降，并且可以通过招募艺人、建造一些建筑物以及部分政策来增加。',
    "You must be careful to not let health drop too low or your citizens will begin to die from disease." : '你必须小心，不要让健康下降太多，否则你的公民将开始死于疾病。',
    "Your people will be more efficient when they are happy and not so much when they get sad. Be carfeul to keep it not too low or they will revolt and rebel against you!" : '员工高兴时会更有效率，而悲伤时则不会那么有效率。 要小心，不要让它过低，否则他们会起义并反抗你！',
    "What's the point of": '有什么意义',
    'When you die or when you decide to reincarnate, you will lose': '当你死亡或决定转世时，你将会失去',
    'which should make your new life easier!': '这会使你的下一次游戏更轻松！',
    'you will receive. There are different types of favor. A neutral favor and one special for each': '将得到，有不同的神恩类型，有中立的神恩，每个神也各有一种',
    "Your cities can be pillaged too, so be careful about it !" :'你的城市也可能被掠夺，所以要小心！',
    "You will need it to construct buildings, to recruit troops and to pay for your troops maintenance." : '你将需要它来建造建筑物，招募部队并支付部队维护费用。',
    "You will not be able to store an infinite amount of gold. There is a limit to it which can be increased by constructing various buildings." : '你将无法存储无限量的黄金。 有一个上限，可以通过建造各种建筑物来增加上限',
    "which is a greate way to keep good relations with them while producing gold and culture" : '这是获得黄金和文化的同时还能与他们保持良好关系的好方法',
    'first, then send it to another city by clicking on your city on the world map and selecting "Trade route".' : '首先，然后通过在世界地图上单击你的城市并选择“贸易路线”将其发送到另一个城市',
    "with other" : '和其他',
    "you are not at war with" : '你和下列文明不在战争状态',
    "You are not alone in the world. Other civilizations are present and trying to extend too." : '你并不孤单，其他文明也存在并且也在努力扩展',
    " can be an essential part of your game or not. It depends on how you like to play." : '是否可以成为你游戏的重要组成部分，这取决于你想怎么玩这个游戏',
    "You will want to attack a city for 2 reasons: To pillage it and gain gold or to conquer it." : '你攻击一座城市的目的有两个：掠夺城市并获得金币或征服它',
    "You can capture cities from barbarians or other civilizations the same way." : '你可以用同样的方法来占领土著或其他文明的城市。',
    "A battle is fought in multiple assault" : '一场战斗是由多种攻击组成',
    "Siege units attack first. Siege attack points are used against all defending units defense points. No one fights back." : '攻城部队首先攻击，攻城攻击会作用于所有防御单位的防御值，攻城单位不能被反击',
    "At this point, the defense buildings can be crushed if there was enough siege units." : '此时，如果有足够的攻城部队，可以摧毁防御建筑',
    "Finally, melee units attack. Only melee units can fight back" : '最后，近战部队进攻，只有近战部队才能反击近战攻击',
    "Ranges units attack second. Defending ranged units can fight back,which means their attack points are used against attackers defense points" : '远程部队随后攻击，防御方的远程部队可以反击，反击伤害作用于所有攻击单位',
    'To be able to recruit units, you usually have to construct the necessary building.': '为了能够招募单位，你通常必须建造必要的建筑物。',
    'To bring a': '带上',
    'To completly clear the city from ALL troops': '彻底清除所有部队的城市',
    'within your attack.': '在你的攻击中',
    'You are protected from attacks until you get to the Ancient Era, so make sure to recruit enough to defend yourself before entering this era !': '在进入上古时代之前，你会受到战斗保护，因此在进入这个时代之前，请确保招募足够多的部队驻守！',
    'Your cities defense will increase with its population, a few buildings and a few policies': '你的城市防御能力将随着人口，一些建筑物和一些政策的增加而增加',
    'a city, you need': '一个城市，你需要',
    "Defending" : '防御',
    "You can also send them to explore automatically. In that case they will walk around the map, discovering lands in random directions." : '你也可以让他们自动探索，在这种情况下，他们将在地图上自动探索地图',
    "When a spy execute a mission, he has a chance to steal some" : '当间谍执行任务时，他有机会偷走一些',
    "with you (only 1 is needed to take a city)." : '一起（只需要1个就能占领城市）。',
    "you will be able to discover new" : '你将能够发现新的',
    ' provides': '提供',
    "(with a major penality of" : '（主要惩罚为',
    'warrior': '勇士',
    'Tactics': '战术',
    'Battle Simulator': '战斗模拟器',
    'Battle simulator': '战斗模拟器',
    'Increase view range of': '增加侦查范围',
    'scouts': '侦察兵',
    'Spy': '间谍',
    'In queue': '在队列中',
    'City conquered !': '占领城市',
    'Shanghai': '上海',
    'Theology': '神学',
    'Chivalry': '骑士精神',
    'Feudalism': '封建制度',
    'Currency': '货币',
    'Distance from capital': '与首都的距离',
    'Barrack(Despotism': '兵营(独裁',
    'After your first': '完成第一次',
    'has finished the construction of': '已经完成建造',
    'Civil Service': '行政部门',
    'Music Theory': '音乐',
    'Engineering': '工程学',
    'Anatomy': '解剖学',
    'Adv. Fortification': '筑城',
    'Physics': '物理学',
    'Steel': '钢铁',
    'Tenochtitlan': '特诺奇提特兰',
    'Training Center': '训练中心',
    'Use ctrl': '使用Ctrl键',
    'click to add to queue': '鼠标点击添加到科学队列',
    'When you': '当你',
    'You will never be able to interact with': '你永远不能交互',
    'capture': '占领',
    'Are you sure you want to reincarnate ?': '你确定你要转生吗？',
    'You will gain': '你将获得',
    'You will keep': '你将保留',
    'your powers,your previously earned favor': '你的力量和你已有的神恩',
    'You will lose': '你将失去',
    'everything else': '除此之外的所有东西',
    'Attacker': '攻击方',
    'Defender': '防御方',
    'Troop': '部队',
    'Number': '数量',
    'Remaining': '剩余',
    'This simulates a battle against barbarians.Result migkht be different against a real civilization.': '此模拟器模拟的是你与土著的战斗，和其它文明之间的战斗结果也许会不同',
    'spy': '间谍',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    "(": "(",
    "-": "-",
    "+": "+",
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    'A': '一个',
    'www.flaticon.com': 'www.flaticon.com',
    'x': 'x',
    '-': '-',
    ',': ',',
    '?': '?',
    '.': '.',
    '(': '(',
    '/': '/',
    '|': '|',
    '＆': '＆',
    'Give 10 Kreds': 'Give 10 Kreds',
    'Give 100 Kreds': 'Give 100 Kreds',
    'Give 1000 Kreds': 'Give 1000 Kreds',
    'Give 20 Kreds': 'Give 20 Kreds',
    'Give 200 Kreds': 'Give 200 Kreds',
    'Give 50 Kreds': 'Give 50 Kreds',
    'Give 500 Kreds': 'Give 500 Kreds',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    'A new discovery': '研究完成',
    'trade routes': '贸易路线',
    'Trade routes': '贸易路线',
    'Trade Routes': '贸易路线',
    'Trade Route': '贸易路线',
    'A new citizen is available in': '一个新的市民出现在了',
    'A new feature has been unlocked': '一个新的功能被解锁了',
    'State': '国家',
    'New civilization discovered': '新的文明被发现',
    'Diplomacy': '外交',
    'Gardens': '花园',
    'Gold transfer arrived in': '黄金运输队已经抵达',
    'Military': '军事',
    'Production': '产量',
    'Time': '时间',
    'Warrior': '勇士',
    'Time to recruit': '招募时间',
    'War': '战争',
    'Allow recruitment of melee': '允许招募军事单位',
    'Attacks': '进攻',
    'Battle of': '战斗在',
    'Copper Mine': '铜矿',
    'Culture': '文化',
    'has finished the construction of': '已经完成',
    'Player': '文明',
    'Religion': '宗教',
    'limit to' : '限制于',
    'Victory in': '战斗胜利在',
    'Your troops have arrived in': '你的部队抵达了',
    'Trade routes to': '贸易路线通往',
    'Village': '村',
    'Well': '水井',
    'Aqueduct': '水渠',
    'Town Hall': '市政厅',
    'Longhouse': '长屋',
    'Chest': '箱子',
    'Monument': '纪念碑',
    'Granary': '粮仓',
    'Copper Mine': '铜矿',
    'Tribunal': '裁判所',
    'Workshop': '工坊',
    'Town Hall': '市政厅',
    'Treasury': '财政部门',
    'Gardens': '花园',
    'Palace': '宫殿',
    'Walls': '城墙',
    'Stables': '马厩',
    'Castle': '城堡',
    'Opera': '歌剧院',
    'Embassy': '大使馆',
    'Consulate': '领事馆',
    'Temple': '寺庙',
    'Monastery': '寺院',
    'Armies': '军队',
    'Gold Mine': '金矿',
    'Market': '市场',
    'Bank': '银行',
    'Mint': '铸币厂',
    'Theatre': '剧场',
    'Circus': '马戏团',
    'Aqueduct': '水渠',
    'Hospital': '医院',
    'Armory': '军械库',
    'Siege Factory': '攻城武器工厂',
    'Military Academy': '军事学院',
    'Furnace': '熔炉',
    'Monastery': '寺院',
    'Barracks': '兵营',
    'Shrine': '圣地',
    'Temple': '寺庙',
    'Library': '图书馆',
    'Uprising in': '起义在',
    'Bronze Working': '青铜铸造',
    'Crop Rotation': '轮作',
    'Language': '语言',
    'Dog domestication': '驯养狗',
    'Tanning': '制革',
    'Pottery': '制陶',
    'Trade': '交易',
    'Spirituality': '精神',
    'Mining': '采矿',
    'Tools': '工具',
    'Art': '艺术',
    'Exploration': '探索',
    'Agriculture': '农业',
    'Archery': '箭术',
    'Writing': '写作',
    'State': '国家',
    'Herding': '放牧',
    'Navigation': '导航',
    'Horseriding': '骑术',
    'Wheel': '车轮',
    'Masonry': '砖石建筑',
    'Justice': '正义',
    'Calendar': '日历',
    'Literature': '文学',
    'Mathematics': '数学',
    'Tactics': '战术',
    'Iron Working': '铁器',
    'Monarchy': '君主制',
    'Drama': '戏剧',
    'Optics': '光学',
    'Construction': '建造',
    'Military': '军事',
    'Republic': '共和国',
    'Theology': '神学',
    'Civil Service': '行政部门',
    'Feudalism': '封建制度',
    'Currency': '货币',
    'Music Theory': '音乐',
    'Engineering': '工程学',
    'Chivalry': '骑士精神',
    'Anatomy': '解剖学',
    'Adv. Fortification': '筑城',
    'Physics': '物理学',
    'Steel': '钢铁',
    'Education': '教育',
    'Training Center': '训练中心',
    'Global cities': '总城市数',
    'Global population': '总人口',
    'Global troops': '总部队数',
    'Milling': '研磨',
    'Mill': '磨坊',
    '': '',
    '': '',
    '': '',
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "s (+": "s (+",
    "(": "(",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    'Village': '村',
    'Agriculture': '农业',
    'Artist': '艺术家',
    'Archery': '箭术',
    'Art': '艺术',
    'trade routes': '贸易路线',
    'Trade routes': '贸易路线',
    'Trade Route': '贸易路线',
    'Dog domestication': '驯养狗',
    'Exploration': '探索',
    'Language': '语言',
    'Mining': '采矿',
    'Pottery': '制陶',
    'Spirituality': '精神',
    'Tanning': '制革',
    'Tools': '工具',
    'Trade': '交易',
    'Ancient Era': '上古时代',
    'Builder': '建筑工人',
    'Buildings': '建筑',
    'Daily Bonus': '每日奖励',
    'Merchant': '商人',
    'Social Policies': '社会政策',
    'Troop queues': '部队队列',
    'Troops': '部队',
    'World panel': '世界组织',
    'citizen': '市民',
    'hunter-gatherer': '采猎者',
    'Monastery': '寺院',
    'trade route': '贸易路线',
    'in the Capital': '在首都',
    'Persians': '波斯',
    'buildings and can be increased in several ways, including': '建筑可以通过多种方法解锁，包括',
    'buildings and can be increased in several ways.': '建筑可以通过多种方法解锁',
    'buildings,': '建筑，',
    'the gold production will drop when you reach the limit, allowing your citizens to work on more useful tasks.': '当黄金达到上限，你的市民将自动转移到其它更有用的工作上去',
    'they will grant you special favor that you can choose to spend on powers.': '它们会给你一些特殊的奖励，你可以把它们花费在力量上',
    'you need to recruit a': '你需要招募一个',
    'you will be able to chose a deity to worship. Each deity have a special power they will grant their followers.': '你可以选择一个神来崇拜，每个神都会给予追随者一些特殊的力量',
    'you will be able to create': '你将允许创建',
    'you will be able to interact with them more.': '你将允许和它们进行更多互动',
    'you will be receive one random gift every 24h.': '你每24小时将获得一个随机的礼物',
    'And once you discover': '并且一旦你发现',
    'Those beasts need to be pacified.': '那些野蛮人需要被物理和平',
    'Those favors can be used to acquire': '你可以获得这些好处',
    'barracks': '兵营',
    'Barracks': '兵营',
    'citizen': '市民',
    'library': '图书馆',
    'Library': '图书馆',
    'Monastery': '寺院',
    'scientist': '科学家',
    'shrine': '圣地',
    'Shrine': '圣地',
    'Temple': '寺庙',
    'trade route': '贸易路线',
    'University': '大学',
    'attack & defense against barbarians': '对土著的攻防加成',
    'chance to break walls & castle with siege units': '攻城器械破坏城墙和城堡的概率',
    'Barb. vil.': '土著村庄',
    'Aztecs': '阿兹特克',
    'Delay': '延迟',
    'ranged units': '远程单位',
    'Transfers': '运输',
    'is over !': '已经完成',
    'Armies': '军队',
    'Bronze Working': '青铜铸造',
    'Calendar': '日历',
    'Crop Rotation': '轮作',
    'Herding': '放牧',
    'Horseriding': '骑术',
    'Justice': '正义',
    'Literature': '文学',
    'Masonry': '砖石建筑',
    'Navigation': '导航',
    'Wheel': '车轮',
    'Writing': '写作',
    'Assyrians': '亚述',
    'Chinese': '中国',
    'Egyptians': '埃及',
    'Greeks': '希腊',
    'Incans': '印加',
    'Indians': '印度',
    'Romans': '罗马',
    'Vikings': '维京',
    'Zulus': '祖鲁',
    'Building queues': '建筑队列',
    'Diplomacy': '外交',
    'Empire panel': '帝国面板',
    'Powers': '力量',
    'Scientist': '科学家',
    'Mathematics': '数学',
    'has lost his last city': '失去了他最后一座城市',
    'Science queue': '科技队列',
    " Academy" :'学院',
    'reincarnation': '重生',
    'buildings cost': '建筑花费',
    ' units cost': '单位成本',
    'have been lost': '已经丢失',
    'farmer': '农夫',
    'builder': '建筑工人',
    'artist': '艺人',
    'social policy': '社会政策',
    'building': '建筑',
    'city owned': '拥有城市',
    'Well': '水井',
    'Aqueduct': '水渠',
    'Town Hall': '市政厅',
    'tech discovered': '已研究科技',
    'Longhouse': '长屋',
    'Chest': '箱子',
    'Monument': '纪念碑',
    'Granary': '粮仓',
    'Copper Mine': '铜矿',
    'Tribunal': '裁判所',
    'Workshop': '工坊',
    'Town Hall': '市政厅',
    'Treasury': '财政部门',
    'Gardens': '花园',
    'Palace': '宫殿',
    'Walls': '城墙',
    'Stables': '马厩',
    'Castle': '城堡',
    'Opera': '歌剧院',
    'Embassy': '大使馆',
    'Consulate': '领事馆',
    'Temple': '寺庙',
    'Monastery': '寺院',
    'Armies': '军队',
    'Gold Mine': '金矿',
    'Market': '市场',
    'Bank': '银行',
    'Mint': '铸币厂',
    'Theatre': '剧场',
    'Circus': '马戏团',
    'Aqueduct': '水渠',
    'Hospital': '医院',
    'Armory': '军械库',
    'Siege Factory': '攻城武器工厂',
    'Military Academy': '军事学院',
    'Furnace': '熔炉',
    'have been lost because city has been taken': '已经中断，因为其中一座城市被占领',
    'State': '国家',
    'Tactics': '战术',
    'Iron Working': '铁器',
    'Monarchy': '君主制',
    'Drama': '戏剧',
    'Optics': '光学',
    'Construction': '建造',
    'Military': '军事',
    'Republic': '共和国',
    'Theology': '神学',
    'Civil Service': '行政部门',
    'priests': '牧师',
    'merchants': '商人',
    'Feudalism': '封建制度',
    'Currency': '货币',
    'Music Theory': '音乐',
    'Engineering': '工程学',
    'Chivalry': '骑士精神',
    'Anatomy': '解剖学',
    'Adv. Fortification': '筑城',
    'Physics': '物理学',
    'Steel': '钢铁',
    'Education': '教育',
    'Training Center': '训练中心',
    'Milling': '研磨',
    'Mill': '磨坊',
    '': '',
    '': '',
    '': '',
    '': '',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);