//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'primary': '主要',
    'secondary': '次要',
    'exotic': '异国',
    'helium': '氦',
    'essence': '真髓',
    'token': '符记',
    'magma': '岩浆',
    'events': '事件',
    'repeated': '重复',
    'unique': '独特',
    'trimp': '脆皮',
    'enemy': '敌人',
    'food': '食物',
    'Food': '食物',
    'wood': '木头',
    'Wood': '木头',
    'metal': '金属',
    'Metal': '金属',
    'fragments': '碎片',
    'Fragments': '碎片',
    'gems': '宝石',
    'Gems': '宝石',
    'science': '科学',
    'Science': '科学',
    'Fire': '火焰',
    'Frost': '冰霜',
    'Wind': '风',
    'Ice': '冰',
    //传家宝
    'Magmatic Shield': '岩浆盾',
    'Magmatic Staff': '岩浆员工',
    'Legendary Staff': '传奇的员工',
    'Magnificent Shield': '华丽的盾牌',
    'Legendary Shield': '传奇的盾牌',
    'Magnificent Staff': '华丽的员工',
    'Plagued Shield': '天灾之盾',
    'Plagued Staff': '天灾之棍',
    'Epic Shield': '史诗之盾',
    'Epic Staff': '史诗之棍',
    'miner': '矿工',
    'lumber': '木料',
    'farming': '农业',
    'Poison': '毒',
    'Knowledge': '知识',
    'Condenser': '冷凝',
    'Strength': '力量',
    'Lightning': '闪电',
    'Monday': '周一',
    'Tuesday': '周二',
    'Wednesday': '周三',
    'Thursday': '周四',
    'Friday': '周五',
    'Saturday': '周六',
    'Sunday': '周日',
    'Improbability': '无序',
    'Corrupt': '腐败',
    'Penguimp': '企鹅',
    'Magma': '岩浆',
    'Healthy': '健康的',
    'Obliterated': '湮没',
    'Common Core': '共同核心',
    'Rare Core': '稀有核心',
    'Uncommon Core': '罕见核心',
    'Nullifium': '虚空物质',
    'Nu': '虚空物质',
    '': '',
    //传家宝效果
    'Condenser Effect': '冷凝器效果',
    'Runestone Drop Rate': '符石掉率',
    'Fire Trap Damage': '火焰陷阱的伤害',
    'Poison Trap Damage': '毒陷阱的伤害',
    'Lightning Trap Damage': '光陷阱的伤害',
    'Fluffy Exp': '蓬松经验',
    'Plaguebringer': '瘟疫传播',
    'Strength Tower Effect': '力量塔效果',
    'Ss': '尖塔石头',
    '': '',
    '': '',
    '': '',
    '': '',
    //特权
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Domination': '统治',
    //从这里开始是时间传送门下的按钮
    'Discipline': '纪律',
    'Daily': '日常',
    'Metal': '金属',
    'Size': '尺寸',
    'Balance': '平衡',
    'Scientist V': '科学家 V',
    'Scientist': '科学家',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Meditate': '冥想',
    'Decay': '衰变',
    'Trimp': '脆皮',
    'Trapper': '捕手',
    'Electricity': '电流',
    'Frugal': '节俭',
    'Life': '生命',
    'Nom': '美味',
    'Lead': '领导',
    'Watch': '观望',
    'Mapocalypse': '地图的启示',
    'Mapology': '地图学',
    'Coordinate': '协同',
    'Crushed': '粉碎',
    'Toxicity': '毒性',
    'Devastation': '破坏',
    'Corrupted': '腐化',
    'Slow': '迟钝',
    //统计
    'Dead Trimps': '死去的脆皮',
    'Battles Won': '战斗胜利',
    'Battles Lost': '战斗失败',
    'Maps Cleared': '地图清除',
    'Zones Cleared': '区域清除',
    'Gems Collected': '宝石收集',
    'Wormholed Helium': '虫洞氦气',
    'He/Hour this Run': '本次游戏氦/小时',
    'Best He/Hr this Run': '本轮游戏中最高的氦/小时',
    'Highest Void Map Clear': '最高虚空地图清除',
    'Golden Upgrades': '黄金升级',
    'Heirlooms Found': '传家宝发现',
    'Daily Challenge Helium': '每日的挑战氦',
    'World Cells Overkilled': '超杀世界单元格敌人数量',
    'Trimps from Generator': '维度发生器生产的脆皮',
    'Nurseries Closed by Magma': '由岩浆封闭的幼儿园',
    'Zones Liquified': '区域液化',
    'Highest Zone': '最高区域',
    'Total Portals Used': '使用的总传送门',
    'Total Helium Earned': '获得总氦气',
    'Best He/Hour all Runs': '所有轮游戏中最高的氦/小时',
    'Planets Broken': '行星破碎',
    'Burned Nurseries': '燃烧的托儿所',
    'Trap/Tower Kills': '陷阱/塔杀死',
    'Gems Collected': '收集宝石',
    'Maps Cleared': '已清理地图',
    'Zones Cleared': '已清理区域',
    'Trimps Fired': '解雇的脆皮',
    'Food/Wood/Metal': '食物/木头/金属',
    'Total Void Maps Cleared': '总计清理虚空地图',
    'Tokens This Run': '本次游戏获得的符记',
    'Amalgamators Befriended': '合并者帮助',
    'Fluffy Exp This Run': '本次游戏蓬松经验',
    'Fluffy Exp/Hr this Run': '本次游戏蓬松经验/小时',
    'Most Tokens': '符记最高数量',
    'Best Fluffy Exp': '最高蓬松经验',
    'Best Fluffy Exp/Hr': '最高蓬松经验/小时',
    'Best Fluffy Exp/Hr this Run': '本次游戏最高蓬松经验/小时',
    'cache': '缓存',
    'bone': '骨头',
    'Classy': '经典',
    //汉化维度发生器升级标题
    'Efficiency': '效率',
    'Capacity': '容量',
    'Supply': '供给',
    'Overclocker': '超频',
    'Hybridization': '混合',
    'Storage': '存储',
    'Shielding': '屏障',
    'Slowburn': '缓慢燃烧',
    'Supervision': '管理',
    'Simulacrum': '复制',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '茅舍',
    'House': '房子',
    'Mansion': '大厦',
    'Hotel': '旅馆',
    'Resort': '娱乐场',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Loot': '战利品',
    'Unlocks': '解锁',
    'Combat': '战斗',
    'enabled': '启用',
    //修饰符
    'Fast Attacks': '快速攻击',
    'Large Cache': '大缓存',
    'Huge Cache': '巨大缓存',
    'Small Savory Cache': '小美味缓存',
    'Small Wooden Cache': '小木制缓存',
    'Small Metal Cache': '小金属缓存',
    'Large Savory Cache': '大美味缓存',
    'Large Wooden Cache': '大木制缓存',
    'Large Metal Cache': '大属缓存',
    'Prestigious': '声望',
    'Legendary': '传奇',
    'Magnificent': '史诗',
    'Magmatic': '岩浆',
    'Ethereal': '暗金',
    'Story': '故事',
    '': '',
    '': '',
    '': '',
    //1.2.标题
    'Shield': '盾',
    'Dagger': '匕首',
    'Boots': '靴子',
    'Mace': '狼牙棒',
    'Helmet': '头盔',
    'Polearm': '长柄武器',
    'Pants': '裤子',
    'Battleaxe': '战斧',
    'Shoulderguards': '护肩',
    'Greatsword': '巨剑',
    'Breastplate': '护胸甲',
    'Arbalest': '劲弩',
    'Gambeson': '夹克',
    'Trap': '陷阱',
    'Barn': '谷仓',
    'Shed': '窝棚',
    'Forge': '锻造室',
    'Hut': '茅舍',
    'House': '房子',
    'Mansion': '大厦',
    'Hotel': '旅馆',
    'Resort': '娱乐场',
    'Gateway': '出入口',
    'Wormhole': '虫洞',
    'Collector': '集电极',
    'Warpstation': '经纱站',
    'Gym': '健身房',
    'Tribute': '贡品',
    'Nursery': '托儿所',
    'Farmer': '农民',
    'Lumberjack': '伐木工',
    'Miner': '矿工',
    'Scientist': '科学家',
    'Scientists': '科学家',
    'Trainer': '培训师',
    'Trainers': '培训师',
    'Explorer': '探险家',
    'Magmamancer': '巫师',
    'Amalgamator': '合并者',
    'Fire Trimps': '解雇脆皮',
    'Gigastation': '千兆站',
    'Geneticistassist': '遗传学家助手',
    'Geneticist': '遗传学家',
    'Agility': '敏捷',
    'Bait': '诱饵',
    'Pheromones': '信息素',
    'Packrat': '包装',
    'Motivation': '动机',
    'Power': '力量',
    'Toughness': '坚韧',
    'Looting': '掠夺',
    'Trumps': '法宝',
    'Custom': '自定义',
    'Confirm Purchase': '确认购买',
    'Looting II': '劫掠 II',
    'Carpentry II': '木工 II',
    'Power II': '力量 II',
    'Toughness II': '坚韧 II',
    'Capable': '能力',
    'Cunning': '狡猾',
    'Curious': '好奇',
    'Overkill': '超杀',
    'Resourceful': '足智多谋',
    'Coordinated': '协调',
    'Coordination': '协作',
    'Siphonology': '虹吸学',
    'Anticipation': '预期',
    'Resilience': '弹性',
    'Meditation': '冥想',
    'Relentlessness': '无情',
    'Battle': '战斗',
    'Carpentry': '木工',
    'Artisanistry': '艺术性',
    'Range': '范围',
    'Motivation II': '动机 II',
    'Bloodlust': '嗜血',
    'Miners': '矿工',
    'Speedminer': '采矿加速',
    'Speedlumber': '砍伐加速',
    'Speedfarming': '耕作加速',
    'Speedscience': '研究加速',
    'Efficiency': '生产效率',
    'Megamace': '巨型狼牙棒',
    'Hellishmet': '地狱头盔',
    'Supershield': '超级盾牌',
    'Dagadder': '攻击匕首',
    'Bootboost': '增速靴',
    'Polierarm': '更长武器',
    'Pantastic': '七分裤',
    'Axeidic': '斧头',
    'Smoldershoulder': '阴燃肩',
    'Greatersword': '更大的剑',
    'Bestplate': '更好的胸甲',
    'Speedexplorer': '探险家加速',
    'Gigastation': '千兆站',
    'TrainTacular': '防御提升',
    'Potency': '繁殖效率',
    'Max': '最大',
    'AutoStorage': '自动存储',
    'AutoStructure': '自动建筑',
    'Configure AutoStructure': '自动建筑配置',
    'AutoUpgrade': '自动升级',
    'AutoPrestige': '自动重铸装备',
    'AutoGolden': '自动黄金升级',
    'Harmbalest': '伤害平衡',
    'GambesOP': '胫甲OP',
    'Maps': '地图',
    'Rename Preset': '重命名预设',
    'Portal': '传送门',
    'Pierce': '穿刺',
    'Fast': '快速',
    'Save Map Settings': '保存地图设置',
    'Reset Map Settings': '重置地图设置',
    'Recycle All': '回收所有',
    'Map Preset': '回收所有',
    'Gymystic': '健身学',
    'Shieldblock': '盾牌防御',
    'Trapstorm': '自动陷阱',
    'Blockmaster': '防御大师',
    'Decay': '衰变',
    'Show/Hide Map Config': '显示/隐藏地图设置',
    'Electricity': '电流',
    'Mastery': '专精',
    'Empowerments of Nature': '自然赋权',
    'Switch Daily': '选择日常挑战',
    'Empower': '赋能',
    'Pressure': '压力',
    'MagnetoShriek': '磁力护盾',
    'Unliving': '亡灵化',
    'Bloodthirst': '嗜血',
    'Scryer Formation': '占卜者阵型',
    'Fire Trap': '火焰陷阱',
    'Frost Trap': '冰霜陷阱',
    'Shift Up': '后移',
    'Shift Down': '前移',
    'Sell Trap/Tower': '出售陷阱/塔',
    'Queue': '队列',
    'Biome': '生物群落',
    'Size': '尺寸',
    'Loot': '抢劫',
    'Special Modifier': '特殊修饰符',
    'Extra Zones': '额外区域',
    'Difficulty': '难度',
    'Perfect Sliders': '完美的滑块',
    'Enchanted Gardens': '魔法花园',
    'Repeat Map': '重复地图',
    'Heirloom': '传家宝',
    'Trustworthy Trimps': '守信的脆皮',
    'World Info': '世界信息',
    'AutoGold': '自动黄金',
    'Threat': '威胁',
    'Enemies': '敌人',
    'Runestones': '符石',
    'Spirestones': '尖塔石头',
    'Trimps Per Second': '每秒脆皮',
    'Max Trimps': '脆皮上限',
    'Scryhard I': '努力占卜 I',
    'Scryhard II': '努力占卜 II',
    'AutoJobs': '自动工作',
    'Legs for Days': '天残脚',
    'Explorer Aura I': '探险家光环 I',
    'Explorer Aura II': '探险家光环 II',
    'Respec Masteries': '洗点',
    'Configure Maps': '配置地图',
    'Map at Spires': '尖塔地图',
    'Import Perk Preset': '导入Perk预设',
    'Export Perk Setup': '导出Perk设置',
    //专精
    'Bionic Magnet I': '仿生磁 I',
    'Bionic Magnet II': '仿生磁 II',
    'Portal Generator': '传送门生成器',
    'Bounty Hunter': '赏金猎人',
    'Home Detector': '家庭探测器',
    'Turkimp Tamer I': '驯兽师 I',
    'Turkimp Tamer II': '驯兽师 II',
    'Turkimp Tamer III': '驯兽师 III',
    'Turkimp Tamer IV': '驯兽师 IV',
    'Void Power I': '虚空力量 I',
    'Void Power II': '虚空力量 II',
    'Void Power III': '虚空力量 III',
    'Metallic Coat': '金属外套',
    'Headstart I': '领先地位 I',
    'Headstart II': '领先地位 II',
    'Headstart III': '领先地位 III',
    'Foremany': '脱颖而出',
    'Map Reducer I': '地图还原剂 I',
    'Map Reducer II': '地图还原剂 II',
    'Double Build': '双重建造',
    'King of Bones I': '骨头之王 I',
    'King of Bones II': '骨头之王 II',
    'Hyperspeed I': '超高速 I',
    'Hyperspeed II': '超高速 II',
    'Blacksmithery I': '黑煅炼 I',
    'Blacksmithery II': '黑煅炼 II',
    'Blacksmithery III': '黑煅炼 III',
    'Quick Gen': '快速第二代',
    'AutoStructure': '自动结构',
    'Magma Flow': '岩浆流',
    'Natural Diplomacy I': '自然外交 I',
    'Natural Diplomacy II': '自然外交 II',
    'Natural Diplomacy III': '自然外交 III',
    'Liquification I': '液化 I',
    'Liquification II': '液化 II',
    'Magmamancermancy': '大巫师',
    'Patience': '忍耐',
    'Still Rowing I': '持续赛艇 I',
    'Still Rowing II': '持续赛艇 II',
    'Strength in Health': '生命的力量',
    'Void Specialization I': '虚空专精 I',
    'Void Specialization II': '虚空专精 II',
    'Megascience': '超级科学',
    'Magmamancers': '岩浆魔法师',
    'Megafarming': '大型农业',
    'Condenser Tower': '冷凝塔',
    'Condenser Tower II': '冷凝塔 II',
    'Knowledge Tower': '知识塔',
    'Knowledge Tower II': '知识塔 II',
    'Poison Trap': '毒物陷阱',
    'Poison Trap II': '毒物陷阱 II',
    'Megaminer': '超级矿工',
    'Lightning Trap': '闪电陷阱',
    'Lightning Trap II': '闪电陷阱 II',
    'Frost Trap IV': '冰霜陷阱 IV',
    'Strength Tower': '力量之塔',
    'Strength Tower II': '力量之塔 II',
    'Strength Tower III': '力量之塔 III',
    'Fire Trap III': '火焰陷阱 III',
    'Trap Layout 1': '陷阱布局 1',
    'Trap Layout 2': '陷阱布局 2',
    'Configure AutoJobs': '配置自动工作',
    'Configure Generator State': '配置生成器状态',
    'Spire Settings': '尖塔设置',
    'Well Fed': '吃的很饱',
    'Fluffy': '蓬松',
    'UberHotel': '优步酒店',
    'UberMansion': '优步',
    'UberResort': '优步娱乐场',
    'No Map At Zone': '区域没有地图',
    'UberHouse': '优步房子',
    'UberHut': '优步茅舍',
    'Map Corruption': '地图腐化',
    'Food/Wood/Metal Loot Breakdown': '食物/木头/金属 洗劫一空',
    'Breezy': '活泼的',
    'Deca Build': '十进制构建',
    'Amalgagreater': '融合器',
    'Flufffocus': '蓬松焦点',
    'Excessive': '过度',
    'Flufffinity': '蓬松有限性',
    'Charged Crits': '带电暴击',
    'Confirm Respec Masteries': '确认专精洗点',
    //成就
    'Maptain': '地图符号',
    "What's This For?": '这个是干什么的?',
    'Collector of Shinies': '闪亮的收藏家',
    'Dragimp Lover': 'Dragimp爱人',
    'Expert of Shinies': '闪亮的专家',
    'Jeweller': '珠宝商',
    'Gemaster': '宝石大师',
    'Feats': '专长',
    'Speed: The Block': '速度: 障碍区',
    'Speed: The Wall': '速度: 高墙',
    'Speed: Anger': '速度: 愤怒维度',
    'Speed: Doom': '速度: 末日神殿',
    'Speed: The Prison': '速度: 监狱',
    'Speed: Bionic': '速度: 仿生仙境',
    'Speed: Star': '速度: 爆炸之星',
    'Frigid': '寒冷',
    'Gallop to Doom': '奔向末日',
    'Canter to Doom': '注定失败',
    'Walk to Doom': '走到末日',
    'Trot to Doom': '快步走向末日',
    'Map Destroyer': '地图毁灭者',
    'Centennial Trimper': '百年修剪者',
    'Prison Sprint': '监狱冲刺',
    'Prison Road Trip': '监狱之旅',
    'Frozen': '冻结',
    'Hour Bender': '小时狂欢',
    'Daylusional': '白天的',
    'Chilly': '冰冷',
    'Frosty': '寒霜',
    'Cool': '凉爽',
    'Coldlector': '冷冻机',
    'Expert': '能手',
    'Sitter': '坐着',
    'Gelid': '文件',
    'Amnesia': '健忘症',
    'Savior': '救世主',
    'Connoisseur': '行家',
    'Vacuum': '真空',
    'Aficionado': '业余',
    'Daystroyer': '日托',
    'Seeker': '探求者',
    'Fancier': '爱好者',
    'Adventurer': '冒险家',
    'GigaClearer': '千兆清理者',
    'Coddler': '小贩',
    'Pathfinder': '探路者',
    'Centelium': '中心',
    'Prison Trek': '监狱旅行',
    'Guardian': '守护者',
    'Dayrailed': '日日的',
    'Daylighted': '日光',
    'Cartographer': '制图师',
    'Map Maker': '地图绘制者',
    'Map Annihilator': '地图歼灭者',
    'Map Runner': '地图奔跑者',
    'Curator': '监护人',
    'Caretaker': '看管者',
    'Accumulator': '蓄电池',
    'Nanny': '保姆',
    'Daypocalyptic': '消日剂',
    'When The Wild Things Are': '当疯狂的事',
    'Advocate': '支持者',
    'Glacial': '冰河',
    'Vanquisher': '征服者',
    'Globetrotter': '周游世界',
    'Supervisor': '监督者',
    'Daystiny': '白昼的',
    'Crisp': '易碎',
    'Pioneer': '拓荒者',
    'Prison Tour': '监狱巡视路线',
    'Wall Student': '墙上的学生',
    'Wall Scaler': '墙壁标尺',
    'Prison Hike': '监狱远足',
    'Block Professional': '专业技术人员',
    'Daydicated': '走神的',
    'Prison Hike': '监狱徒步旅行',
    'Acquired Frost': '后天霜冻',
    'Time of Your Life': '你生命中的时光',
    'Brisk': '轻快',
    'A Trimp Through Time': '一个脆皮穿越时空',
    'Quick N Cool': '快速冷却',
    'Frosty Tanker': '结霜油船',
    'Daytermined': '白昼终结',
    'Venti Timeachino': '超大时间',
    'Zone Progress': '区域进度',
    'Trimp Damage': '脆皮伤害',
    'Trimps Owned': '拥有脆皮',
    'Real Estate': '房地产',
    'Total Portals': '总传送门',
    'Total Zone Clears': '总清理区域',
    'Total Map Clears': '地图总清理数',
    'Helium Collection': '氦收集',
    'Helium Per Hour': '氦每小时',
    'Heirloom Collection': '传家宝收藏',
    'Gem Collection': '宝石收集',
    'Daily Bonus': '日常奖励',
    'Humane Run': '人性化战斗',
    'A Time Like No Other': '没有别的时间',
    'Lucky Resolve': '幸运的决心',
    'This is Easy': '这很容易',
    'Blimp Slayer': '飞艇杀手',
    'Groundbreaker': '开拓性',
    'The Beginning': '开端',
    'Determined': '决心',
    'Professor': '教授',
    'Trimp Aficionado': '脆皮业余爱好者',
    'Slayer of Planets': '星际杀手',
    'Motivated': '上进心',
    'Electric': '电气',
    'Stronk': '残端',
    'Endurance': '耐久力',
    'Unwavering': '坚定不移',
    'Coordinated': '配合',
    'Resolved': '已解决',
    'Steadfast': '坚定',
    'Grit': '砂砾',
    'Perseverance': '恒心',
    'Persistence': '坚持',
    'Tenacity': '韧性',
    'The Instigator': '研究者',
    'The Destroyer': '破坏者',
    'The Eradicator': '毁灭者',
    'The Exterminator': '灭火器',
    'Heat Maker': '制热机',
    'Heat Hater': '加热器',
    'Heat Breaker': '热断路器',
    'Heat Slayer': '热火杀手',
    'Heat Expert': '热火专家',
    'Heat Bender': '热弯机',
    'Volcanic': '火山',
    'Magma Master': '岩浆大师',
    'Acre of Nature': '大自然',
    'Aspirer': '灵感',
    'Insane': '癫狂',
    'Spire Master': '尖塔大师',
    'Speed: Spire': '速度: 尖塔',
    'Speed: Spire II': '速度: 尖塔 II',
    'Speed: Spire III': '速度: 尖塔 III',
    'Speed: Spire IV': '速度: 尖塔 IV',
    'Too Many Trimps': '太多脆皮',
    'Overcrowding': '人满为患',
    'This Is Trimp': '这是脆皮',
    'It Takes a Tribe': '建成部落',
    'It Takes a Town': '建成乡镇',
    'It Takes a City': '建成城市',
    'It Takes a Nation': '建成国家',
    'A Milli Trimpi': '百万脆皮',
    'MMMEGATRIMPS': '百万兆脆皮',
    'It Takes a Planet': '建成星球',
    'It Takes a Universe': '建成宇宙',
    'Trimpsponential Growth': '调整增长',
    'Tiny Homes': '小公寓',
    'Residential Development': '住宅开发',
    'Taste for Luxury': '品味奢华',
    'Fancy': '花俏',
    'The Skyline': '地平线',
    'Dimensional Drift': '维漂移',
    'Too Cool For Helium': '对氦来说太酷了',
    'Space From Stars': '星际空间',
    'To Infinity and Beyond': '无穷无尽',
    'Mass Generation': '质量产生',
    'Lead Trimps': '领导脆皮',
    'Silver Trimps': '银色脆皮',
    'Golden Trimps': '金色脆皮',
    'Copper Trimps': '铜色脆皮',
    'Platinum Trimps': '白金脆皮',
    'Iron Trimps': '铁脆皮',
    'Steel Trimps': '钢脆皮',
    'Obsidian Trimps': '黑曜石脆皮',
    'Cobalt Trimps': '钴脆皮',
    'Topaz Trimps': '黄玉脆皮',
    'Diamond Trimps': '钻石脆皮',
    'Transcendental Trimps': '超越脆皮',
    'Finder': '发现者',
    'Angry Runner': '愤怒的赛跑者',
    'Angry Racer': '愤怒的赛车手',
    'Angry Teleporter': '愤怒传送者',
    'Angry Sprinter': '愤怒的运动员',
    'Map Commander': '地图指挥官',
    'Map Slaughterer': '地图屠夫',
    'Dedicated Traveller': '专注的旅行者',
    'Squeaky Dasher': '吱吱嘎嘎的家伙',
    'Gatherer': '采集者',
    'Watchdog': '看门狗',
    'Bushwhacker': '游击队员',
    'Devotee': '信徒',
    'Prison Odyssey': '监狱探险',
    'Blimp Snatcher': '飞艇掠夺者',
    'Wall Contender': '墙壁竞争者',
    'Gusty Gait': '阵风步态',
    'Prison Jog': '监狱慢跑',
    'No Time for That': '不浪费时间',
    'Invisible': '无形',
    'Realtor': '房地产经纪人',
    'Holey': '洞穴',
    'Survivor': '幸存者',
    'Maptastic': '地图符号',
    'Void': '虚空',
    'Helium': '氦',
    'Gym X10': '健身房 X10',
    'Consolation Prize': '安慰奖',
    'Speed: Spire V': '速度:尖塔V',
    'actiVe': '激活',
    'Arctic Accelerator': '北极加速器',
    'driVen': '驱动',
    'Friend of Bots': '机器人的朋友',
    'Nerfed': '削弱',
    'Nerfeder': '继续削弱',
    'Tent City': '帐篷城',
    'Infected': '被感染',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //成就结束
    '': '',
    'Block': '防御',
    'Message Config': '消息设置',
    'Buy Max': '购买最大数量',
    'Save Perk Preset': '保存额外福利预设',
    'Rename Perk Preset': '重命名额外福利预设',
    'Load Perk Preset': '加载额外福利预设',
    'Classy': '经典',
    'Respec': '修改',
    'Health': '生命值',
    'Attack': '攻击力',
    'Set Map At Zone': '在区域内设置地图',
    'Megalumber': '巨型木材',
    'Void Map': '虚空地图',
    'Corruption': '腐败',
    'The Magma': '岩浆',
    'Error': '出错啦',
    'No Snow': '不显示雪',
    'Show Snow': '显示雪',
    //设置项目
    'Default Generator': '默认生成器',
    'Heirloom Animations': '传家宝动画',
    'Alert Mastery': '专精提醒',
    'Allow Big Popups': '允许大弹出窗口',
    'Tiny Perk Buttons': '小额外福利按钮',
    '': '',
    '': '',
    '': '',
    //1.3.地图
    'Dimension of Anger': '愤怒维度',
    'The Prison': '监狱',
    'Bionic Wonderland': '仿生仙境',
    'Bionic Wonderland X': '仿生仙境X',
    'Bionic Wonderland IX': '仿生仙境IX',
    'Bionic Wonderland XI': '仿生仙境XI',
    'The Block': '障碍区',
    'The Wall': '高墙',
    'Trimple Of Doom': '末日之神殿',
    'Imploding Star': '爆炸之星',
    'Tricky Paradise': '整蛊天堂',
    'Haunted Gardens': '闹鬼花园',
    'Whispering Gardens': '耳语花园',
    'Abandoned Gardens': '被遗弃的花园',
    'Bewitched Gardens': '迷人的花园',
    'Terrible Gardens': '可怕的花园',
    'Dark Gardens': '黑暗花园',
    'Blighted Gardens': '枯萎的花园',
    'Sacred Gardens': '神圣花园',
    'Weird Gardens': '怪异的花园',
    'Steamy Gardens': '蒸汽花园',
    'Red Gardens': '红色花园',
    'Calm Gardens': '平静的花园',
    'Evil Gardens': '邪恶花园',
    'Dry Gardens': '干燥的花园',
    'Enchanted Gardens': '魔法花园',
    'Light Gardens': '光明花园',
    'Dirty Gardens': '肮脏的花园',
    'Fiery Gardens': '火热的花园',
    'Deadly Void': '致命的虚空',
    'Heinous Void': '令人发指的虚空',
    'Heinous Pit': '令人发指的坑',
    'Heinous Nightmare': '令人发指的梦魇',
    'Heinous Descent': '令人发指的血统',
    'Poisonous Void': '有毒虚空',
    'Poisonous Pit': '毒坑',
    'Poisonous Nightmare': '有毒的噩梦',
    'Poisonous Descent': '有毒的血统',
    'Deadly Pit': '致命的坑',
    'Deadly Descent': '致命的血统',
    'Deadly Void': '致命的虚空',
    'Deadly Nightmare': '致命的梦魇',
    'Destructive Descent': '破坏性的血统',
    'Destructive Nightmare': '破坏性的噩梦',
    'Destructive Void': '破坏性虚空',
    'Destructive Pit': '破坏性虚坑',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //自动脚本2汉化文本
    'Auto Start Daily': '自动开始日常',
    'Damage to Health Ratio': '健康伤害比率',
    'Finish Challenge2': '完成挑战2',
    'Manual Gather/Build / Auto Gather/Build': '手动收集/建造 / 自动收集/建造',
    'Toggle Automapping2': '切换自动地图2',
    'Auto Allocate Off / Auto Allocate On / Dump into Looting II': '自动分配关闭 / 自动分配开启 / 进入掠夺II',
    'Amalgamator Goal': '合并者目标',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //阻止页面打印
    '平均': '平均',
    '导入': '导入',
    '欢迎': '欢迎',
    '导出': '导出',
    '自动战斗': '自动战斗',
    '战斗': '战斗',
    '世界信息': '世界信息',
    '购买最大': '购买最大',
    '攻击阵型': '攻击阵型',
    '防守阵型': '防守阵型',
    '肉山阵型': '肉山阵型',
    '无编队': '无编队',
    '退出地图': '退出地图',
    '重复10次': '重复10次',
    '装备优先': '装备优先',
    '脆皮信息': '脆皮信息',
    '暂停游戏': '暂停游戏',
    '区域内无地图': '区域内无地图',
    '退出世界': '退出世界',
    '尖塔地图': '尖塔地图',
    '重复所有': '重复所有',
    '一个虚空地图': '一个虚空地图',
    '仿生仙境 XIX': '仿生仙境 XIX',
    '仿生仙境 XX': '仿生仙境 XX',
    '仿生仙境 XXI': '仿生仙境 XXI',
    '仿生仙境 VII': '仿生仙境 VII',
    '仿生仙境 VIII': '仿生仙境 VIII',
    '仿生仙境 IX': '仿生仙境 IX',
    '导入': '导入',
    '仿生仙境 VI': '仿生仙境 VI',
    '仿生仙境 X': '仿生仙境 X',

}

//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
var cnRegReplace = new Map([
	[/^requires (\d+) more research points$/, '需要$1个研究点'],
	[/^(\d+) Royal points$/, '$1 皇家点数'],
	[/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
	[/^Usages: (\d+)\/$/, '用途：$1\/'],
	[/^workers: (\d+)\/$/, '工人：$1\/'],

]);

//2.采集新词
//20190320@JAR

var cnItem = function () {

    //传参是否非空字串
    if (!arguments[0]) return;

    //检验传参是否对象
    let text = arguments[0],
        s = '';
    if (typeof (text) != "string")
        return text;
    else
        s = arguments[0].charCodeAt();

    //检验传参是否英文
    // if (
    //     s < 65 || (s > 90 && s < 97) || (s > 122)
    //
    // ) return text;

    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix = cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix];
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0];
            text = text.substr(0, text.length - text_reg_exclude_postfix.length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return arguments[0];
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (
            text == i || text == cnItems[i] &&
            cnItems[i] != ''
        )
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : arguments[0]
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return arguments[0];
    }

    if (cnItems._OTHER_.length < 500) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function (a, b) {
                return a.localeCompare(b)
            }
        );
    }

    /*
        //开启生词打印
        //console.log(
            '有需要汉化的英文：', text
        );
    */

    //返回生词字串
    return arguments[0];
};

transTaskMgr = {
    tasks: [],
    addTask: function (node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function () {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "TEXTAREA" && subnode.innerHTML && subnode.innerText) {
                if (subnode.innerHTML === subnode.innerText) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function () {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function (e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.innerHTML && mutation.target.innerText && mutation.target.innerHTML === mutation.target.innerText) {
                mutation.target.innerText = cnItem(mutation.target.innerText);
            } else if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "TEXTAREA" && node.innerHTML && node.innerText) {
                        if (node.innerHTML === node.innerText) {
                            node.innerText = cnItem(node.innerText);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
}();
