//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //1.1.待归类
    'sewer': '下水道',
    'refinery': '炼油厂',
    'Market': '市场',
    'Square': '广场',
    'Hospital': '医院',
    'Tent': '帐篷',
    'Campfire': '营火',
    'campfire': '营火',
    'Campfires': '营火',
    'Generator': '发电机',
    'Injury': '受伤',
    'storage': '存储',
    'NE': '右上方',
    'north': '上方',
    'SW': '左下方',
    'Trading post': '贸易站',
    'Inn': '旅馆',
    'Lights': '灯火',
    'Improvement': '改良',
    'Research center': '研究中心',
    'Tower block': '塔楼',
    'Smithy': '铁匠铺',
    'Cement mill': '水泥厂',
    'Apothecary shop': '药剂师商店',
    'Follower': '随从',
    'water': '水',
    'food': '食物',
    'metal': '金属',
    'rope': '绳索',
    'herbs': '草药',
    'fuel': '燃料',
    'medicine': '药品',
    'tools': '工具',
    'concrete': '混凝土',
    'Workers': '工人',
    'Collectors': '收集器',
    'collectors': '收集器',
    'collector': '收集器',
    'calendar': '日历',
    'Trappers': '猎人',
    'Scavengers': '搜索者',
    'Rope-makers': '制绳者',
    'Chemists': '化学家',
    'Snail farms': '蜗牛农场',
    'Light': '光源',
    'Bag': '背包',
    'Exploration': '探查',
    'Ingredient': '材料',
    'UniqueEquipment': '特殊装备',
    'Follower': '随从',
    'Artefact': '人工制品',
    'Strained ankle': '扭伤脚踝',
    'Burn': '烧伤',
    'Broken rib': '肋骨骨折',
    'Base': '基础',
    'Sunglasses': '太阳镜',
    'Camp': '营地',
    'Being in camp': '在营地',
    'Population': '人口',
    'blueprint': '蓝图',
    'Libraries': '图书馆',
    'stamina': '耐力',
    'lose items': '丢失物品',
    'lose an item': '丢失一件物品',
    'Matches': '火柴',
    'matches': '火柴',
    'Rubber bands': '橡皮筋',
    'rubber bands': '橡皮筋',
    'Spider silk': '蛛丝',
    'spider silk': '蛛丝',
    'Lock pick': '开锁器',
    'Basic First Aid Kit': '基础急救箱',
    'Full First Aid Kit': '完整急救包',
    'Glowstick': '荧光棒',
    'Map': '地图',
    'Starchart': '星图',
    'Pamphlet': '小册子',
    'Seashell': '海贝',
    'Temple key': '神殿钥匙',
    'Volcanic rock': '火山岩',
    'Pearl': '珍珠',
    'Fountain pen': '钢笔',
    "Scientist's notebook": '科学家笔记',
    'ID Chip': 'ID芯片',
    'Canned tuna': '金枪鱼罐头',
    'Leather pouch': '皮革袋',
    'Round stone': '圆石',
    'Charred seed': '烧焦的种子',
    'Runestone': '符石',
    'Automatic luggage': '自动化皮箱',
    'Scavenger bag': '搜索者包',
    "Hicker's rucksack": '乡巴佬的帆布包',
    'Jumbo backpack': '特大背包',
    'Basic backpack': '基础背包',
    'Plastic bag': '塑料背包',
    'Lantern': '灯笼',
    'Electric light': '电灯',
    'Ghost light': '幽灵灯',
    'Mittens': '连指手套',
    'max vision': '最大视野',
    'attack': '攻击力',
    'bag size': '背包容量',
    'defence': '防御力',
    'warmth': '保暖度',
    'radiation protection': '辐射防护',
    'poison protection': '毒物防护',
    'sunblindness protection': '遮阳防护',
    'light': '光源',
    'bag': '背包',
    'weapon': '武器',
    'armor': '盔甲',
    'shirt': '衬衫',
    'legs': '腿部',
    'head': '头部',
    'hands': '手部',
    'shoes': '脚部',
    'Shiv': '小刀',
    'Spear': '矛',
    'Crossbow': '弩',
    'Pistol': '手枪',
    'Revolver': '左轮手枪',
    'Custom SMG': 'SMG冲锋枪',
    'Improvised bazooka': '简易火箭筒',
    'Warm Coat': '暖和的大衣',
    'Biker jacket': '机车夹克',
    'Scrap metal armor': '废金属护甲',
    'Kevlar vest': '防弹衣',
    'Riot police vest': '防暴警察背心',
    'Exoskeleton': '外骨骼',
    'Tattered shirt': '破旧的衬衫',
    'Factory uniform shirt': '工厂制服衬衫',
    'Guard shirt': '守卫衬衫',
    'Protective shirt': '防护衫',
    "Scavenger's raincoat": '搜索者雨衣',
    'Ragged pants': '破旧的裤子',
    'Factory uniform pants': '工厂制服裤子',
    'Guard uniform pants': '警卫制服裤',
    'Padded pants': '衬裤',
    'Long underwear': '秋裤',
    'Sunglasses': '墨镜',
    'Wollen hat': '羊毛帽',
    'Pollution mask': '防污染面具',
    'Scrap metal helmet': '废金属头盔',
    'Gas mask': '防毒面具',
    "Explorer's helmet": '探索者之盔',
    'Work gloves': '劳动手套',
    'Quality gloves': '高质量手套',
    "Scavenger's gloves": '搜索者手套',
    'Improvised flip-flops': '简易人字拖',
    'Worn trainers': '运动鞋',
    'Hiking boots': '登山鞋',
    'movement cost': '移动消耗',
    'health': '健康',
    'Hut': '棚屋',
    'Library': '图书馆',
    'Fortification': '要塞',
    'Moss garden': '苔藓花园',
    'rumours': '传闻',
    'urban pests': '城市害虫',
    'aggressive animals': '侵略性动物',
    'bandits': '强盗',
    'bots': '机器人',
    'pack': '一团',
    'mob': '乌合之众',
    'patrolled by': '巡逻着',
    'guarded by': '守护着',
    'infested with': '到处都是',
    'covered in': '覆盖着',
    'cleared': '已清除',
    'disabled': '已禁用',
    'killed': '已杀死',
    'driven away': '已赶走',
    'pests': '害虫',
    'stairwell': '楼梯井',
    'south': '下方',
    'north': '上方',
    'west': '左方',
    'east': '右方',
    'Gang': '怪物群',
    'gang': '怪物群',
    'W': '左',
    'E': '右',
    'N': '上',
    'S': '下',
    'NE': '右上',
    'NW': '左上',
    'SW': '左下',
    'SE': '右下',
    'Hunger': '饥饿',
    'Thirst': '口渴',
    'Healthy': '健康',
    'Augmented': '增强',
    'Radiation sickness': '辐射病',
    'Poisoned': '中毒',
    'Encumbered': '负重',
    'Cold': '寒冷',
    'Export': '导出',
    'Export / import save': '导出/导入存档',
    'empty': '空',
    'Enemy name & strength': '敌人名称及兵力',
    'Raid!': '袭击！',
    'Other items': '其它物品',
    'Leave all': '全部留下',
    'Items': '物品',
    'Load': '加载',
    'Locations': '位置',
    'location': '位置',
    'Vision ': '视野',
    'vision': '视野',
    'Nothing here': '这里什么都没有',
    'Outside': '野外',
    'Projects': '工程',
    'Rename': '重命名',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //怪物
    'huge rat': '大老鼠',
    'huge rats': '大老鼠',
    'giant centipede': '巨型蜈蚣',
    'poisonous centipede': '毒蜈蚣',
    'radioactive cockroach': '辐射蟑螂',
    'cave bat': '洞穴蝙蝠',
    'ghost bat': '幽灵蝙蝠',
    'vampire bat': '吸血蝙蝠',
    'poisonous spider': '毒蜘蛛',
    'gigantic spider': '巨蜘蛛',
    'ratsnake': '鼠蛇',
    'albino salamander': '白化蜥蜴',
    'fire salamander': '火蜥蜴',
    'duskboar': '幽暗野猪',
    'rusted guard bot': '生锈的守卫机器人',
    'ancient guard bot': '远古守卫机器人',
    'robot from a forgotten war': '被遗忘战争中的机器人',
    'drone from a forgotten war': '被遗忘战争中的无人机',
    'malfunctioning fire door': '故障的防火门',
    'antagonistic fire door': '敌对的防火门',
    'territorial sewer varanid': '区域下水道巨蜥',
    'predatory sewer varanid': '掠夺下水道巨蜥',
    'haywire guard bot 1': '故障守卫机器人1号',
    'haywire guard bot 2': '故障守卫机器人2号',
    'haywire guard bot 3': '故障守卫机器人3号',
    'wasp': '黄蜂',
    'bee': '蜜蜂',
    'spirit of earth': '大地之灵',
    'spirit of wind': '微风之灵',
    'spirit of fire': '火焰之灵',
    'spirit of sun': '太阳之灵',
    'vengeful dryad': '复仇森林女神',
    'vampire': '吸血鬼',
    'ape': '猿',
    'bear': '熊',
    'drove of boars': '一群野猪',
    'security bot': '安保机器人',
    'rabid dog': '狂犬',
    'leaking gas pipe': '泄漏的煤气管',
    'mugger': '掠夺者',
    'doomsayer': '灾难预言者',
    'armed gangster': '武装歹徒',
    'sector emergency system': '应急防御系统',
    'thorny bush': '尖刺灌木',
    'overgrown nettle': '巨型荨麻',
    'hawk': '鹰',
    'a group of seagulls': '一群海鸥',
    'scorpion': '蝎子',
    'territorial magpie': '喜鹊',
    'great black pelican': '鹈鹕',
    'swarm of pidgeons': '大群鸽子',
    'agitated murder of crows': '一群发狂的乌鸦',
    'aggressive raccoon': '发狂的浣熊',
    'escaped pet boa': '逃出的宠物蟒',
    'military bot': '军用机器人',
    'escaped zoo panther': '逃出动物园的豹',
    'injured zoo panther': '受伤的动物园豹',
    //按钮文字
    'Rest': '休息',
    'Storage': '仓库',
    'Snail farm': '蜗牛农场',
    'Shrine': '神社',
    'Barracks': '军营',
    'Fortifications': '要塞',
    'Sit down': '坐下',
    'Aqueduct': '沟渠',
    'Tent cover': '帐篷盖',
    'Treatment': '治疗',
    'Augment': '增加',
    'Recruit': '招募',
    'Radio tower': '广播塔',
    'Caravan stable': '商队马厩',
    'Go': '出发',
    'Enter camp': '进入营地',
    'Back to camp': '返回营地',
    'Move up': '向上',
    'Move down': '向下',
    'Despair': '绝望',
    'Scavenge': '清理',
    'Scout': '侦察',
    'scout': '侦察',
    'Investigate': '调查',
    'Scout workshop': '侦察车间',
    'Refill water': '补给水',
    'Bucket': '水桶',
    'Collect': '收集',
    'Trap': '陷阱',
    'Launch': '开始',
    'Flee': '逃离',
    'Fight': '战斗',
    'Cancel': '取消',
    'Trade': '贸易',
    'Confirm': '确认',
    'Continue': '继续',
    'Take all': '全部拿走',
    '': '',
    //Header
    'dark   square': '黑暗的广场',
    '': '',
    '': '',
    //描述
    'Set up camp.': '建立营地。',
    'Recover stamina.': '恢复体力。',
    'A place for 4 people to stay.': '可以待四个人的地方。',
    'Houses 10 people.': '可以待10个人',
    'Increases resource storage.': '增加资源存储',
    'Increases reputation bonus from housing (0.3% per house)': '增加增加来自房子的声望奖励（每个房子 +0.3%）',
    'Produces food': '生产食物',
    'Workspace for toolsmiths.': '工匠的工作场所',
    'Accumulate and store more evidence.': '积累和储存更多的线索。',
    'Allows 10 soldiers.': '允许10名士兵。',
    'Increases rumour generation and unlocks upgrades.': '增加传言生成和解锁升级。',
    'Collect rumours from the population.': '从人群中收集传言。',
    'Keep the darkness at bay for good.': '永远远离黑暗。',
    'Water infrastructure to improve collecting efficiency.': '改善供水基础设施的收集效率。',
    'Enables healing injuries.': '启用伤痛治愈。',
    'Heal injuries.': '医治受伤。',
    'Enables foreign traders to visit.': '启用外国商人来访。',
    'Increases rumours and enables recruitment.': '增加传言并招募人才。',
    'Recruit followers.': '招募追随者。',
    'Connect camps to a trade network.': '将营地连接到贸易网络。',
    'Space to set up a trading caravan.': '建立贸易大篷车的空间。',
    'A place to relax and socialize.': '一个放松和社交的地方。',
    'A dash of beauty in the concrete desert.': '水泥沙漠里的一丝美丽。',
    'Venture out into the corridors.': '外出到走廊。',
    'Rest and manage camp.': '休息以及管理营地。',
    'Shortcut back to the nearest camp.': '抄近路回最近的营地。',
    'Sleep rough and regain a bit of stamina.': '睡个好觉，恢复一点体力。',
    'Give up. Stop moving. Rest.': '放弃。停止移动。休息。',
    'Look for resources.': '寻找资源。',
    'Scout the area for evidence.': '在这一地区寻找线索。',
    'Scout the workshop to see if it can be used.': '检查车间，看看是否能用。',
    'Get water.': '取水。',
    'Accumulates water.': '积累水。',
    'Collect accumulated water.': '收集积累的水',
    'Accumulates food.': '积累食物。',
    'Collect accumulated food.': '收集积累的食物。',
    'A place to rest.': '一个休息的地方。',
    'Leave this planet and launch for the great unknown.': '离开这个星球，前往未知的地方。',
    'Abandon what you were doing and run.': '放弃你正在做的，逃跑吧。',
    'Confirm trade.': '确认交易。',
    'item_res_medicine': 'item_res_medicine',
    'Clinic': '诊所',
    'Camp defences: +6': '营地防御 +6',
    'Camp defences: +10': '营地防御 +10',
    'dark crumbling  square': '暗坠广场',
    'crumbling slum square': '摇摇欲坠的贫民窟广场',
    'Went scavenging. ': '去清理。',
    'Went scavenging.': '去清理。',
    'scavenge': '清理',
    'Rummaged in the dark. ': '在黑暗中翻遍了。',
    'Rummaged in the dark.': '在黑暗中翻遍了。',
    'A crude single-shot pistol, like a hand-held miniature cannon.': '一把粗制的单发手枪，就像一把手持式微型加农炮。',
    'A deadly ranged weapon consisting of a horizontal limb assembly mounted on a stock that shoots projectiles.': '一种致命的远程武器，由一个水平肢体组件组成，安装在射击射弹的枪托上。',
    'A huge backpack with plenty of space.': '一个巨大的背包，有充足的空间。',
    'A more sophisticated handgun that allows several shots before reloading.': '一种更复杂的手枪，可在重新装弹前进行多次射击。',
    'A more spacious bag with lots of pockets.': '一个更宽敞的包，有很多口袋。',
    'Advanced light for serious travellers.': '适合认真旅行者的高级灯。',
    'Based on the old Surface Guard uniform with additional environmental proection.': '在旧的表面防护制服的基础上增加了额外的环境保护措施。',
    'Basic protection for hands.': '对于手的基本防护。',
    'Feeble light for basic survival in the dark undercorridors.': '在黑暗的地下走廊里，为了基本的生存而发出微弱的光。',
    'Gloves that protect from almost all environmental hazards.': '防护几乎所有环境危害的手套。',
    'Headgear designed specifically for scavenging in the City.': '专为城市清除而设计的头盔。',
    'Heal all injuries on the go.': '在旅途中治愈所有伤痛。',
    'Heal light injuries on the go.': '在旅途中治疗轻伤。',
    'Heavy, but worth it.': '很重，但值得。',
    'Improvised sharp poking implement.': '锋利的戳具。',
    'It may be made from scrap metal but it is still a serious weapon.': '它可能由废金属制成，但它仍然是一种严重的武器。',
    'It\'s not fancy, but allows one to carry around more stuff than their hands and pockets can hold.': '它不是花哨的，但允许一个人携带比他们的手和口袋更多的东西。',
    'Looks official, but not particularly protective.': '看起来很正式，但不是特别保护。',
    'No scavenger ever regretted having good gloves.': '没有一个清道夫曾经后悔戴着这个好手套。',
    'Nothing keeps hands warm like fluffy mittens.': '没有什么比毛茸茸的手套更保暖的了。',
    'Nothing keeps you warm like long underwear.': '没有什么比长内裤更保暖的了。',
    'Old-fashioned but reliable weapon.': '老式但可靠的武器。',
    'Perfect apparel for the post-apocalyptic knight.': '完美的后末日骑士服装。',
    'Powerful but heavy and somewhat unreliable construction of pipes, reclaimed weapon parts and improvised ammunition.': '强大但沉重，有些不可靠的管道建设，回收的武器部件和临时弹药。',
    'Protects a scavenger\'s feet from sharp things that might be lying around.': '保护清理者的脚不受周围尖锐物体的伤害。',
    'Protects from bites and scratches.': '防止咬伤和划伤。',
    'Something against the chill.': '对抗寒冷的东西。',
    'Something that\'s actually produced with the aim of keeping one safe.': '实际上是为了保护一个人的安全而生产的东西。',
    'Specifically made for keeping travellers warm and safe.': '专为旅客保暖和安全而设计。',
    'Temporary light. Can be used as a distraction.': '临时的光。可以用来分散注意力。',
    'The best protection an explorer can hope for.': '这是探险家能得到的最好的保护。',
    'Useful tool when exploring and scouting.': '探索和侦察时的有效工具。',
    'Warm basic headwear.': '温暖的基本的头饰。',
    'abundant': '丰富',
    'scarce': '稀缺',
    'common': '普通',
    'cleared for use': '可以使用',
    'not cleared': '未清理',
    'Determines maximum stamina': '决定最大耐力',
    'Required for exploration': '探索需求',
    'Makes exploration safer': '让探索更安全',
    'Helps you navigate the City.': '帮助您导航城市。',
    'There are still many unvisited streets on this level.': '在这一层仍有许多还未到过的街道。',
    'This level has been thoroughly explored.': '这一层的地图已被完全绘制出来了。所有的地点都已经被检查过了。',
    'This level has been mapped, but there are a few unexplored locations left.': '这一层的地图已被完全绘制出来了。还有几处还未探查过的地方。',
    'There are still unscouted streets on this level.': '在这一层仍有还未侦察过的街道。',
    'There are still some unvisited streets on this level.': '在这一层仍有一些还未到过的街道。',
    'A wide street or corridor. It\'s hard to find anything in the vast darkness.': '宽阔的街道或走廊。 在浩瀚的黑暗中很难找到任何东西。',
    'A wide street or corridor that doesn\'t seem to be in very good repair. It\'s hard to find anything in the vast darkness.': '宽阔的街道或走廊似乎没有很好的维修。 在浩瀚的黑暗中很难找到任何东西。',
    'A rare empty space inside the City; there is no floor or walls, no buildings, nothing. Only vast empty darkness.': '城内罕见的空地; 没有地板或墙壁，没有建筑物，没有。 只有浩瀚空虚的黑暗。',
    'A street or corridor with an abandoned air. Details fade in the darkness.': '有废弃空气的街道或走廊。 细节在黑暗中消失。',
    'A street or corridor with several buildings. In the darkness it\'s hard to say what they are.': '有几座建筑的街道或走廊。 在黑暗中很难说它们是什么。',
    'A dense corridor with barely enough space to walk and plenty of sharp edges, uneven paths and crumbled walls. You feel your way in the darkness.': '一条密集的走廊，几乎没有足够的空间可以走动，还有许多锋利的边缘，不平坦的小径和破碎的墙壁。 你在黑暗中感受到自己的方式。',
    'A dense corridor with barely enough space to walk. You feel your way in the darkness.': '一条密集的走廊，几乎没有足够的空间走路。 你在黑暗中感受到自己的方式。',
    'Do you want to restart the game? Your progress will be lost.': '你想重新开始游戏吗？ 你当前的游戏进度将会丢失。',
    'Confirmation': '信息确认',
    'abandoned slum square': '废弃的贫民窟广场',
    'A wide square surrounded by crumbling make-shift residential towers that don\'t seem to have ever been connected to the grid.': '一个宽阔的广场，周围是摇摇欲坠的临时转换住宅塔楼，这些塔楼似乎从未与电网连接过。',
    'Scouted the area.': '侦查这个区域。',
    'Wool hat': '羊毛帽',
    'Lockpick': '撬锁钳',
    'Full first aid kit': '全套急救箱',
    'Basic first aid kit': '基本急救箱',
    'ok': '确定',
    'Your throat is dry.': '你的喉咙很干。',
    'Getting tired. Should find a place to rest soon.': '累了。你得找个地方休息一下。',
    'Made a bucket. It will collect water.': '做了一个水桶。 它可以收集水。',
    'Made a Lantern. Light will make scavenging safer.': '做了一个灯笼。 光会使清理更安全。',
    'No longer thirsty.': '不再口渴了。',
    'Built a camp.': '建造一个营地。',
    'Resting': '休息',
    'Bag capacity': '背包容量',
    'Camp storage': '营地存储上限',
    'Carry capacity': '携带能力',
    'Tribe storage': '部落存储',
    'Out of food!': '没食物了！',
    'Out of water!': '没水了！',
    'Left camp. The darkness of the city envelops you.': '离开营地。城市的黑暗笼罩着你。',
    'Built a trap. It will catch food.': '建造了一个陷阱。它可以捕捉到食物。',
    'Getting tired. Should head back to camp soon.': '你感到累了。 应该尽快回到营地。',
    'resting': '休息',
    'Barely counts for clothing, but for now it\'ll have to do.': '几乎不算衣服，但现在只能这样了。',
    'Fight pests (右)': '抗击害虫(右)',
    'Area already scouted.': '区域已经被侦察过。',
    'Area not scouted yet.': '区域还没有侦察过。',
    'No collectable food.': '没有可收集的食物。',
    'No collectable water.': '没有可收集的水。',
    'The world fades. You wake up with no memory how you found your way back.': '世界消失了。当你醒来时，却不记得你是如何找到回来的路的。',
    'Built a campfire. Here, ideas are shared and discussed.': '建立了一个篝火。在这里，分享和讨论想法。',
    'Already fully rested.': '已经完全休息好了。',
    'Apothecary shop required: 2x house': '药店要求:2x 房子',
    'Aqueducts': '输水管道',
    'Armour': '盔甲',
    'Augmented Clothing 2': '增强型服装2',
    'Automatic pistols': '自动手枪',
    'Bag-making 1': '制袋1',
    'Bag-making 2': '制袋2',
    'Blocked by a fight.': '被一场战斗挡住了。',
    'Campfire already exists': '营火已经存在',
    'Can\'t do this while: Injury': '现在不能这么做:受伤',
    'Caravan Stable required': '需要大篷车马厩',
    'Cement mill required: 2x house': '水泥磨机要求:2x 房子',
    'Chemistry': '化学',
    'Concrete Fortification required': '需要混凝土加固',
    'Crafting': '工艺',
    'Field medicine': '野战医疗',
    'First Aid': '急救',
    'Fortification required': '需要加固',
    'Guard Uniform': '警卫制服',
    'Hospitality': '热情好客',
    'Improvement required': '需要改进',
    'Library required': '需要图书馆',
    'Market required': '需要市场',
    'Metal working 1': '金属加工1',
    'Metal working 2': '金属加工2',
    'Moss garden required': '需要苔藓花园',
    'No passage.': '没有通道。',
    'Research center required': '需要研究中心',
    'Revolvers': '左轮手枪',
    'Sewing': '缝纫',
    'Smithy required: 2x house': '铁匠铺要求:2x 房子',
    'Square required: 2x storage': '广场需要:2x 仓库',
    'Sunlight required.': '需要阳光。',
    'Synthetic Fibers': '合成纤维',
    'Tent already exists': '帐篷已经存在',
    'Textile Arts': '纺织艺术',
    'Tower block required: 3x house': '塔楼需要:3x 房子',
    'Upgrade required: ': '需要升级:',
    'Urban Heliculture': '城市养殖业',
    'Vest plating': '背心电镀',
    'Water purification': '水净化',
    'Using scavenged fiber and cloth to make rope, a useful building and crafting material.': '利用回收的纤维和布料制作绳索，是一种有用的建筑和工艺材料。',
    'The varied skill of making useful things out of whatever happens to be available': '使有用的东西变得有用的各种各样的技能',
    'Rope-making': '制绳',
    'rope-maker': '制绳工',
    'Pest control': '虫害控制',
    'Locked stats.': '锁定状态。',
    'Engineering': '工程学',
    'Elevator mechanics': '电梯机械学',
    'Education': '教育',
    'Currency': '货币',
    'Compass': '指南针',
    'Cement': '水泥',
    'Bridge-building': '桥梁建设',
    'Blueprint required.': '需要蓝图。',
    'Bag is full.': '包满了。',
    'Blocked. ': '路被挡住了。',
    'Clinic required': '需要诊所',
    'Everything already selected.': '所有物品都已经选中了。',
    'Generator required': '需要发电机',
    'Hut required': '需要小屋',
    'Nothing to collect': '没有东西可收集',
    'Snail farm required': '需要蜗牛养殖场',
    'Square required': '需要广场',
    'Can\'t carry that much stuff.': '带不动更多东西了。',
    'The darkness is like a wall.': '黑暗就像一堵墙。',
    'Fell through a rotten floor. Lost 1 lantern.': '从腐烂的地板上摔了下来。失去了1灯笼。',
    'no change': '无改变',
    'Sat at the campfire to exchange stories about the corridors.': '坐在篝火旁交换有关走廊的故事。',
    'discussing': '讨论',
    'A stranger shows up.': '一个陌生人出现了。',
    'evidence': '线索',
    'Sat at the campfire to exchange stories, but there was nothing new.': '坐在篝火旁交换故事，但没有什么新东西。',
    'Campfire required': '需要篝火',
    'No new rumours at the moment.': '目前没有新的传闻。',
    'You are alone in a massive dark corridor, far below sunlight.': '你独自在一个巨大的黑暗走廊里，远离阳光。',
    'Your stomach is grumbling.': '你的肚子在咕噜咕噜叫。',
    'Built a storage.': '建了一个存储空间。',
    'Made a Shiv.': '制作了了一把小刀。',
    'Researched Crafting.': '研究工艺。',
    'The art of crafting durable bags.': '制作耐用背包的艺术。',
    'Made an Improvised flip-flops.': '做了一个临时的人字拖。',
    'Made a Warm Coat.': '做了一件暖和的外套。',
    'Used for crafting.': '用于工艺制作。',
    'Made a Lockpick.': '制作了一个撬锁工具。',
    'Combine': '组合',
    'Clinic already exists': '诊所已经存在',
    'Built a clinic.': '建造一个诊所。',
    'Tower blocks': '塔楼',
    'recovering': '恢复中',
    'The world fades. You wake up back in camp.': '世界消失了。你在营地醒来。',
    'Exhausted and hungry, you sit to rest. Your consciousness fades.<br/>You wake up back in camp. Some of the scavengers found you and brought you home.': '又累又饿，你坐下来休息。你的意识消失。<br/>你在营地醒来。一些搜索者发现了你并把你带回家。',
    'repair': '修复',
    'Researched Building projects.': '研究建设项目。',
    'Area clear.': '区域已清理。',
    'Managing large building projects and building structures that allow passage to different levels.': '管理大型建筑项目和允许不同楼层通行的建筑结构。',
    'scout locale u': '侦查区域U',
    'Staircase': '楼梯',
    'Staircase Down': '向下的楼梯',
    'Staircase Up': '向上的楼梯',
    'Staircase Down already exists': '向下的楼梯已经存在',
    'Toolsmiths': '工匠',
    'CD': 'CD',
    'Built a smithy.': '建造了一个铁匠铺。',
    'Researched Metal working 1.': '研究金属加工1。',
    'Meager protection against the effects of polluted air.': '微薄的保护，防止污染空气的影响。',
    'Bold political leaflet printed on thick paper urging residents of the \'sewers\' to rebel against segregation.': '大胆的政治传单印在厚厚的纸上，敦促“下水道”的居民反抗种族隔离。',
    'An old circular data storage with the word \'backup\' written on it. Without an electric computing machine, it\'s impossible to stay if it is still readable.': '一个旧的循环数据存储，上面写着“备份”一词。 没有电动计算机，如果它仍然可读，则不可能留下来。',
    'Reclaiming tower blocks that can house more people.': '回收塔块，可以容纳更多的人。',
    '': '',
    '': '',
    '': '',
    //1.2.地图
    'abandoned residential street': '被遗弃的住宅街',
    'abandoned maintenance street': '放弃维护的街道',
    'crumbling commercial square': '摇摇欲坠的商业广场',
    'abandoned industrial street': '废弃的工业街',
    'crumbling maintenance street': '摇摇欲坠的维护街道',
    'crumbling slum street': '摇摇欲坠的贫民窟街',
    'abandoned slum street': '被遗弃的贫民窟街',
    'crumbling maintenance square': '崩塌的维修广场',
    'dark crumbling  street': '黑暗破败的街道',
    'A quiet residential area lined with slowly decaying apartment towers.': '一个安静的住宅区，两旁有缓缓腐烂的公寓楼。',
    'infested with urban pests': '充斥着城市害虫',
    'A narrow slum street surrounded (and in some parts, covered) by make-shift dwellings that have been adandoned for some time.': '一条狭窄的贫民窟街道，被临时搭建的住房所包围(有些地方甚至被盖住)。',
    'group of pests': '一群害虫',
    'Clear the enemies blocking passage.': '清除堵塞通道的敌人。',
    'A narrow street lined by decommissioned control units for City services like water, electricity, air filtering and robotics.': '一条狭窄的街道，由退役的控制单元排列，用于城市服务，如水，电，空气过滤和机器人。',
    'A narrow slum street surrounded (and in some parts, covered) by make-shift dwellings.': '一条狭窄的贫民窟街道被移民住宅包围（在某些地方，被覆盖）。',
    'crumbling residential street': '摇摇欲坠的住宅街道',
    'abandoned commercial street': '被遗弃的商业街',
    'A former shopping street lined with deserted shops and artisan\'s workshops.': '这是一条前购物街，两旁都是空旷的商店和工匠的工作室。',
    'Too hungry to go on.': '饿得走不动了。',
    'Exhaustion': '虚脱',
    'Exhausted and hungry, you sit to rest. Your consciousness fades.<br/>When you wake up, you find yourself back in camp.': '又累又饿，你坐下来休息。你的意识消失。<br/>当你醒来时，你发现自己又回到了营地。',
    'infested with huge rats': '有巨大的老鼠出没',
    'A mostly empty square with a control room in the middle and old cable systems criss-crossing the low ceiling.': '一个几乎空无一人的广场，中间有一间控制室，低矮的天花板上纵横交错着古老的电缆系统。',
    'There are some make-shift shacks against the walls here, but they have not been repaired in a long time.': '这里有一些靠墙的临时棚屋，但它们已经很长时间没有修理了。',
    'group': '成群',
    'The road is clear.': '道路已清理。',
    'Music': '音乐',
    'Built a hut. People will come if they hear about the camp.': '建立了一个小屋。如果人们听说了营地的事，他们就会来的。',
    'A crumbling street lined with what were once some kind of apartments.': '一条摇摇欲坠的街道两旁，曾经是某种公寓。',
    'An inhabitant packs their belongings and leaves.': '一个居民收拾行李离开了。',
    'Quiet sewer': '安静的下水道',
    'lock pick': '开锁',
    'intimidating': '令人生畏的',
    'Scout for additional resources and evidence.': '寻找额外的资源和线索。',
    'Scouted the area. There is a sewer here that seems worth investigating.': '搜索了这个区域。这里有个下水道似乎值得调查一下。',
    'Scouted the area.<br/>There is a sewer here that seems worth investigating.': '搜索了这个区域。<br/>这里有个下水道似乎值得调查一下。',
    'A low street surrounded by old factories and industrial buildings.': '一条被旧工厂和工业建筑包围的低矮街道。',
    'An abandoned market square lined with the remains of shops and empty, silent billboards.': '一个废弃的市场广场，两旁是残留的商店和空荡荡的、寂静的广告牌。',
    'Too thirsty to go on.': '太渴了，没法继续走了。',
    'Exhausted and thirsty, you sit to rest. Your consciousness fades.<br/>When you wake up, you find yourself back in camp.': '又累又渴，你坐下来休息。你的意识消失。<br/>当你醒来时，你发现自己又回到了营地。',
    'A quiet square surrounded by abandoned apartments.': '一个安静的广场，周围都是废弃的公寓。',
    'crumbling residential square': '摇摇欲坠的住宅广场',
    'crumbling industrial street': '摇摇欲坠的工业街',
    'A street lined with ruined factories and rats dashing to avoid light.': '街道两旁都是废弃的工厂，老鼠为了避光而四处逃窜。',
    'Got scared of the shadows and ran, leaving some items behind. Lost 1 tattered shirt.': '因为害怕阴影逃跑了，留下了一些东西。失去了1把小刀。',
    'Got scared of the shadows and ran, leaving some items behind. Lost 1 shiv.': '因为害怕阴影逃跑了，留下了一些东西。失去了1件破烂的衬衫。',
    'Scouted the area. 找到 一个 well. There is a sewer here that seems worth investigating.': '在该地区进行了侦察。 找到一个水井。 这里有一个下水道似乎值得调查。',
    'crumbling commercial street': '摇摇欲坠的商业街',
    'abandoned slum corridor': '废弃的贫民窟走廊',
    'An deserted corridor lined with the remains of shops and artisan\'s workshops.': '一条空无一人的走廊，两旁是商店和工匠作坊的遗迹。',
    'There used to be a few homes here, but they have not been repaired in a long time.': '这里过去有几所房子，但很长一段时间没有修理了。',
    'A filthy corridor packed so full of abandoned dark-dweller shacks that there is barely enough space to pass through.': '肮脏的走廊里挤满了被遗弃的黑暗居民的棚屋，几乎没有足够的空间通过。',
    'Too tired to go on.': '太累了无法继续走了。',
    'There has been a raid, but the camp was defended.': '我们遭到了突袭，但营地被守住了。',
    'Exhausted and helpless, you sit to rest. Your consciousness fades.<br/>When you wake up, you find yourself back in camp.': '疲惫无助，你坐下来休息。你的意识消失。<br/>当你醒来时，你发现自己又回到了营地。',
    'abandoned industrial corridor': '废弃的工业走廊',
    'Combine pieces to a blueprint.': '将碎片组合成蓝图。',
    'Found a piece of forgotten technology.': '发现了一块被遗忘的技术。',
    'Healed all injuries.': '治愈了所有伤病。',
    'Locale already scouted.': '区域已经侦察过了。',
    'No longer hungry.': '不再饥饿了。',
    'Perk required: Injury': '需求条件：受伤',
    'Some sort of a maintenance corridor between two vast factories with barely enough space to walk.': '两家工厂之间的维修走廊，几乎没有足够的空间行走。',
    'A crumbling street behind a maintenance center, the low ceiling criss-crossed by old wires and ducts.': '维修中心后面一条摇摇欲坠的街道，低矮的天花板上纵横交错着旧电线和管道。',
    'Increases with camp size and decreases with camp defences.': '随营地规模增加而增加，随营地防御而减少。',
    'Missing pieces.': '丢失的碎片。',
    'crumbling industrial square': '摇摇欲坠的工业广场',
    'A wide square with a ruined factory on one side and what looks like the remains of an old storehouse on the other.': '一个宽阔的广场，一边是一个废弃的工厂，另一边看起来像是一个旧仓库的遗迹。',
    'A mostly empty square with of the remains of old cable systems criss-crossing the low ceiling.': '一个几乎空无一人的广场，低矮的天花板上纵横交错着旧电缆系统的残骸。',
    'leaking water pipe': '漏水的水管',
    'Refilled water at the leaking water pipe.': '在漏水的水管处加满水。',
    'An quiet market square lined with the deserted shops and empty, silent billboards.': '一个安静的市场广场，两旁是空荡荡的商店和无声的广告牌。',
    'abandoned commercial square': '废弃的商业广场',
    'abandoned residential square': '废弃住宅广场',
    'If there was any sunlight, these would probably be handy.': '如果有阳光，这些可能会很方便。',
    'Staircase Up already exists': '向上的楼梯已经存在',
    'Found a park bench to sleep on. Barely feel rested.': '找了个公园的长椅睡觉。几乎没有休息的感觉。',
    'abandoned maintenance square': '废弃的维修广场',
    'building': '建造',
    'crumbling maintenance sector': '破碎维修区',
    'Got injured.': '受伤了。',
    'well': '水井',
    'Abandoned mall': '废弃的购物中心',
    'abandoned maintenance square': '废弃维修广场',
    'abandoned industrial square': '废弃的工业广场',
    'A wide square with a abandoned factory on one side and what looks like an old storehouse on the other.': '一个宽阔的广场，一边是一个废弃的工厂，另一边看起来像一个旧仓库。',
    'A rare empty space inside the City; there is no floor or walls, no buildings, nothing.': '城市内部罕见的空地;没有地板和墙壁，没有建筑物，什么都没有。',
    'area too cold': '这里太冷了',
    'Feeling warm again.': '感觉又暖和了。',
    'It\'s unbearably cold.': '冷得受不了。',
    'Safer here.': '这里更安全。',
    'crumbling slum sector': '摇摇欲坠的贫民区',
    'swarm': '成群',
    'giant centipedes': '巨大的蜈蚣',
    'Won\'t get far with low stamina.': '耐力过低，走不了多远。',
    'Trading post required': '需要贸易站',
    'Shortcut to the camp on this level.': '这一层通往营地的捷径。',
    'No news from other camps at the moment.': '目前没有其他营地的消息。',
    'There won\'t be much water left in the camp.': '我们营地里的水不多了。',
    'population decreasing': '人口减少',
    'No water': '没水了',
    'There won\'t be much water left in the camp.': '我们营地里的水不多了。',
    'New ways of making textiles.': '制造纺织品的新方法。',
    'Researched Textile Arts.': '纺织艺术已研究。',
    'Give your camp a new name': '给你的营地起个新名字',
    'Rename Camp': '重命名营地',
    'Built a hut.': '建了一个小屋。',
    'Researched Compass.': '研究指南针。',
    'A tool for reliable navigation in the vast city, enabling the establishment of basic trade routes.': '在广阔的城市中可靠导航的工具，可以建立基本的贸易路线。',
    'Built a trading post.': '建立了一个贸易站。',
    'Trading post already exists': '贸易站已经存在',
    'unassigned workers': '未分配的工人',
    'mall': '购物中心',
    'Are you sure you want to discard this item?': '您确定要丢弃这个物品吗?',
    'Built a square. The camp feels more like a town withing the City already.': '建立了一个广场。营地给人的感觉更像是一个与城市融为一体的小镇。',
    'People are anxious. They say the camp needs better defences.': '人们都很焦虑。他们说营地需要更好的防御。',
    'Poor defences': '防御能力很差',
    'radioactive cockroaches': '放射性蟑螂',
    'Square already exists': '广场已经存在',
    'This level seems eerily devoid of any signs of recent human activity.': '这一层似乎没有任何近期人类活动的迹象。',
    'Alternative source of food.': '替代食物来源。',
    'Requires undiscovered resources.': '需要未被发现的资源。',
    'Researched Urban Heliculture.': '研究蜗牛养殖。',
    'raid': '突袭',
    'Bone Crossing': '骨交叉',
    'Built a snail farm.': '建了一个蜗牛农场。',
    'Level population': '人口比率',
    'There is no more water.': '没有更多的水了。',
    'apothecary': '药剂师',
    'Common medium of exchange makes trading more efficient.': '共同的交换媒介使交易更有效率。',
    'Concentrated effort to build and store knowledge.': '集中精力建立和储存知识。',
    'Heal injuries on the go.': '在路上受了伤。',
    'Lights that defeat the darkness in the camp once and for all.': '一劳永逸地战胜黑暗的光明。',
    'Reclaiming tower blocks that can house more people.': '可以容纳更多人的高楼大厦。',
    'smith': '铁匠',
    'Smiths can turn scrap metal into tools and weapons.': '铁匠能把废金属变成工具和武器。',
    'Techniques for large-scale filtering and disinfecting drinking water that permit using more water sources.': '大规模过滤和消毒饮用水的技术，允许使用更多的水源。',
    'A trade caravan heads out.': '一支商队出发了。',
    'Old Waterworks': '旧水厂',
    'Repairing elevators that allow passage to new levels.': '修理电梯，让电梯可以前往新的层面。',
    'Crafting trader': '工艺商人',
    'Elevator Down (Repair)': '下行电梯（修复）',
    'Elevator Up (Repair)': '上行电梯（修复）',
    'Feeling better again.': '再次感觉好多了。',
    'Feeling nauseous.': '感到恶心。',
    'Fragile, yellow and light pink shell that must have been looted from a museum.': '易碎、黄色和淡粉色的贝壳，一定是从博物馆里抢来的。',
    'Puzzling piece of stone with an ancient rune on it.': '一块刻着古代符文的令人费解的石头。',
    'Traded with a caravan.': '和一支商队进行交易',
    'Built a tower block.': '建一座塔楼。',
    'Researched Tower blocks.': '研究塔楼。',
    'ruined industrial street': '荒废的工业街道',
    'ruined slum street': '破烂的贫民窟街道',
    'ruined commercial street': '被毁坏的商业街',
    'poisonous spiders': '毒蜘蛛',
    'Party': '队伍',
    'It seems there used to be shops and markets here, but there isn\'t much left except for ruins.': '这里以前似乎有商店和市场，但现在只剩下废墟了。',
    'It seems like this place was last used as a make-shift residential area, but there is nothing left but ruins.': '看起来这个地方最后被用作临时住宅区，但是除了废墟什么也没有留下。',
    'gigantic spiders': '巨型蜘蛛',
    'ghost bats': '幽灵蝙蝠',
    'cave bats': '穴居蝙蝠',
    'crumbling slum corridor': '摇摇欲坠的贫民窟走廊',
    'crumbling industrial corridor': '摇摇欲坠的工业走廊',
    'abandoned residential corridor': '废弃住宅走廊',
    'abandoned back alley': '废弃后巷',
    'A narrow, forgotten corridor running between two tall residential towers, with barely enough space to walk.': '一条狭窄的、被遗忘的走廊，位于两座高耸的住宅楼之间，几乎没有足够的空间行走。',
    'A narrow corridor between two massive shopping towers with barely enough space to walk.': '两大购物中心之间的狭窄走廊，几乎没有足够的空间行走。',
    'A former industrial sector where factories or workshops lie in ruins.': '以前的工业部门，那里的工厂或车间已成废墟。',
    'A filthy corridor packed so full of long-abandoned dark-dweller shacks that there is barely enough space to pass through.': '这条肮脏的走廊挤满了长期被遗弃的黑暗居民的棚屋，几乎没有足够的空间通过。',
    'A filthy corridor packed so full of long-abandoned…hat there is barely enough space to pass through.': '肮脏的走廊里挤满了长期被遗弃的东西，几乎没有足够的空间可以通过。',
    'A narrow, forgotten corridor running between two t…dential towers, with barely enough space to walk.': '一条狭窄的、被遗忘的走廊，位于两座塔之间，几乎没有足够的空间行走。',
    'There used to be homes here, but there isn\'t much left except for ruins.': '这里过去有很多房子，但现在只剩下废墟了。',
    'With this bag, weight is starting to be more of a problem than space.': '有了这个袋子，重量开始成为比空间更大的问题。',
    'Smooth stone that fits in the palm of a hand. There is something calming about it.': '手掌大小的光滑石头。有一种使人平静的东西。',
    'Keeping other animals away from food and materials for more reliable storage.': '让其他动物远离食物和材料，以便更可靠地储存。',
    'ruined slum square': '破烂的贫民窟广场',
    'ruined residential square': '荒废的住宅广场',
    'A mostly empty and desolate square with the remains of some broken cable systems criss-crossing the low ceiling.': '一个空荡荡的广场，低矮的天花板上纵横交错着一些破损的电缆系统的残骸。',
    'albino salamanders': '白化蝾螈',
    'camp': '营地',
    'Create and manipulate new, stronger fibers for better protection and easier manufacturing.': '创造和操作新的，更强的纤维，以更好的保护和更容易制造。',
    'Find out if there is anyone living here.': '看看是否有人住在这里。',
    'fire salamanders': '火蜥蜴',
    'food, water': '食物, 水',
    'Foreign camp': '外国营地',
    'Gas Masks': '防毒面具',
    'It seems like once people lived here, but there is nothing left but ruins.': '好像曾经有人住在这里，但这里只剩下废墟。',
    'It seems this used to be a market square of some sort, but there isn\'t much left except for ruins.': '这里似乎曾经是某种集市广场，但现在除了废墟已所剩无几。',
    'Mill Road Academy': '米尔路学院',
    'Protection against environmental hazards': '环境危害防护',
    'Researched Synthetic Fibers.': '研究了合成纤维。',
    'ruined commercial square': '荒废的商业广场',
    'ruined industrial square': '荒废的工业广场',
    'ruined maintenance square': '荒废失修广场',
    'A few large unidentifiable ruins loom over a gloomy industrial square.': '在一个阴暗的工业广场上隐约可见几处巨大的、无法辨认的废墟。',
    'Abandoned shop': '废弃的商店',
    'animals': '动物',
    'build': '建造',
    'duskboars': '野猪',
    'Elevator (Build)': '电梯（建造）',
    'Elevator Down (Build)': '下行电梯（建造）',
    'Elevator Up (Build)': '上行电梯（建造）',
    'Enables building huge structures to bridge levels when there is no existing staircase or elevator, and lays the foundation for more construction projects.': '在没有现有楼梯或电梯的情况下，可以建造巨大的桥梁，为更多的建设项目打下基础。',
    'Fortified the camp.': '加固了营地。',
    'ratsnakes': '鼠蛇',
    'Researched Engineering.': '研究工程。',
    'ruined residential street': '毁坏的住宅街道',
    'Trader from Slugger Town': '来自重击城的商人',
    'area too polluted': '污染严重地区',
    'crumbling back alley': '弯弯曲曲的小巷',
    'The air here is toxic.': '这里的空气有毒。',
    'Unnerving piece of black rock. Something is etched on it in an unfamiliar language.': '令人不安的黑色岩石。有些东西用一种不熟悉的语言刻在上面。',
    'Small leather pouch with a string that allows it to be worn around the neck. All it contains is some kind of a powder.': '有绳子的小皮袋，可以挂在脖子上。它只含有某种粉末。',
    'Gives a definite sense of security in dangerous environments.': '在危险的环境中给人一种明确的安全感。',
    'eavy key with a demonic eel-like ornament so intricately carved it feels almost alive. Strangely cold to the touch.': '这把钥匙带有恶魔般的鳗鱼般的装饰，雕工复杂，几乎让人觉得它是活的。摸起来出奇的冷。',
    'Long since dried and useless as a writing implement, but still popular among sages and philosophers as a symbol of knowledge.': '作为书写工具，它早已干枯无用，但作为知识的象征，它在圣贤和哲学家中仍然很受欢迎。',
    'A narrow corridor between two vast and decaying shopping towers with barely enough space to walk.': '一条狭窄的走廊，位于两座巨大而破旧的购物中心之间，几乎没有足够的步行空间。',
    'risky': '有风险',
    'Went scavenging.Fled empty-handed.': '去捡垃圾了。空手而逃。',
    'attack  +': '攻击 +',
    'Build': '建造',
    'Built projects': '建成项目',
    'cost': '成本',
    'Craft': '工艺',
    'Current followers': '当前追随者',
    'Current version': '当前版本',
    'defence  +': '防御  +',
    'Events': '事件',
    'Export / import your save data for backup or to continue playing on another computer.': '导出/导入保存数据以进行备份或继续在另一台计算机上玩。',
    'free / diseased': '空闲 / 患病',
    'health: -': '健康: -',
    'Health': '健康',
    'Import': '导入',
    'Import/export': '导入/导出',
    'Incoming caravans': '外来商队',
    'max': '最大',
    'max vision  +': '视野上限  +',
    'Maximum followers': '追随者上限',
    'More': '更多',
    'Name': '名称',
    'Save': '保存',
    'Soldier': '士兵',
    'Selected': '已选择',
    'Silver': '银',
    'Status': '状态',
    'Upgrade effects': '升级效果',
    'Upgrade name': '升级名称',
    'Upgrades': '升级',
    'Upgrade details': '升级详情',
    'Upgrade description': '升级描述',
    'Info': '信息',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //1.3.防具
    'Weapon': '武器',
    'Armor': '盔甲',
    'Arm': '盔甲',
    'Legs': '腿部',
    'Leg': '腿部',
    'Chest': '胸部',
    'Shoes': '脚部',
    'Foot': '脚部',
    'Shirt': '衬衫',
    'Hands': '手部',
    'Hand': '手部',
    'Head': '头部',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //1.4.战斗
    'easy': '容易',
    'a pest is blocking passage': '一只害虫挡住了去路',
    'Wanderer': '流浪者',
    'Fight won.': '战斗胜利',
    'deadly': '致命',
    'fight lost': '战斗失败',
    'a 害 is blocking passage': '一些害虫阻挡了去路',
    'surprised by a 害 while scavenging': '在清理时被一种害虫惊吓到了',
    'defeated': '被打败了',
    'Intruder defeated.': '入侵者被打败了。',
    'use spring': '使用泉水',
    'Refilled water at the well.': '把井里的水再灌满。',
    'a': '一个',
    'an': '一个',
    'Dropped bag while climbing a fence. Lost 1 spider silk.': '爬栅栏时把包掉了。丢失了1条蛛丝。',
    'use_spring': '使用泉水',
    'A more systematic approach to knowledge gathering and preservation. Will enable more specialized workers later on.': '更系统地收集和保存知识。以后可以雇佣更专业的工人。',
    'Inns': '旅馆',
    'Feels oddly comfortable in dark corridors and abandoned factories.': '在黑暗的走廊和废弃的工厂里，感觉出奇的舒适。',
    'Inn already exists': '旅馆已经存在了',
    'Laboratories': '实验室',
    'Library already exists': '图书馆已经存在',
    'Used to be the standard uniform in the dark levels of the City.': '曾经是城市黑暗层面的标准制服。',
    '': '',
    'Disband': '遣散',
    'Max followers reached.': '追随者已达到上限了。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //1.5.升级
    'Researched Field medicine.': '研究野战医学。',
    'Researched Rope-making.': '研究绳索制作。',
    'Treating basic injuries.': '治疗基本伤害。',
    'available': '可用',
    'locked': '未解锁',
    'researched': '已研究',
    'The craft of making clothes out of fabric.': '用布料制作衣服的工艺。',
    'Researched Sewing.': '研究了缝纫。',
    'Caravans': '商队',
    'Travelling to other factions to trade for goods': '前往其他势力进行货物贸易',
    'Sometimes strangers pass by the camp. Perhaps we can offer them a place to sleep?': '有时有陌生人经过营地。也许我们可以给他们提供一个睡觉的地方?',
    'Decent, reasonable shoes for walking in most places.': '适合在大多数地方行走的体面、合理的鞋子。',
    'Doesn\'t make one invincible, but feels like it.': '并不能让一个人所向披靡，但感觉就像这样。',
    'Building bridges over collapsed sectors.': '在倒塌的地区修建桥梁。',
    'Bridge': '桥梁',
    'scavenger': '清道夫',
    'Trade with people from foreign camps and cooperatives.': '与来自外国营地和合作社的人交易。',
    'Processing technique that allows more metal left behind by previous inhabitants to be salvaged.': '使以前的居民留下的更多的金属被打捞出来的技术。',
    'Managing bigger caravans that can carry more goods': '管理能够运送更多货物的大型商队',
    'Constructions to keep unwelcome strangers away.': '把不受欢迎的陌生人拒之门外。',
    'An ancient but effective weapon.': '一种古老而有效的武器。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //1.6.属性（30）
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //1.7.敌人 
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',


    //1.8.营地
    'A raid! The camp is under attack.': '突袭！ 营地受到攻击。',
    'Buildings': '建筑',
    'Entered camp.': '进入营地。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //1.9 日志
    'Building projects': '建筑工程',
    'Smelting': '熔炼',
    'Scavenger Gear': '拾荒装置',
    'Augmented clothing made to withstand the harshest of environments.': '强化过的衣服经得起最恶劣的环境。',
    'UV Protection': '紫外线防护',
    'Protection from sunlight.': '保护自己免受阳光伤害。',
    'Jet engine': '喷气发动机',
    'Taking weapons and fighting to a new level of destructiveness.': '将武器和战斗上升到一个新的破坏水平。',
    'Medicine': '医学',
    'Rediscovered modern technology for disease prevention and treatment.': '是现代的疾病预防和治疗技术。。',
    'Radio': '广播',
    'Build radio towers to increase your civilization\'s reputation.': '建造广播塔来提高你文明的声誉。',
    'Surgery': '手术',
    'Complex procedures for fixing the human body': '复杂的人体修复程序',
    'Augmented Clothing 1': '强化服1',
    'echniques for improving existing clothing for exploration': '为了探索需要，用科技改善现有服装的技术。',
    'Philosophy': '哲学',
    'Another way to find answers to questions.': '另一种寻找问题答案的方法。',
    'Concrete Fortifications': '混凝土防御工事',
    'Better fortifications': '有更好的防御',
    'Alchemy': '炼金术',
    'Basic knowledge of making herbal medicines.': '制作草药的基本知识。',
    'Good gloves to keep explorers safe': '保护探险者安全的好手套',
    'Glove-making': '手套制造',
    'Scientific Method': '科学方法',
    'An organized approach to growing new knowledge': '用一种有条理的方式来获取新知识。',
    'Food preservation': '食物保存',
    'Salting, smoking and pickling food to make it last longer.': '腌制，烟熏以及酸制食物，让它们保存更长的时间。',
    'Military': '军事',
    'A dedicated and trained class of workers for protecting and fighting.': '经受训练并奉献自身，来保护和作战的一类人。',
    'Getting tired. Should have a rest soon.': '你累了。 应该马上休息一下。',
    'Raid over. We drove the attackers away.': '突袭结束了。 我们把袭击者赶走了。',
    'Trader leaves.': '商人离开了。',
    'Lights already exists': '灯火已经存在了。',
    'Market already exists': '市场已经存在了。',
    'Installed lights to the camp.': '为营地安装了灯火。',
    'Built a market.': '建立了一个市场。',
    'Built an caravan stable.': '建造了一个商队马厩。',
    'Generator already exists': '发电机已经存在',
    'A fellow traveller who has agreed to travel together.': '同意一起旅行的同行者。',
    'Set up a generator.': '设置一个发电机。',
    'Slugger Town': '贫民窟',
    'Bigger caravans': '更大的商队',
    'stable': '马厩',
    'Caravan Stable': '商队马厩',
    'Concrete Fortification': '混凝土加固',
    'house': '房屋',
    'Terrible defences': '炮台防御',
    'trader': '商人',
    'Invalid selection.': '无效的选择。',
    'A trader arrives.': '一个商人到达了。',
    'There is no more food.': '没有更多的食物了。',
    'a few seconds ago': '刚刚',
    'ability': '能力',
    'All upgrades': '所有升级',
    'All is quiet in the camp.': '营地里一切都很安静。',
    'A wide street or corridor that doesn\'t seem to be in very good repair. It\'s hard to find anything in the vast darkness. There is no': '宽阔的街道或走廊似乎没有很好的维修。 在浩瀚的黑暗中很难找到任何东西。 没有',
    'Apothecary': '药剂师',
    'Available caravans': '可用的商队',
    'Available followers': '可用的追随者',
    'Available projects': '可用项目',
    'Available upgrades': '可用升级',
    'Blueprints': '蓝图',
    'Chemist': '化学家',
    'Close': '关闭',
    'fight': '战斗',
    'Followers': '追随者',
    'Stats': '统计',
    'sunblindness': '日光盲症',
    'sunblindness protection  +': '防盲 +',
    'Search': '搜索',
    'Sector details': '区域详情',
    'size': '大小',
    'Scavenger': '拾荒者',
    'Vision': '视野',
    'Use': '使用',
    'Trapper': '猎人',
    'Tribe': '部落',
    'Stamina': '耐力',
    'Restart': '重玩',
    'Resources': '资源',
    'Reset': '重置',
    'Resources found by scavenging: metal (common': '通过清除发现的资源:金属(常见',
    'Resources scavenged': '清理获得的资源',
    'Teleport': '传送',
    'Toolsmith': '工具师',
    'trade': '贸易',
    'Trade partners': '贸易伙伴',
    'Trader': '商人',
    'Trader inventory': '商人存货',
    'Your world seed': '你的世界种子',
    'Water collector': '集水器',
    'You don\'t have any followers': '您没有任何的追随者',
    'Are you sure you want to load this save? Your current progress will be lost.': '您确定要加载此存档吗？ 您当前的游戏进度将会丢失',
    'Camp defences': '营地防御',
    'Camp defences: +': '营地防御: +',
    'Camp overview': '营地概览',
    'Environment': '环境',
    'Equipment': '装备',
    'Increases scavenge loot': '增加清理的战利品',
    'Last raid': '上次突袭',
    'Loaded data': '加载的数据',
    'lvl pop': '人口级别',
    'Messages': '消息',
    'Evidence': '线索',
    'Game saved': '游戏已保存',
    'injury': '受伤几率',
    'Your pockets are empty.': '你的口袋是空的。',
    'less': '收起',
    'less than a minute ago': '不久前',
    'Notes, sketches, devices, parts, plans and experiments collected from the City.': '从城市收集的笔记、草图、设备、零件、计划和实验。',
    'Own strength': '自身实力',
    'Paused': '已暂停',
    'Wander': '游荡',
    'warmth  +': '保暖  +',
    'Save world seed': '存档的世界种子',
    'Scientist': '科学家',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}

//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
	[/^(\d+) minutes ago$/, '$1 分钟前'],
	[/^Save version: (.+)$/, '存档版本: $1'],
	[/^Save timestamp: (.+)$/, '存档时间戳: $1'],
	[/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
	[/^Usages: (\d+)\/$/, '用途：$1\/'],
	[/^workers: (\d+)\/$/, '工人：$1\/'],

]);

//2.采集新词
//20190320@JAR

var cnItem = function () {

    //传参是否非空字串
    if (!arguments[0]) return;

    //检验传参是否对象
    let text = arguments[0],
        s = '';
    if (typeof (text) != "string")
        return text;
    else
        s = arguments[0].charCodeAt();

    //检验传参是否英文
    // if (
    //     s < 65 || (s > 90 && s < 97) || (s > 122)
    //
    // ) return text;

    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix = cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix];
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0];
            text = text.substr(0, text.length - text_reg_exclude_postfix.length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return arguments[0];
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (
            text == i || text == cnItems[i] &&
            cnItems[i] != ''
        )
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : arguments[0]
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return arguments[0];
    }

    if (cnItems._OTHER_.length < 500) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function (a, b) {
                return a.localeCompare(b)
            }
        );
    }

    /*
        //开启生词打印
        //console.log(
            '有需要汉化的英文：', text
        );
    */

    //返回生词字串
    return arguments[0];
};

transTaskMgr = {
    tasks: [],
    addTask: function (node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function () {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "TEXTAREA" && subnode.innerHTML && subnode.innerText) {
                if (subnode.innerHTML === subnode.innerText) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function () {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function (e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.innerHTML && mutation.target.innerText && mutation.target.innerHTML === mutation.target.innerText) {
                mutation.target.innerText = cnItem(mutation.target.innerText);
            } else if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "TEXTAREA" && node.innerHTML && node.innerText) {
                        if (node.innerHTML === node.innerText) {
                            node.innerText = cnItem(node.innerText);
                        } else {
                            TransSubTextNode(node);
                            transTaskMgr.doTask();
                        }
                    }
                }
            }
        }
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
}();
