/*var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?437daaace550a2581826916a1ff60768";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();*/

// 站长工具

var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan style='display:none;' id='cnzz_stat_icon_1253112090'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s95.cnzz.com/z_stat.php%3Fid%3D1253112090' type='text/javascript'%3E%3C/script%3E"));
var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan style='display:none;' id='cnzz_stat_icon_1254712307'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s11.cnzz.com/z_stat.php%3Fid%3D1254712307' type='text/javascript'%3E%3C/script%3E"));
//document.getElementById('cnzz_stat_icon_1253112090').style.display='none';

/* (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-49804115-1', 'play68.com');
ga('send', 'pageview'); */

  /*var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//89.35.play68.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();*/
(function(s,n){"object"===typeof exports&&"undefined"!==typeof module?n(exports):"function"===typeof define&&define.amd?define("DCAgent",["exports"],n):n(s.DCAgent={})})(this,function(s){function n(){}function ka(a){var b,c;b=Date.now();c="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c;c=(b+16*Math.random())%16|0;b=Math.floor(b/16);return"x"===a?c.toString(16):(c&7|8).toString(16)});return(a||"")+c.replace(/-/g,"").toUpperCase()}function la(a){var b,c;for(b in a)c=a[b],a[b]=
c;(2<=arguments.length?[].slice.call(arguments,1):[]).forEach(function(d){var f;f=[];for(b in d)c=d[b],f.push(a[b]=c);return f});return a}function k(a,b,c){if("function"===typeof a)try{return a.apply(b,c)}catch(d){h("attemp error for "+a.toString(),d.stack)}}function ma(a,b,c){function d(){!1!==k(a)&&J(d,b)}c?d():J(d,b)}function h(a,b){console.log("#DCAgent: "+a);b&&console.log(b)}function na(a){try{return a.setItem(".","."),a.removeItem("."),!0}catch(b){return!1}}function y(a,b){a=m(a);p.setItem(a,
b);U.set(a,b,365);return b}function C(a){a=m(a);return p.getItem(a)||U.get(a)}function m(a){if(K||L===a)return a;e.appId||h("appid should not be empty when you are in native env");return e.appId+"."+a}function oa(a){var b=u.hash,c="!"+a;if(b){var d=/![0-9A-Z]{32,128}/gi;(b=b.match(d))?(b=b[0].slice(1),a===b||C(V)||(e.parentId=b,y(V,b)),u.href=u.href.replace(d,c)):u.href+=c}else u.href+="#"+c}function W(a,b,c,d){var f={data:{online:{},events:a||[],errors:b||[]},success:d};c&&(f.data.reg=c);a=M(z);
b=M(D);if(a.length||b.length)p.removeItem(m(z)),p.removeItem(m(D)),f.data.events=f.data.events.concat(a),f.data.errors=f.data.errors.concat(b),f.error=function(){e.debug&&h("report failed, restoring data to localStorage");E(f.data.events,z);E(f.data.errors,D)};X(f,Y)}function Z(a,b,c){a={page:encodeURIComponent(a||pa),optime:parseInt(e.initializedOn),ottime:parseInt(Date.now()/1E3),lttime:parseInt(e.loginTime/1E3)};W([{eventid:"_DESelf_PV",labelmap:JSON.stringify(a),duration:"1"}],null,b,function(){N+=
1;k(c)})}function qa(){if(F)return F;O+=1;if(!(4<O)){var a={egret:"egret",cocos:"cc.game",impact:"ig",phaser:"Phaser",pixi:"PIXI",create:"createjs",three:"THREE",gameMaker:"asset_get_type",playCanvas:"pc.fw",turbulenz:"TurbulenzEngine",quintus:"Quintus",melon:"me.game",lychee:"lychee",wade:"wade.addSceneObject",crafty:"Crafty",lime:"lime.Scene",enchant:"enchant",isogenic:"IgeEngine",gameclosure:"GC.Application",panda:"game.Scene",kiwi:"Kiwi",jaws:"jaws",sirius2d:"ss2d",collie:"collie",physics:"Physics",
stage:"Stage.Anim",babylon:"BABYLON"},b;for(b in a){var c=a[b];if(-1<c.indexOf(".")){var c=c.split("."),d=g[c[0]];if(d&&d[c[1]])return F=b}else if(g[c])return F=b}}}function ra(){var a;P||(P={appid:e.appId,accountid:e.accountId,uid:e.deviceId,appver:e.appVer,ver:$,channel:e.channel,domain:q.domain||"",screen:sa,logintime:String(parseInt(e.loginTime/1E3)),crtime:C(A)||""});a=P;a.onlinetime=e.intervalCount*e.interval/1E3||1;a.pv=N.toString();a.engine=qa()||"";return a}function ta(a){var b=new g.XMLHttpRequest;
b.timeout=aa;b.open("POST",a.url,!0);b.setRequestHeader("Content-Type","text/plain; charset=UTF-8");var c=Date.now();b.onreadystatechange=function(){if(4===this.readyState){var b=200<=this.status&&300>this.status,f=Date.now()-c;k(b?a.success:a.error,this,[this,f]);k(a.complete,this,[this,f]);this.timeout=this.onreadystatechange=null}};b.timeout=function(){var b=Date.now()-c;k(a.error,this,[this,b,!0]);k(a.complete,this,[this,b]);this.timeout=this.onreadystatechange=null};b.send(JSON.stringify(a.data))}
function ua(a){var b=new egret.URLLoader,c=Date.now();b.addEventListener(egret.Event.COMPLETE,function(b){var d=Date.now()-c;b=b.target;k("success"===b.data?a.success:a.error,b,[b,d,d>=aa]);k(a.complete,b,[b,d])});var d=new egret.URLRequest(a.url);d.method=egret.URLRequestMethod.POST;d.data=JSON.stringify(a.data);b.load(d)}function X(a,b){if(a.data){a.data.errors&&a.data.errors.length>v.max&&(e.debug&&h("sending too many errors, only "+v.max+" allowed"),a.data.errors=a.data.errors.slice(0,v.max));
for(var c in a.data)"number"===typeof a.data[c]&&(a.data[c]=String(a.data[c]));c=Math.abs(e.onlinetime);c>va||0>=c?e.debug&&h("illegal online time: "+c):(c=la({headers:ra()},a.data),wa({url:b,data:c,success:function(b,c){t.succ=1;t.fail=0;t.total=c;k(a.success,b,[b,c])},error:function(b,c,g){t.succ=0;t.fail+=1;t.total+=c;k(a.error,b,[b,c,g]);g&&e.debug&&h("report timeout, network infomation",t)},complete:function(b,c){E({eventid:xa,labelmap:JSON.stringify(t),duration:"1"},z);k(a.complete,b,[b,c])}}),
e.debug&&h("report data:",c))}}function M(a){a=m(a);try{var b=JSON.parse(p.getItem(a));return Array.isArray(b)?b:[]}catch(c){return p.removeItem(a),[]}}function E(a,b){b=m(b);var c=M(b);Array.isArray(a)?a.forEach(function(a){return c.push(a)}):c.push(a);p.setItem(b,JSON.stringify(c))}function ya(){g.addEventListener&&g.addEventListener("error",function(a){k(function(){if(v.isReportAllowed(a.filename)){v.count+=1;var b={};["colno","filename","lineno","message"].forEach(function(c){return b[c]=a[c]||
"0"});var c=a.error||{};b.stack=c.stack||"";b.type=c.name||"Error";b.timestamp=parseInt(a.timeStamp/1E3);E(b,D)}})},!1)}function za(){k(function(){if(g[G])g[G]=null;else if("function"===typeof define&&define.amd)require.undef(G);else if("object"===typeof s&&"undefined"!==typeof module){var a=require.resolve(G);delete require.cache[a]}else h("unknown module system, unload DCAgent manually please");h("DCAgent has been destroyed.")})}function Aa(){if(ba)return za(),!1;q.hidden||(e.intervalCount+=1,B.setItem(m(Q),
e.intervalCount),W());return!0}function R(a,b){if(!w.isAgentReady()){var c=[a];[].forEach.call(b,function(a){return c.push(a)});H.push(c);return!0}}function Ba(a){a=m(a);try{var b=JSON.parse(p.getItem(a));return Array.isArray(b)?b:[]}catch(c){return p.removeItem(a),[]}}function Ca(a,b){b=m(b);var c=Ba(b);Array.isArray(a)?a.forEach(function(a){return c.push(a)}):c.push(a);p.setItem(b,JSON.stringify(c))}function ca(a,b,c){if(!a)h("invoke failed, missing eventId");else if(!R("onEvent",arguments)){null==
b&&(b=0);var d,e;if(c&&"[object Object]"===Da.call(c)){for(d in c)e=c[d],c[d]=encodeURIComponent(e);d=JSON.stringify(c)}else d="";Ca({eventid:a,duration:String(b),labelmap:d},z)}}function da(a){R("onPageView",arguments)||Z(a)}function ea(a){a&&a.hasOwnProperty("amount")&&!R("onPayment",arguments)&&(a.amount=parseFloat(a.amount)||0,X({data:{payment:{currencyAmount:a.amount.toFixed(2),currencyType:a.currencyType||"CNY",payType:String(a.payType||""),iapid:String(a.iapid||""),orderId:String(a.orderId||
""),payTime:String(a.payTime||"")}}},Y))}function fa(a,b,c,d){b&&y(L,a);e.deviceId=a;e.accountId=e.accountId||a;var f=B.getItem(m(ga));f||(f=Date.now(),B.setItem(m(ga),f));e.loginTime=f;f=B.getItem(m(Q));f||(f="0",B.setItem(m(Q),f));e.intervalCount=parseInt(f);e.interval=1E3*Math.max(10,parseFloat(c.interval||e.interval));e.virus&&Ea(a);c.errorReport&&(c.excludes&&(v.excludes=v.excludes.concat(c.excludes)),ya());c=null;b&&(c={isact:b,isreg:1},e.parentId&&(c.parentid=e.parentId),r.localStorage||(c.localstorage=
1));e.initializedOn=Date.now()/1E3;C(A)||y(A,e.initializedOn);Z(null,c,function(){w.setReadyState(3);for(var b={onEvent:ca,onPageView:da,onPayment:ea},c=0,f=H.length;c<f;c++){var h=H[c];b[h.shift()].apply(g,h)}H.length=0;ma(Aa,e.interval);"function"===typeof d&&d(a)})}function Fa(a){function b(c){k(function(){if(0===ha.indexOf(c.origin)){var d=JSON.parse(c.data);g.removeEventListener("message",b,!1);y(A,d.crtime);a(d.id)}})}g.addEventListener("message",b,!1);var c=q.createElement("iframe");c.style.display=
"none";c.src=ha;c.onload=function(){this.onload=null;this.parentNode.removeChild(this)};var d=function(){return q.body.appendChild(c)};q.body?d():q.addEventListener("DOMContentLoaded",d,!1)}function Ga(a){y(A,parseInt(Date.now()/1E3));var b;b=r.engine.egret?ia+Ha:ia+Ia;a(ka(b))}var x=(0,eval)("this"),g=x||{},q=x.document||{},u=x.location||{},e={appId:"",deviceId:"",accountId:"",channel:"",appVer:"",interval:10,intervalCount:0,loginTime:0,debug:g.DCAGENT_DEBUG_OPEN},r={get engine(){return S},get localStorage(){return Ja},
get sessionStorage(){return Ka},get postMessage(){return La},get realBrowser(){return K},get cookie(){return Ma}},l;"function"===typeof q.createElement&&(x=q.createElement("div"),x.innerHTML="<i></i>","function"===typeof x.querySelector&&(l=x.querySelector("i"),l=!!l&&"I"===l.tagName));var S={egret:"undefined"!==typeof egret},Ja=!!g.localStorage||!!S.egret,Ka=!!g.sessionStorage,La=!!g.postMessage,K=!!l,Ma=K&&"cookie"in q,J=g.setTimeout;S.egret&&(J=function(a,b){egret.setTimeout(a,g,b)});var Da=Object.prototype.toString;
l={getItem:n,setItem:n,removeItem:n};var p=r.localStorage?g.localStorage:l,B=r.sessionStorage?g.sessionStorage:l;r.engine.egret&&(p=egret.localStorage);var A="dcagent_create_time",ia="ND",Ha="EGRET",Ia="UE",V="dcagent_parent_id",z="dcagent_client_events",D="dcagent_client_errors",ga="dcagent_login_time",Q="dcagent_interval_key",L="dcagent_client_id",Y="http://rd.gdatacube.net/dc/html5/sync",ha="http://rd.gdatacube.net/dc/html5/whoami",xa="_DESelf_OSS",aa=3E4,G="DCAgent",va=172800,ja,U=ja=r.cookie?
{get:function(a){return(a=q.cookie.match(new RegExp("(^|)\\s*"+a+"=([^\\s]*)")))&&3<=a.length?decodeURIComponent(a[2]):null},set:function(a,b,c,d,e,g){var h;c&&(h=new Date,h.setTime(h.getTime()+864E5*c));c=c?" expires="+h.toGMTString():"";e=" path="+(e||"/");d=d?" domain="+d:"";g=g?" secure":"";q.cookie=a+"="+encodeURIComponent(b)+c+e+d+g},remove:function(a,b,c){ja.set(a,"",-1,b,c)}}:{get:n,set:n,remove:n},Ea=r.realBrowser?oa:n,I={max:100,count:0,excludes:[],isReportAllowed:function(a){if(I.count<
I.max)return I.excludes.every(function(b){return-1===a.indexOf(b)})}},v=I,N=0,pa=r.realBrowser?u.pathname+u.search:"/",$="15";s.version=$;l=g.screen||{};var sa=l.width?l.width+"*"+l.height:"0*0",F,O=0,P,t={succ:0,fail:0,total:0},wa=function(){if(g.XMLHttpRequest)return ta;if(r.engine.egret)return ua;h("unknow platform, http request is not support");return n}(),ba=!1;s.teardown=function(){ba=!0};var T=0,w={getReadyState:function(){return T},setReadyState:function(a){T=a},isAgentReady:function(){return 3===
T}},H=[];s.onEvent=ca;s.onPageView=da;s.onPayment=ea;var Na=r.postMessage&&r.realBrowser?Fa:Ga;s.init=function(a,b){if(na(p))if(0<w.getReadyState())h("DCAgent.init should be called only once");else if(a=a||{},a.appId){["errorReport","virus"].forEach(function(b){return e[b]=a.hasOwnProperty(b)?!!a[b]:!0});["appId","accountId","appVer"].forEach(function(b){return e[b]=a[b]||""});e.channel=a.channel||q.referrer||"";var c=C(L);c?fa(c,0,a,b):(w.setReadyState(1),Na(function(c){w.setReadyState(2);fa(c,1,
a,b)}))}else h("init failed, missing appId");else r.localStorage?h("localstorage qouta error, private mode?"):h("localstorage is not supported.")};l=w.isAgentReady;Object.defineProperty(s,"readyState",{get:function(){h("DCAgent.readyState is obsolete, use DCAgent.isReady() instead");return w.getReadyState()}});s.isReady=l});
