var scorelevel=0;
var layers={};var whose_turn=g_WhosTurn;var b_qpbg_x_p=0;var b_qpbg_y_p=0;var qpbg_x_p=0;var qpbg_y_p=0;var wySprite=null;var scoreSprite=null;var no1Sprite=null;var no2Sprite=null;var no3Sprite=null;var greatSprite=null;var qpbgSprite=null;var game_level=null;var boards_Sprite=[];var boards_position=[];var move_opers=[];var move_dis=null;var move_speed=0;var r1=0;var r2=0;var r3=0;var r4=0;var r1_f=0;var r2_f=0
var r3_f=0;var r4_f=0;var StartUI=cc.LayerColor.extend({ctor:function(){this._super();var bgSprite=cc.Sprite.create(res.m_bg);bgSprite.setAnchorPoint(0,0);bgSprite.setPosition(0,0);this.addChild(bgSprite);},onEnter:function(){this._super();cc.eventManager.addListener({event:cc.EventListener.TOUCH_ONE_BY_ONE,onTouchBegan:function(touch,event){var pos=touch.getLocation();if(pos.y<=79*cc.winSize.height/100&&pos.y>=54*cc.winSize.height/100&&pos.x>=12*cc.winSize.width/100&&pos.x<=90*cc.winSize.width/100){cc.log("StartUI OnEnter Introduction page");gameScene.addChild(layers.introUI,g_GameZOrder.front);}
    if(pos.y<=45*cc.winSize.height/100&&pos.y>=20*cc.winSize.height/100&&pos.x>=25*cc.winSize.width/100&&pos.x<=80*cc.winSize.width/100){cc.log("StartUI OnEnter StartGame page");gameScene.addChild(layers.gameUI,g_GameZOrder.ui);layers.startUI.removeFromParent();}
    return true;}},this);}});var IntroUI=cc.Layer.extend({ctor:function(){this._super();var bgSprite=cc.Sprite.create(res.i_bg);bgSprite.setAnchorPoint(0,0);bgSprite.setPosition(0,0);this.addChild(bgSprite);},onEnter:function(){this._super();cc.eventManager.addListener({event:cc.EventListener.TOUCH_ONE_BY_ONE,swallowTouches:true,onTouchEnded:function(touch,event){cc.log("IntroUI onTouchBegan");layers.introUI.removeFromParent();return true;},onTouchBegan:function(touch,event){return true;}},this);}});var FailedUI=cc.Layer.extend({ctor:function(){this._super();var bgSprite=cc.Sprite.create(res.failed_pannel);bgSprite.setAnchorPoint(0.5,0.5);bgSprite.setPosition(cc.winSize.width/2,cc.winSize.height/2);this.addChild(bgSprite);var notify=new cc.Sprite(res.notify);notify.setAnchorPoint(0.5,0.5);notify.setPosition(cc.p(cc.winSize.width*27/100,cc.winSize.height*33/100));this.addChild(notify);var replay=new cc.Sprite(res.again);replay.setAnchorPoint(0.5,0.5);replay.setPosition(cc.p(cc.winSize.width*73/100,cc.winSize.height*33/100));this.addChild(replay);var smad1Sprite=cc.Sprite.create(res.smad1);smad1Sprite.setAnchorPoint(0.5,0);smad1Sprite.setPosition(cc.winSize.width/2,0)
    this.addChild(smad1Sprite);},onEnter:function(){this._super();cc.eventManager.addListener({event:cc.EventListener.TOUCH_ONE_BY_ONE,onTouchBegan:function(touch,event){return true;},onTouchEnded:function(touch,event){var pos=touch.getLocation();if(pos.y>cc.winSize.height*20/100&&pos.y<cc.winSize.height*45/100){if(pos.x<cc.winSize.width*45/100){dp_share();}
else if(pos.x>cc.winSize.width*55/100){cc.log("FailedUI play again");layers.failedUI.removeFromParent();cc.log("FailedUI player again");clearAllDatas();initBoard(game_level);noShow();}}
    if(pos.y<cc.winSize.height*15/100){cc.log("ResultUI smad1 has been clicked");}}},this);},onExit:function(){this._super();}});var SuccessUI=cc.Layer.extend({ctor:function(){this._super();var bgSprite=cc.Sprite.create(res.success_pannel);bgSprite.setAnchorPoint(0.5,0.5);bgSprite.setPosition(cc.winSize.width/2,cc.winSize.height/2);this.addChild(bgSprite);var notify=new cc.Sprite(res.notify);notify.setAnchorPoint(0.5,0.5);notify.setPosition(cc.p(cc.winSize.width*27/100,cc.winSize.height*33/100));this.addChild(notify);var replay=new cc.Sprite(res.again);replay.setAnchorPoint(0.5,0.5);replay.setPosition(cc.p(cc.winSize.width*73/100,cc.winSize.height*33/100));this.addChild(replay);var smad1Sprite=cc.Sprite.create(res.smad1);smad1Sprite.setAnchorPoint(0.5,0);smad1Sprite.setPosition(cc.winSize.width/2,0)
    this.addChild(smad1Sprite);},onEnter:function(){this._super();cc.eventManager.addListener({event:cc.EventListener.TOUCH_ONE_BY_ONE,onTouchBegan:function(touch,event){return true;},onTouchEnded:function(touch,event){var pos=touch.getLocation();if(pos.y>cc.winSize.height*20/100&&pos.y<cc.winSize.height*45/100){if(pos.x<cc.winSize.width*45/100){cc.log("SuccessUI notify friends");gameScene.addChild(layers.shareUI,g_GameZOrder.ui);}
else if(pos.x>cc.winSize.width*55/100){cc.log("SuccessUI play again");layers.successUI.removeFromParent();cc.log("SuccessUI player again");clearAllDatas();game_level=g_GameLevel.level2;initBoard(game_level);noShow();}}
    if(pos.y<cc.winSize.height*15/100){cc.log("ResultUI smad1 has been clicked");}}},this);},onExit:function(){this._super();}});var ShareUI=cc.LayerColor.extend({ctor:function(){this._super();var bgSprite=cc.Sprite.create(res.share_bg);bgSprite.setAnchorPoint(0.5,0.5);bgSprite.setPosition(cc.winSize.width/2,cc.winSize.height/2);this.addChild(bgSprite);
    // var smad2Sprite=cc.Sprite.create(res.smad2);
    // smad2Sprite.setAnchorPoint(0.5,0);
    // smad2Sprite.setPosition(this.width/2,0);
    // this.addChild(smad2Sprite);
},onEnter:function(){share("qld");}});var GameUI=cc.Layer.extend({ctor:function(){this._super();var bgSprite=cc.Sprite.create(res.g_bg,g_GameZOrder.bg);bgSprite.setAnchorPoint(0,0);bgSprite.setPosition(0,0);this.addChild(bgSprite,g_GameZOrder.bg);var sunSprite=cc.Sprite.create(res.sun);sunSprite.setAnchorPoint(0.5,0.5);sunSprite.setPosition(cc.p(cc.winSize.width*85/100,cc.winSize.height*90/100));this.addChild(sunSprite,g_GameZOrder.ui);var sunRotate=cc.RotateBy.create(10,360);var rep=cc.RepeatForever.create(sunRotate);sunSprite.runAction(rep);scoreSprite=cc.Sprite.create(res.score1);scoreSprite.setAnchorPoint(0,0.5);scoreSprite.setPosition(cc.p(0,cc.winSize.height*90/100));this.addChild(scoreSprite);cc.spriteFrameCache.addSpriteFrames(res.wy_plist,res.wy);var wyFrame=cc.spriteFrameCache.getSpriteFrame("wy_1.png");wySprite=cc.Sprite.createWithSpriteFrame(wyFrame);wySprite.setAnchorPoint(0.5,0.5);wySprite.setPosition(-cc.winSize.width*20/100,cc.winSize.height*75/100);this.addChild(wySprite,g_GameZOrder.ui);var animFrames=[];for(var i=0;i<4;i++){var str="wy_"+(i+1)+".png";var frame=cc.spriteFrameCache.getSpriteFrame(str);if(frame){animFrames.push(frame);}}
    var animation=cc.Animation.create(animFrames,0.1);wySprite.runAction(cc.RepeatForever.create(cc.Animate.create(animation)));var moveAction=cc.MoveTo.create(8,cc.p(cc.winSize.width*130/100,cc.winSize.height*75/100));wySprite.runAction(moveAction);this.schedule(this.wy_move,30);no1Sprite=cc.Sprite.create(res.no1);no1Sprite.setPosition(cc.winSize.width/2,cc.winSize.height*40/100);this.addChild(no1Sprite,g_GameZOrder.front);no1Sprite.setVisible(false);no2Sprite=cc.Sprite.create(res.no2);no2Sprite.setPosition(cc.winSize.width/2,cc.winSize.height*40/100);this.addChild(no2Sprite,g_GameZOrder.front);no2Sprite.setVisible(false);no3Sprite=cc.Sprite.create(res.no3);no3Sprite.setPosition(cc.winSize.width/2,cc.winSize.height*40/100);this.addChild(no3Sprite,g_GameZOrder.front);no3Sprite.setVisible(false);var b_qpbgSprite=cc.Sprite.create(res.b_qpbg);b_qpbgSprite.setAnchorPoint(0.5,0.5);b_qpbgSprite.setPosition(cc.winSize.width*50/100,cc.winSize.height*35/100);this.addChild(b_qpbgSprite);b_qpbg_x_p=b_qpbgSprite.x-b_qpbgSprite.width/2;b_qpbg_y_p=b_qpbgSprite.y-b_qpbgSprite.height/2;qpbgSprite=cc.Sprite.create(res.qpbg);qpbgSprite.setAnchorPoint(0.5,0.5);qpbgSprite.setPosition(b_qpbgSprite.width/2,b_qpbgSprite.height/2);b_qpbgSprite.addChild(qpbgSprite);qpbg_x_p=qpbgSprite.x-qpbgSprite.width/2;qpbg_y_p=qpbgSprite.y-qpbgSprite.height/2;greatSprite=cc.Sprite.create(res.greate);greatSprite.setPosition(qpbgSprite.getPosition().x,qpbgSprite.getPosition().y);greatSprite.setAnchorPoint(0.5,0.5);greatSprite.setVisible(false);qpbgSprite.addChild(greatSprite,g_GameZOrder.front);game_level=g_GameLevel.level2;initBoard(game_level);setTimeout(noShow,1500);},wy_move:function(){cc.log("GameUI wy_move");var moveAction=cc.MoveTo.create(8,cc.p(cc.winSize.width*120/100,cc.winSize.height*75/100));wySprite.runAction(moveAction);setTimeout(this.wy_startP,15000);},wy_startP:function(){cc.log("GameUI wy_startP");wySprite.setPosition(-cc.winSize.width*20/100,cc.winSize.height*75/100);},onEnter:function(){this._super();cc.eventManager.addListener({touch_row:10,event:cc.EventListener.TOUCH_ONE_BY_ONE,swallowTouches:true,onTouchBegan:function(touch,event){if(whose_turn!=g_WhosTurn.player){return true;}
    cc.log("Touch x:"+touch.getLocation().x+"   y:"+touch.getLocation().y);show_boardsPosition(game_level);for(var i=0;i<boards_Sprite.length;i++){if(isPointInBoard(touch.getLocation(),boards_Sprite[i])){if(judgeSuccess(i)==j_SuccState.success){cc.log("click the right board");if(game_level==g_GameLevel.level6){cc.log("game level6 success");gameScene.addChild(layers.successUI,g_GameZOrder.ui);}else{greatShow();}
        whose_turn=g_WhosTurn.AI;}else if(judgeSuccess(i)==j_SuccState.failed){cc.log("click the wrong board");dp_submitScore(scorelevel);gameScene.addChild(layers.failedUI,g_GameZOrder.ui);whose_turn=g_WhosTurn.AI;}}}},onTouchEnded:function(touch,event){},onTouchMoved:function(touch,event){}},this);}});function judgeSuccess(i){cc.log("judgeSuccess  i:"+i+"   r1:"+r1+"   r2:"+r2+"   r3:"+r3+"   r4:"+r4);if(game_level==g_GameLevel.level2){if(i==r1){boards_Sprite[i].initWithFile(res.jhs_logo);r1_f=1;return j_SuccState.success;}else{boards_Sprite[r1].initWithFile(res.jhs_logo);return j_SuccState.failed;}}
    if(game_level==g_GameLevel.level3||game_level==g_GameLevel.level4){if(i==r1||i==r2){if(i==r1){boards_Sprite[i].initWithFile(res.jhs_logo);r1_f=1;}
        if(i==r2){boards_Sprite[i].initWithFile(res.he_logo);r2_f=1;}}
    else{boards_Sprite[r1].initWithFile(res.jhs_logo);boards_Sprite[r2].initWithFile(res.he_logo);return j_SuccState.failed;}
        if(r1_f==1&&r2_f==1){return j_SuccState.success;}else{return j_SuccState.nosure;}}
    if(game_level==g_GameLevel.level5){if(i==r1||i==r2||i==r3){if(i==r1){boards_Sprite[i].initWithFile(res.jhs_logo);r1_f=1;}
        if(i==r2){boards_Sprite[i].initWithFile(res.he_logo);r2_f=1;}
        if(i==r3){boards_Sprite[i].initWithFile(res.ln139_logo);r3_f=1;}}
    else{boards_Sprite[r1].initWithFile(res.jhs_logo);boards_Sprite[r2].initWithFile(res.he_logo);boards_Sprite[r3].initWithFile(res.ln139_logo);return j_SuccState.failed;}
        if(r1_f==1&&r2_f==1&&r3_f==1){return j_SuccState.success;}else{return j_SuccState.nosure;}}
    if(game_level==g_GameLevel.level6){if(i==r1||i==r2||i==r3||i==r4){if(i==r1){boards_Sprite[i].initWithFile(res.jhs_logo);r1_f=1;}
        if(i==r2){boards_Sprite[i].initWithFile(res.he_logo);r2_f=1;}
        if(i==r3){boards_Sprite[i].initWithFile(res.ln139_logo);r3_f=1;}
        if(i==r4){boards_Sprite[i].initWithFile(res.injoin7_logo);r4_f=1;}}
    else{boards_Sprite[r1].initWithFile(res.jhs_logo);boards_Sprite[r2].initWithFile(res.he_logo);boards_Sprite[r3].initWithFile(res.ln139_logo);boards_Sprite[r4].initWithFile(res.injoin7_logo);return j_SuccState.failed;}
        if(r1_f==1&&r2_f==1&&r3_f==1&&r4_f==1){return j_SuccState.success;}else{return j_SuccState.nosure;}}}
function isPointInBoard(point,board){if(cc.rectContainsPoint(board.getBoundingBoxToWorld(),point)){return true;}else{return false;}}
function initBoard(code){var num=0;var scale=0;var dis_div=0;if(code==g_GameLevel.level2||code==g_GameLevel.level3){move_dis=100;}else{move_dis=75;}
    if(code==g_GameLevel.level2||code==g_GameLevel.level3||code==g_GameLevel.level4||code==g_GameLevel.level5){move_speed=MoveSpeed.normal;}else{move_speed=MoveSpeed.fast;}
    game_level=code;switch(code){case g_GameLevel.level1:num=4;scale=0.6;dis_div=2;break;case g_GameLevel.level2:num=9;scale=0.4;dis_div=3;break;case g_GameLevel.level3:num=9;scale=0.4;dis_div=3;break;case g_GameLevel.level4:num=16;scale=0.34;dis_div=4;case g_GameLevel.level5:num=16;scale=0.34;dis_div=4;break;case g_GameLevel.level6:num=16;scale=0.34;dis_div=4;break;default:break;}
    r1=getRandNo(num-1,[100]);r2=getRandNo(num-1,[r1]);r3=getRandNo(num-1,[r1,r2]);r4=getRandNo(num-1,[r1,r2,r3]);r1_f=0;r2_f=0;r3_f=0;r4_f=0;cc.log("GameUI initBoard r1:"+r1+"   r2:"+r2+"   r3:"+r3+"r4:"+r4);for(var i=0;i<num;i++){var boardSprite=null;if(i==r1){boardSprite=cc.Sprite.create(res.jhs_logo);}
        if(code==g_GameLevel.level3||code==g_GameLevel.level4||code==g_GameLevel.level5||code==g_GameLevel.level6){if(i==r2){boardSprite=cc.Sprite.create(res.he_logo);}}
        if(code==g_GameLevel.level5||code==g_GameLevel.level6){if(i==r3){boardSprite=cc.Sprite.create(res.ln139_logo);}}
        if(code==g_GameLevel.level6){if(i==r4){boardSprite=cc.Sprite.create(res.injoin7_logo);}}
        if(boardSprite==null){boardSprite=cc.Sprite.create(res.board_null);}
        boardSprite.setAnchorPoint(0.5,0.5);boardSprite.setScale(scale);boardSprite.setPosition(qpbgSprite.width/(dis_div*2)+(qpbgSprite.width/dis_div)*(i%dis_div),qpbgSprite.height/(dis_div*2)+(qpbgSprite.height/dis_div)*parseInt(i/dis_div));qpbgSprite.addChild(boardSprite);boards_Sprite.push(boardSprite);if(i%dis_div==0){boards_position.push([]);}
        boards_position[parseInt((i/dis_div))][i%dis_div]=i;}
    show_boardsPosition(code);}
function show_boardsPosition(code){var row=0;var col=0;if(code==g_GameLevel.level1||code==g_GameLevel.level2||code==g_GameLevel.level3){row=3;col=3;}
    if(code==g_GameLevel.level4||code==g_GameLevel.level5||code==g_GameLevel.level6){row=4;col=4;}
    for(var i=row-1;i>=0;i--){if(col==3){cc.log("["+i+"]   "+boards_position[i][0]+" "+boards_position[i][1]+" "+boards_position[i][2]);}
        if(col==4){cc.log("["+i+"]   "+boards_position[i][0]+" "+boards_position[i][1]+" "+boards_position[i][2]+" "+boards_position[i][3]);}}}
function startGame(){if(game_level==g_GameLevel.level2){boards_Sprite[r1].initWithFile(res.board_null);}
    if(game_level==g_GameLevel.level3||game_level==g_GameLevel.level4){boards_Sprite[r1].initWithFile(res.board_null);boards_Sprite[r2].initWithFile(res.board_null);}
    if(game_level==g_GameLevel.level5){boards_Sprite[r1].initWithFile(res.board_null);boards_Sprite[r2].initWithFile(res.board_null);boards_Sprite[r3].initWithFile(res.board_null);}
    if(game_level==g_GameLevel.level6){boards_Sprite[r1].initWithFile(res.board_null);boards_Sprite[r2].initWithFile(res.board_null);boards_Sprite[r3].initWithFile(res.board_null);boards_Sprite[r4].initWithFile(res.board_null);}
    set_moveOper();show_MoveOpers();startMove();}
function startMove(){cc.log("startMove-----------------move_speed"+move_speed);show_MoveOpers();if(game_level==g_GameLevel.level2||game_level==g_GameLevel.level3){var i=0;for(i=0;i<move_opers.length;i++){switch(move_opers[i].cl){case 0:setTimeout("move_l2_sc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;case 1:setTimeout("move_l2_mc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;case 2:setTimeout("move_l2_bc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;default:setTimeout("move_l2_bc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;}}
    setTimeout("setPlayerTurn()",(i+1)*(1000+200)*move_speed);}
    if(game_level==g_GameLevel.level4||game_level==g_GameLevel.level5||game_level==g_GameLevel.level6){var i=0;for(i=0;i<move_opers.length;i++){switch(move_opers[i].cl){case 0:setTimeout("move_l4_sc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;case 1:setTimeout("move_l4_mc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;case 2:setTimeout("move_l4_bc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;default:setTimeout("move_l4_bc("+move_opers[i].po+")",(i+1)*(1000+200)*move_speed);break;}}
        setTimeout("setPlayerTurn()",(i+1)*(1000+200)*move_speed);}}
function setPlayerTurn(){cc.log("setPlayerTurn-----------------------r1:"+r1+"   r2:"+r2+"   r3:"+r3+" r4:"+r4);whose_turn=g_WhosTurn.player;show_boardsPosition(game_level);}
function set_moveOper(){cc.log("set_moveOper gamelevel:"+game_level);var t_looper=6;if(game_level==g_GameLevel.level2||game_level==g_GameLevel.level3){t_looper=getRandNo(3,[100])+4;}else{t_looper=getRandNo(3,[100])+6;if(game_level==g_GameLevel.level6){t_looper=t_looper+getRandNo(3,[100])+6;}}
    for(var i=0;i<t_looper;i++){if(game_level==g_GameLevel.level2||game_level==g_GameLevel.level3){var t_cl=getRandNo(3,[100]);var t_po=getRandNo(4,[100])+1;var t_st=getRandNo(3,[100])+1;if(t_st==3){if(getRandNo(2,[100])){t_st=3;}else{t_st=2;}}
        for(var j=0;j<t_st;j++){var op={cl:1,po:1,di:1};op.cl=t_cl;op.po=t_po;move_opers.push(op);}}
        if(game_level==g_GameLevel.level4||game_level==g_GameLevel.level5||game_level==g_GameLevel.level6){var t_cl=getRandNo(4,[100]);var t_po=getRandNo(4,[100])+1;var t_st=getRandNo(3,[100])+1;if(t_st==3){if(getRandNo(2,[100])){t_st=3;}else{t_st=2;}}
            for(var j=0;j<t_st;j++){var op={cl:1,po:1,di:1};op.cl=t_cl;op.po=t_po;move_opers.push(op);}}}}
function move_l4_sc(p){if(getRandNo(6,[100])==8){move_l4_sc_all(p);}else{move_l4_sc_some(p);}}
function move_l4_sc_all(p){move_l4_sc_s(1);move_l4_sc_s(2);move_l4_sc_s(3);move_l4_sc_s(4);show_boardsPosition(game_level);}
function move_l4_sc_some(p){move_l4_sc_s(p);move_l4_sc_s(p+4);show_boardsPosition(game_level);}
function move_l4_sc_s(p){var x_p=0;var y_p=0;switch(p){case 1:x_p=0;y_p=0;break;case 2:x_p=2;y_p=0;break;case 3:x_p=0;y_p=2;break;case 4:x_p=2;y_p=2;break;default:break;}
    switch(p){case 5:x_p=2;y_p=1;break;case 8:x_p=0;y_p=1;break;case 7:x_p=1;y_p=0;break;case 6:x_p=1;y_p=2;break;default:break;}
    boards_Sprite[boards_position[0+x_p][0+y_p]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[0+x_p][0+y_p]],move_dis)));boards_Sprite[boards_position[0+x_p][1+y_p]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0+x_p][1+y_p]],move_dis)));boards_Sprite[boards_position[1+x_p][0+y_p]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1+x_p][0+y_p]],move_dis)));boards_Sprite[boards_position[1+x_p][1+y_p]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[1+x_p][1+y_p]],move_dis)));p0=boards_position[0+x_p][0+y_p];p1=boards_position[0+x_p][1+y_p];p2=boards_position[1+x_p][0+y_p];p3=boards_position[1+x_p][1+y_p];boards_position[0+x_p][0+y_p]=p2;boards_position[0+x_p][1+y_p]=p0;boards_position[1+x_p][0+y_p]=p3;boards_position[1+x_p][1+y_p]=p1;}
function move_l4_mc(p){switch(p){case 1:move_l4_mc_s(1);if(getRandNo(2,[100])==1){move_l4_mc_s(2);}else{if(getRandNo(2,[100])==1){move_l4_sc_s(2);}else{move_l4_sc_s(4);}}
    break;case 2:move_l4_mc_s(2);if(getRandNo(2,[100])==1){move_l4_mc_s(1);}else{if(getRandNo(2,[100])==1){move_l4_sc_s(1);}else{move_l4_sc_s(3);}}
    break;case 3:move_l4_mc_s(3);if(getRandNo(2,[100])==1){move_l4_mc_s(4);}else{if(getRandNo(2,[100])==1){move_l4_sc_s(4);}else{move_l4_sc_s(3);}}
    break;case 4:move_l4_mc_s(4);if(getRandNo(2,[100])==1){move_l4_mc_s(3);}else{if(getRandNo(2,[100])==1){move_l4_sc_s(1);}else{move_l4_sc_s(2);}}
    break;default:break;}}
function move_l4_mc_s(p){var x_p=0;var y_p=0;switch(p){case 1:x_p=0;y_p=0;break;case 2:x_p=2;y_p=0;break;case 3:x_p=0;y_p=0;break;case 4:x_p=0;y_p=2;default:break;}
    if(p==1||p==2){move_l4_mc_s_h(x_p);}
    if(p==3||p==4){move_l4_mc_s_s(y_p);}}
function move_l4_mc_s_h(x_p){boards_Sprite[boards_position[0+x_p][1]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0+x_p][1]],move_dis)));boards_Sprite[boards_position[0+x_p][2]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0+x_p][2]],move_dis)));boards_Sprite[boards_position[0+x_p][3]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0+x_p][3]],move_dis)));boards_Sprite[boards_position[0+x_p][0]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0+x_p][0]],move_dis)));boards_Sprite[boards_position[1+x_p][0]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[1+x_p][0]],move_dis)));boards_Sprite[boards_position[1+x_p][1]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[1+x_p][1]],move_dis)));boards_Sprite[boards_position[1+x_p][2]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[1+x_p][2]],move_dis)));boards_Sprite[boards_position[1+x_p][3]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1+x_p][3]],move_dis)));p0=boards_position[0+x_p][0];p1=boards_position[0+x_p][1];p2=boards_position[0+x_p][2];p3=boards_position[0+x_p][3];p4=boards_position[1+x_p][3];p5=boards_position[1+x_p][2];p6=boards_position[1+x_p][1];p7=boards_position[1+x_p][0];boards_position[0+x_p][0]=p1;boards_position[0+x_p][1]=p2;boards_position[0+x_p][2]=p3;boards_position[0+x_p][3]=p4;boards_position[1+x_p][3]=p5;boards_position[1+x_p][2]=p6;boards_position[1+x_p][1]=p7;boards_position[1+x_p][0]=p0;}
function move_l4_mc_s_s(y_p){boards_Sprite[boards_position[0][1+y_p]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0][1+y_p]],move_dis)));boards_Sprite[boards_position[0][0+y_p]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0][0+y_p]],move_dis)));boards_Sprite[boards_position[1][0+y_p]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[1][0+y_p]],move_dis)));boards_Sprite[boards_position[2][0+y_p]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[2][0+y_p]],move_dis)));boards_Sprite[boards_position[3][0+y_p]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[3][0+y_p]],move_dis)));boards_Sprite[boards_position[3][1+y_p]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[3][1+y_p]],move_dis)));boards_Sprite[boards_position[2][1+y_p]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[2][1+y_p]],move_dis)));boards_Sprite[boards_position[1][1+y_p]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1][1+y_p]],move_dis)));p0=boards_position[0][0+y_p];p1=boards_position[0][1+y_p];p2=boards_position[1][1+y_p];p3=boards_position[2][1+y_p];p4=boards_position[3][1+y_p];p5=boards_position[3][0+y_p];p6=boards_position[2][0+y_p];p7=boards_position[1][0+y_p];boards_position[0][0+y_p]=p1;boards_position[0][1+y_p]=p2;boards_position[1][1+y_p]=p3;boards_position[2][1+y_p]=p4;boards_position[3][1+y_p]=p5;boards_position[3][0+y_p]=p6;boards_position[2][0+y_p]=p7;boards_position[1][0+y_p]=p0;}
function move_l4_bc(p){move_l2_sc(4);boards_Sprite[boards_position[3][0]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[3][0]],move_dis)));boards_Sprite[boards_position[3][1]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[3][1]],move_dis)));boards_Sprite[boards_position[3][2]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[3][2]],move_dis)));boards_Sprite[boards_position[0][0]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0][0]],move_dis)));boards_Sprite[boards_position[1][0]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[1][0]],move_dis)));boards_Sprite[boards_position[2][0]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[2][0]],move_dis)));boards_Sprite[boards_position[0][3]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0][3]],move_dis)));boards_Sprite[boards_position[0][2]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0][2]],move_dis)));boards_Sprite[boards_position[0][1]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[0][1]],move_dis)));boards_Sprite[boards_position[3][3]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[3][3]],move_dis)));boards_Sprite[boards_position[2][3]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[2][3]],move_dis)));boards_Sprite[boards_position[1][3]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1][3]],move_dis)));p0=boards_position[0][0];p1=boards_position[0][1];p2=boards_position[0][2];p3=boards_position[0][3];p4=boards_position[1][3];p5=boards_position[2][3];p6=boards_position[3][3];p7=boards_position[3][2];p8=boards_position[3][1];p9=boards_position[3][0];p10=boards_position[2][0];p11=boards_position[1][0];boards_position[0][0]=p1;boards_position[0][1]=p2;boards_position[0][2]=p3;boards_position[0][3]=p4;boards_position[1][3]=p5;boards_position[2][3]=p6;boards_position[3][3]=p7;boards_position[3][2]=p8;boards_position[3][1]=p9;boards_position[3][0]=p10;boards_position[2][0]=p11;boards_position[1][0]=p0;}
function move_l2_sc(p){cc.log("move_l2_sc===================");var x_p=0;var y_p=0;switch(p){case 1:x_p=0;y_p=0;break;case 2:x_p=1;y_p=0;break;case 3:x_p=0;y_p=1;break;case 4:x_p=1;y_p=1;break;default:break;}
    boards_Sprite[boards_position[0+x_p][0+y_p]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[0+x_p][0+y_p]],move_dis)));boards_Sprite[boards_position[0+x_p][1+y_p]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0+x_p][1+y_p]],move_dis)));boards_Sprite[boards_position[1+x_p][0+y_p]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1+x_p][0+y_p]],move_dis)));boards_Sprite[boards_position[1+x_p][1+y_p]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[1+x_p][1+y_p]],move_dis)));p0=boards_position[0+x_p][0+y_p];p1=boards_position[0+x_p][1+y_p];p2=boards_position[1+x_p][0+y_p];p3=boards_position[1+x_p][1+y_p];boards_position[0+x_p][0+y_p]=p2;boards_position[0+x_p][1+y_p]=p0;boards_position[1+x_p][0+y_p]=p3;boards_position[1+x_p][1+y_p]=p1;show_boardsPosition(game_level);}
function move_l2_bc(p){cc.log("move_l2_bc===================");boards_Sprite[boards_position[0][0]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[0][0]],move_dis)));boards_Sprite[boards_position[0][1]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[0][1]],move_dis)));boards_Sprite[boards_position[0][2]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0][2]],move_dis)));boards_Sprite[boards_position[1][2]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[1][2]],move_dis)));boards_Sprite[boards_position[2][2]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[2][2]],move_dis)));boards_Sprite[boards_position[2][1]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[2][1]],move_dis)));boards_Sprite[boards_position[2][0]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[2][0]],move_dis)));boards_Sprite[boards_position[1][0]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1][0]],move_dis)));p0=boards_position[0][0];p1=boards_position[0][1];p2=boards_position[0][2];p3=boards_position[1][2];p4=boards_position[2][2];p5=boards_position[2][1];p6=boards_position[2][0];p7=boards_position[1][0];boards_position[0][0]=p7;boards_position[0][1]=p0;boards_position[0][2]=p1;boards_position[1][2]=p2;boards_position[2][2]=p3;boards_position[2][1]=p4;boards_position[2][0]=p5;boards_position[1][0]=p6;show_boardsPosition(game_level);}
function move_l2_mc(p){cc.log("move_l2_mc===================");var x_p=0;if(p==1||p==3){x_p=0;}else{x_p=1;}
    boards_Sprite[boards_position[0+x_p][0]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[0+x_p][0]],move_dis)));boards_Sprite[boards_position[0+x_p][1]].runAction(cc.moveTo(move_speed,move_right(boards_Sprite[boards_position[0+x_p][1]],move_dis)));boards_Sprite[boards_position[0+x_p][2]].runAction(cc.moveTo(move_speed,move_up(boards_Sprite[boards_position[0+x_p][2]],move_dis)));boards_Sprite[boards_position[1+x_p][2]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[1+x_p][2]],move_dis)));boards_Sprite[boards_position[1+x_p][1]].runAction(cc.moveTo(move_speed,move_left(boards_Sprite[boards_position[1+x_p][1]],move_dis)));boards_Sprite[boards_position[1+x_p][0]].runAction(cc.moveTo(move_speed,move_down(boards_Sprite[boards_position[1+x_p][0]],move_dis)));p0=boards_position[0+x_p][0];p1=boards_position[0+x_p][1];p2=boards_position[0+x_p][2];p3=boards_position[1+x_p][2];p4=boards_position[1+x_p][1];p5=boards_position[1+x_p][0];boards_position[0+x_p][0]=p5;boards_position[0+x_p][1]=p0;boards_position[0+x_p][2]=p1;boards_position[1+x_p][2]=p2;boards_position[1+x_p][1]=p3;boards_position[1+x_p][0]=p4;show_boardsPosition(game_level);}
function show_MoveOpers(){for(var i=0;i<move_opers.length;i++){cc.log("["+i+"]  cl:"+move_opers[i].cl+"   po:"+move_opers[i].po+"    di:"+move_opers[i].di);}}
function greatShow(){var noAction1=cc.MoveBy.create(NO_TIME*2,cc.p(0,cc.winSize.height*3/100));var noAction2=cc.FadeOut.create(NO_TIME*2);var noActions=[noAction1,noAction2];var swap=cc.Spawn.create(noActions);greatSprite.stopAllActions();greatSprite.setVisible(true);greatSprite.setOpacity(255);greatSprite.setPosition(qpbgSprite.getPosition().x,qpbgSprite.getPosition().y);var cf=cc.CallFunc.create(nextLevel,greatSprite,null);greatSprite.runAction(cc.Sequence.create(swap,cf));}
function nextLevel(){scorelevel++;game_level++;cc.log("nextLevel game level:"+game_level);setTimeout("nextLevelInit()",500);}
function nextLevelInit(){clearAllDatas();setTimeout("initBoard("+game_level+")",300);setTimeout("noShow()",1000);}
function clearAllDatas(){for(var i=0;i<boards_Sprite.length;i++){boards_Sprite[i].removeFromParent();}
    boards_Sprite=[];boards_position=[];move_opers=[];switch(game_level){case g_GameLevel.level2:scoreSprite.initWithFile(res.score1);scoreSprite.setAnchorPoint(0,0.5);break;case g_GameLevel.level3:scoreSprite.initWithFile(res.score3);scoreSprite.setAnchorPoint(0,0.5);break;case g_GameLevel.level4:scoreSprite.initWithFile(res.score4);scoreSprite.setAnchorPoint(0,0.5);break;case g_GameLevel.level5:scoreSprite.initWithFile(res.score5);scoreSprite.setAnchorPoint(0,0.5);break;case g_GameLevel.level6:scoreSprite.initWithFile(res.score6);scoreSprite.setAnchorPoint(0,0.5);break;default:break;}}
function noShow(){var noAction1=cc.MoveBy.create(NO_TIME,cc.p(0,cc.winSize.height*10/100));var noAction2=cc.FadeOut.create(NO_TIME);var noActions=[noAction1,noAction2];var swap=cc.Spawn.create(noActions);no1Sprite.stopAllActions();no1Sprite.setVisible(true);no1Sprite.setOpacity(255);no1Sprite.setPosition(cc.winSize.width*50/100,cc.winSize.height*35/100);var cf=cc.CallFunc.create(no2Show,no1Sprite,null);no1Sprite.runAction(cc.Sequence.create(swap,cf));}
function no2Show(){var noAction1=cc.MoveBy.create(NO_TIME,cc.p(0,cc.winSize.height*10/100));var noAction2=cc.FadeOut.create(NO_TIME);var noActions=[noAction1,noAction2];var swap=cc.Spawn.create(noActions);no2Sprite.stopAllActions();no2Sprite.setVisible(true);no2Sprite.setOpacity(255);no2Sprite.setPosition(cc.winSize.width*50/100,cc.winSize.height*35/100);var cf=cc.CallFunc.create(no3Show,no2Sprite,null);no2Sprite.runAction(cc.Sequence.create(swap,cf));}
function no3Show(){var noAction1=cc.MoveBy.create(NO_TIME,cc.p(0,cc.winSize.height*10/100));var noAction2=cc.FadeOut.create(NO_TIME);var noActions=[noAction1,noAction2];var swap=cc.Spawn.create(noActions);no3Sprite.stopAllActions();no3Sprite.setVisible(true);no3Sprite.setOpacity(255);no3Sprite.setPosition(cc.winSize.width*50/100,cc.winSize.height*35/100);no3Sprite.runAction(cc.Sequence.create(swap));setTimeout(startGame,1000);}
var GameScene=cc.Scene.extend({onEnter:function(){this._super();layers.startUI=new StartUI();this.addChild(layers.startUI);layers.introUI=new IntroUI();layers.gameUI=new GameUI();layers.failedUI=new FailedUI();layers.successUI=new SuccessUI();layers.shareUI=new ShareUI();}});var gameScene=null;
//eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('(1(){2 a=3.p(\'4\');a.e=\'d/c\';a.h=g;a.f=\'6://9.8.7/m/o.k\';2 b=3.n(\'4\')[0];b.5.j(a,b);a.i=1(){a.5.l(a)}})();',26,26,'|function|var|document|script|parentNode|http|com|9g|game|||javascript|text|type|src|true|async|onload|insertBefore|js|removeChild|dtsl|getElementsByTagName||createElement'.split('|'),0,{}))